import type { Tool } from "@/lib/catalog/types";

/**
 * Finance calculators. Live ones work in any country (choose a currency); the
 * country tax calculators are "coming-soon" until they can be kept exactly up to
 * date with each tax year. The loan, mortgage and compound interest calculators
 * live in ./more.ts and belong to this category too.
 */
const added = "2026-10-01";
const updatedAt = "2026-10-01";
const base = { category: "finance", status: "live" as const, addedAt: added, updatedAt };

export const financeTools: Tool[] = [
  /* ——— Pay & income ——— */
  {
    ...base,
    slug: "salary-converter",
    group: "pay",
    name: "Hourly to Salary Calculator",
    primaryKeyword: "hourly to salary calculator",
    description: "Convert hourly pay to a yearly salary and back — plus monthly, weekly and pro-rata part-time pay.",
    icon: "wallet",
    popular: true,
    keywords: ["hourly to salary", "salary to hourly", "salary calculator", "pro rata salary", "part time salary calculator", "annual salary", "how much is $20 an hour a year"],
    steps: ["Enter your pay and whether it's per hour, day, week, month or year.", "Set your hours and paid weeks.", "See it as hourly, daily, weekly, monthly and yearly pay."],
    about: "Turns any rate of pay into every other: an hourly wage into a yearly salary, a salary into an hourly rate, and everything in between. A second calculator works out pro-rata pay for part-time hours.",
    useCases: ["Compare a salaried job with an hourly one.", "Work out your part-time (pro-rata) salary.", "Check what a pay rise means per hour."],
    related: ["savings-goal-calculator", "calculators/percentage-calculator", "vat-calculator"],
    notes: ["Pro-rata salary", "Any currency"],
    faqs: [
      { q: "How much is $20 an hour a year?", a: "At 40 hours a week for 52 weeks, $20 an hour is $41,600 a year before tax. Fewer hours or unpaid time off lower it." },
      { q: "How do I work out a pro-rata salary?", a: "Multiply the full-time salary by your weekly hours and divide by the full-time hours. £30,000 at 22.5 of 37.5 hours is £18,000." },
      { q: "Is this before or after tax?", a: "Before tax (gross). Take-home pay depends on your country's income tax and deductions." },
    ],
    guide: [
      { title: "Paid weeks, not working weeks", body: ["Paid holidays still count, so most full-time employees should use 52 weeks. Use fewer only for unpaid time — for example contractors or seasonal work."] },
      { title: "Common full-time hours", body: ["Full-time is usually 40 hours a week in the US and Canada, 37.5–40 in the UK and 38 in Australia. Using your contract's hours gives the most accurate hourly rate."] },
    ],
    metaTitle: "Hourly to Salary Calculator — Hourly, Monthly & Yearly Pay",
    metaDescription: "Convert hourly pay to yearly salary and back, with monthly, weekly and daily pay. Includes a pro-rata salary calculator for part-time hours.",
  },

  /* ——— Homes & property ——— */
  {
    ...base,
    slug: "mortgage-affordability-calculator",
    group: "home",
    name: "Mortgage Affordability Calculator",
    title: "How Much House Can I Afford?",
    primaryKeyword: "how much house can i afford",
    description: "See the home price you could afford from your income, debts, deposit and mortgage rate.",
    icon: "key",
    popular: true,
    keywords: ["how much house can i afford", "mortgage affordability calculator", "affordability calculator", "how much mortgage can i get", "borrowing power", "home affordability"],
    steps: ["Enter your income, monthly debts and deposit.", "Add the mortgage rate and term.", "See the price you could afford and the monthly payment."],
    about: "Estimates the most expensive home you could afford using the debt-to-income ratios lenders commonly use: housing costs within about 28% of income, and all debts within about 36%. It includes property tax and insurance, and shows your loan-to-income multiple.",
    useCases: ["Set a realistic budget before house hunting.", "See how a bigger deposit or lower rate changes your budget.", "Check whether paying off a car loan first helps."],
    related: ["mortgage-calculator", "rent-vs-buy-calculator", "savings-goal-calculator"],
    notes: ["Uses lender ratios", "Includes tax and insurance"],
    faqs: [
      { q: "How much house can I afford on my salary?", a: "A common rule is that housing costs shouldn't exceed about 28% of your gross monthly income, and all debts about 36%. On $90,000 a year with few debts, that's roughly $2,100 a month for housing." },
      { q: "How do UK and Australian lenders decide?", a: "Many UK lenders cap borrowing at around 4.5 times income, and Australian lenders assess “serviceability” with a rate buffer. The calculator shows your loan-to-income multiple so you can compare." },
      { q: "Should I borrow the maximum?", a: "Not necessarily. The maximum assumes nothing changes; leaving room in your budget protects you if rates or costs rise." },
    ],
    guide: [
      { title: "The 28/36 rule", body: ["Many US lenders like housing costs (mortgage, property tax, insurance) under 28% of gross income, and total debt payments under 36%. You can change both limits in the calculator to match a lender or your own comfort level."] },
    ],
    metaTitle: "How Much House Can I Afford? Affordability Calculator",
    metaDescription: "Find out how much house you can afford from your income, debts, deposit and mortgage rate, using the 28/36 rule lenders use. Any currency.",
  },
  {
    ...base,
    slug: "rent-vs-buy-calculator",
    group: "home",
    name: "Rent vs Buy Calculator",
    primaryKeyword: "rent vs buy calculator",
    description: "Compare the real cost of renting and buying over the years you plan to stay.",
    icon: "building",
    keywords: ["rent vs buy calculator", "should i rent or buy", "renting vs buying a house", "buy or rent"],
    steps: ["Enter the home price, deposit, mortgage rate and your rent.", "Set how long you'll stay.", "See which is cheaper and when buying pays off."],
    about: "Compares the net cost of buying a home — deposit, payments, tax, maintenance and selling costs, minus what you get when you sell — with renting and investing the deposit instead. It also finds the year buying starts to win.",
    useCases: ["Decide whether to buy now or keep renting.", "See how long you need to stay for buying to pay off.", "Test what happens if prices grow slower than expected."],
    related: ["mortgage-affordability-calculator", "mortgage-calculator", "rental-yield-calculator"],
    notes: ["Break-even year", "Adjustable assumptions"],
    faqs: [
      { q: "Why does renting sometimes win?", a: "Buying has big up-front and selling costs. If you move within a few years, those costs often outweigh the equity you build." },
      { q: "What matters most in the result?", a: "How long you stay, how fast home prices grow, and the return you'd earn by investing the deposit instead. Try changing those first." },
    ],
    guide: [
      { title: "What the comparison includes", body: ["Buying: deposit, buying costs, mortgage payments, property tax, maintenance and insurance, minus the sale price after selling costs and the remaining loan.", "Renting: rent that rises each year, minus the growth you'd earn by investing the deposit and buying costs instead."] },
    ],
    metaTitle: "Rent vs Buy Calculator — Is It Cheaper to Rent or Buy?",
    metaDescription: "Compare renting and buying a home over the years you'll stay: net costs, the break-even year and how price growth changes the answer.",
  },
  {
    ...base,
    slug: "rental-yield-calculator",
    group: "home",
    name: "Rental Yield Calculator",
    primaryKeyword: "rental yield calculator",
    description: "Work out the gross and net rental yield of a buy-to-let or investment property.",
    icon: "house-plus",
    keywords: ["rental yield calculator", "buy to let yield", "gross rental yield", "net rental yield", "investment property calculator"],
    steps: ["Enter the price and buying costs.", "Add the monthly rent, running costs and vacancy.", "See the gross and net yield."],
    about: "Shows how much a rental property earns compared with what it costs to buy. Gross yield uses the rent alone; net yield subtracts running costs and time empty, and includes buying costs like stamp duty.",
    useCases: ["Compare investment properties.", "Check whether a rent covers your costs.", "See how vacancies change your return."],
    related: ["rent-vs-buy-calculator", "roi-calculator", "mortgage-calculator"],
    notes: ["Gross and net yield"],
    faqs: [
      { q: "What is a good rental yield?", a: "Gross yields of about 5–8% are often considered reasonable, but it depends heavily on the city and how much the property is expected to grow in value." },
      { q: "Gross vs net yield?", a: "Gross is yearly rent ÷ price. Net takes off running costs and empty periods and adds buying costs to the price — it's the more realistic number." },
    ],
    guide: [
      { title: "Before mortgage and tax", body: ["Yield measures the property itself, so mortgage interest and income tax aren't included. Use the loan and ROI calculators to see the return on your own money."] },
    ],
    metaTitle: "Rental Yield Calculator — Gross & Net Yield",
    metaDescription: "Calculate the gross and net rental yield of an investment property, including buying costs, running costs and vacancy. Any currency.",
  },

  /* ——— Loans & debt ——— */
  {
    ...base,
    slug: "auto-loan-calculator",
    group: "borrow",
    name: "Auto Loan Calculator",
    title: "Auto Loan Calculator (Car Loan)",
    primaryKeyword: "auto loan calculator",
    description: "Find your monthly car payment with trade-in, down payment, sales tax and fees.",
    icon: "car",
    popular: true,
    keywords: ["auto loan calculator", "car loan calculator", "car payment calculator", "car finance calculator", "trade in calculator"],
    steps: ["Enter the car price, down payment and trade-in.", "Add sales tax, fees, the rate and term.", "See the monthly payment and total cost."],
    about: "Works out a car loan payment the way dealers do: price plus sales tax and fees, minus your down payment and trade-in equity. It also handles owing money on your trade-in and shows the total interest.",
    useCases: ["Check a dealer's monthly payment quote.", "Compare 48, 60 and 72-month loans.", "See how a bigger down payment saves interest."],
    related: ["loan-calculator", "debt-payoff-calculator", "calculators/percentage-calculator"],
    notes: ["Trade-in and sales tax"],
    faqs: [
      { q: "Is sales tax charged before or after the trade-in?", a: "In most US states, only on the price after the trade-in credit, which saves money. A few states tax the full price — switch the option off for those." },
      { q: "Is a longer loan a good idea?", a: "A 72 or 84-month loan lowers the payment but costs more interest, and you may owe more than the car is worth for longer." },
    ],
    guide: [
      { title: "Negative equity", body: ["If you owe more on your trade-in than it's worth, that difference is added to the new loan. The calculator shows it so it doesn't come as a surprise."] },
    ],
    metaTitle: "Auto Loan Calculator — Car Payment with Trade-In & Tax",
    metaDescription: "Calculate your monthly car payment with trade-in, down payment, sales tax and fees, plus total interest. Compare 36 to 84-month loans.",
  },
  {
    ...base,
    slug: "debt-payoff-calculator",
    group: "borrow",
    name: "Debt Payoff Calculator",
    primaryKeyword: "debt payoff calculator",
    description: "Plan your way out of debt — compare the avalanche and snowball methods side by side.",
    icon: "trending-down",
    popular: true,
    keywords: ["debt payoff calculator", "debt snowball calculator", "debt avalanche calculator", "pay off debt", "debt free date"],
    steps: ["List your debts with balance, rate and minimum payment.", "Add any extra you can pay each month.", "See your debt-free date and total interest for each method."],
    about: "Builds a month-by-month payoff plan for several debts at once. Compare the avalanche method (highest interest rate first, least interest overall) with the snowball method (smallest balance first, quicker early wins).",
    useCases: ["Find your debt-free date.", "See how much an extra payment saves.", "Choose between snowball and avalanche."],
    related: ["credit-card-payoff-calculator", "loan-calculator", "savings-goal-calculator"],
    notes: ["Snowball vs avalanche"],
    faqs: [
      { q: "Snowball or avalanche — which is better?", a: "Avalanche always costs the least interest. Snowball pays off small debts first, which many people find motivating. The calculator shows the real difference for your debts — often it's small." },
      { q: "What happens when one debt is paid off?", a: "Its minimum payment rolls onto the next debt, which is why payoff speeds up over time." },
    ],
    guide: [
      { title: "Why minimums must cover interest", body: ["If a minimum payment is smaller than the interest added each month, that debt grows forever. The calculator warns you so you can raise it."] },
    ],
    metaTitle: "Debt Payoff Calculator — Snowball vs Avalanche",
    metaDescription: "Plan your debt-free date. Compare the debt snowball and avalanche methods for all your debts, and see how extra payments save interest.",
  },
  {
    ...base,
    slug: "credit-card-payoff-calculator",
    group: "borrow",
    name: "Credit Card Payoff Calculator",
    primaryKeyword: "credit card payoff calculator",
    description: "See how long it takes to pay off a credit card, or what to pay to clear it by a date.",
    icon: "credit-card",
    keywords: ["credit card payoff calculator", "credit card interest calculator", "pay off credit card", "credit card calculator"],
    steps: ["Enter your balance and APR.", "Choose a monthly payment, or a number of months.", "See the payoff time, payment and total interest."],
    about: "Works out how long a credit card balance takes to clear at a fixed monthly payment, or the payment needed to clear it in a set number of months — and how much interest you'll pay either way.",
    useCases: ["Set a payment that clears your card in a year.", "See the true cost of paying a little each month.", "Compare paying more now with paying for longer."],
    related: ["debt-payoff-calculator", "loan-calculator", "savings-goal-calculator"],
    notes: ["Two ways to plan"],
    faqs: [
      { q: "Why does my balance barely go down?", a: "At 20–30% APR, a large share of each payment is interest. Paying even a little more each month cuts the time and interest a lot." },
      { q: "Does this include new purchases?", a: "No — it assumes you stop using the card while you pay it off." },
    ],
    guide: [
      { title: "How card interest is charged", body: ["APR is a yearly rate, but cards charge it monthly: 24% APR is about 2% a month on the balance. On a $5,000 balance that's roughly $100 of interest in the first month alone — which is why small payments barely move the balance."] },
    ],
    metaTitle: "Credit Card Payoff Calculator — Time & Interest",
    metaDescription: "Calculate how long it takes to pay off a credit card, or the monthly payment to clear it by a date, and how much interest you'll pay.",
  },

  /* ——— Saving & investing ——— */
  {
    ...base,
    slug: "savings-goal-calculator",
    group: "save",
    name: "Savings Goal Calculator",
    primaryKeyword: "savings goal calculator",
    description: "Find how much to save each month to reach a goal — or how long it will take.",
    icon: "target",
    keywords: ["savings goal calculator", "savings calculator", "how much to save each month", "saving for a house deposit", "emergency fund calculator"],
    steps: ["Enter your goal and what you've already saved.", "Add your savings interest rate.", "See the monthly amount needed, or how long it takes."],
    about: "Plans a savings goal — a deposit, a car, an emergency fund — either by working out the monthly amount needed by a date, or how long it takes at a monthly amount you choose. Interest is included.",
    useCases: ["Save a house deposit by a target date.", "Build an emergency fund.", "Plan for a holiday or wedding."],
    related: ["compound-interest-calculator", "retirement-calculator", "salary-converter"],
    notes: ["Two ways to plan", "Interest included"],
    faqs: [
      { q: "How much should my emergency fund be?", a: "A common guideline is three to six months of essential expenses." },
      { q: "Does the interest rate matter much?", a: "For short goals, not a lot — the amount you save does most of the work. Over several years, interest adds up noticeably." },
    ],
    guide: [
      { title: "Where to keep the money", body: ["For goals within a few years, an easy-access or high-interest savings account keeps the money safe and available. Investing suits longer goals, where there's time to ride out ups and downs."] },
    ],
    metaTitle: "Savings Goal Calculator — How Much to Save a Month",
    metaDescription: "Work out how much to save each month to reach a savings goal, or how long it will take, with interest included. Any currency.",
  },
  {
    ...base,
    slug: "retirement-calculator",
    group: "save",
    name: "Retirement Calculator",
    primaryKeyword: "retirement calculator",
    description: "Project your retirement savings in today's money and see if you're on track.",
    icon: "palm",
    keywords: ["retirement calculator", "retirement savings calculator", "how much do i need to retire", "4% rule", "pension calculator"],
    steps: ["Enter your age, savings and monthly contributions.", "Set an expected return, inflation and the income you want.", "See your projected savings and any shortfall."],
    about: "Projects your retirement savings, converts the result into today's money so it's easy to understand, and compares it with the savings you'd need for the income you want — using a withdrawal rate such as the 4% rule.",
    useCases: ["Check if you're saving enough for retirement.", "See the effect of retiring a few years later.", "Find how much more to save each month."],
    related: ["compound-interest-calculator", "savings-goal-calculator", "inflation-calculator"],
    notes: ["In today's money", "Shortfall shown"],
    faqs: [
      { q: "What is the 4% rule?", a: "A rule of thumb that withdrawing about 4% of your savings in the first year, then adjusting for inflation, has historically lasted around 30 years. It's a guide, not a guarantee." },
      { q: "Does it include state pensions or Social Security?", a: "No. Enter the income you want from your own savings, on top of any state pension." },
    ],
    guide: [
      { title: "Real vs nominal money", body: ["A million in 30 years won't buy what a million buys today. The calculator divides the future balance by inflation over the same period, so the headline figure is in today's money — the number you can actually picture."] },
    ],
    metaTitle: "Retirement Calculator — Are You Saving Enough?",
    metaDescription: "Project your retirement savings in today's money, see the income they could provide with the 4% rule, and find any shortfall to close.",
  },
  {
    ...base,
    slug: "inflation-calculator",
    group: "save",
    name: "Inflation Calculator",
    primaryKeyword: "inflation calculator",
    description: "See what prices will cost in future — and what your money will really be worth.",
    icon: "line-chart",
    keywords: ["inflation calculator", "future value of money", "purchasing power calculator", "cost of living increase"],
    steps: ["Enter an amount and a number of years.", "Set an average inflation rate.", "See future prices and lost purchasing power."],
    about: "Shows how inflation changes the value of money over time: what today's prices will cost in future, and what a future amount is worth in today's money, at an average yearly rate you choose.",
    useCases: ["See what a salary needs to be in 10 years to keep up.", "Plan savings goals in real terms.", "Understand how cash loses value over time."],
    related: ["retirement-calculator", "compound-interest-calculator", "savings-goal-calculator"],
    notes: ["Future and today's value"],
    faqs: [
      { q: "What inflation rate should I use?", a: "Central banks in the US, UK, Canada and Australia target about 2–3% a year, and long-run averages are often around 3%." },
      { q: "Can it show historical inflation?", a: "It uses an average rate you choose. For official historical figures, use your country's statistics office, such as the BLS in the US or the ONS in the UK." },
    ],
    guide: [
      { title: "The rule of 70", body: ["Divide 70 by the inflation rate to estimate how many years it takes prices to double: at 3% a year, about 23 years; at 5%, about 14."] },
    ],
    metaTitle: "Inflation Calculator — Future Prices & Purchasing Power",
    metaDescription: "Calculate how inflation affects prices and purchasing power over time: what things will cost in future and what money will be worth.",
  },
  {
    ...base,
    slug: "roi-calculator",
    group: "save",
    name: "ROI Calculator",
    primaryKeyword: "roi calculator",
    description: "Calculate return on investment, the gain or loss, and the yearly (annualized) return.",
    icon: "chart-column",
    keywords: ["roi calculator", "return on investment calculator", "investment return", "annualized return", "cagr calculator"],
    steps: ["Enter the amount invested and its final value.", "Add the number of years, if you know it.", "See the ROI and the annualized return."],
    about: "Measures how much an investment made or lost as a percentage of what you put in, and — if you give a time period — the equivalent yearly return, so investments held for different lengths of time can be compared fairly.",
    useCases: ["Compare two investments held for different periods.", "Measure a marketing campaign's return.", "Check how a property or shares really performed."],
    related: ["compound-interest-calculator", "rental-yield-calculator", "profit-margin-calculator"],
    notes: ["Annualized return"],
    faqs: [
      { q: "What is annualized return?", a: "The steady yearly rate that would turn your starting amount into the final value. A 35% gain over 3 years is about 10.5% a year." },
      { q: "Does ROI include fees and dividends?", a: "Include them in the final value for an accurate result — subtract fees and add any income you received." },
    ],
    guide: [
      { title: "ROI vs annualized return", body: ["Plain ROI ignores time: 50% over ten years is far worse than 50% over two. The annualized figure puts investments on the same yearly footing so they can be compared."] },
    ],
    metaTitle: "ROI Calculator — Return on Investment & Annual Return",
    metaDescription: "Calculate return on investment (ROI), your gain or loss, and the annualized yearly return, to compare investments held for different times.",
  },
  {
    ...base,
    slug: "simple-interest-calculator",
    group: "save",
    name: "Simple Interest Calculator",
    primaryKeyword: "simple interest calculator",
    description: "Calculate simple interest on any amount, rate and time — and compare it with compound interest.",
    icon: "percent",
    keywords: ["simple interest calculator", "simple interest formula", "interest calculator", "I = PRT"],
    steps: ["Enter the amount and yearly rate.", "Enter the time in years, months or days.", "See the interest and the total."],
    about: "Works out simple interest (interest = principal × rate × time) for any period, and shows how much more you'd get with monthly compounding instead.",
    useCases: ["Check interest on a short-term loan.", "Learn the simple interest formula.", "Compare simple and compound interest."],
    related: ["compound-interest-calculator", "loan-calculator", "calculators/percentage-calculator"],
    notes: ["Formula shown"],
    faqs: [
      { q: "What's the difference from compound interest?", a: "Simple interest is only charged on the original amount. Compound interest is also charged on interest already added, so it grows faster." },
      { q: "Where is simple interest used?", a: "Some short-term loans, car loans in some countries, bonds and many school exercises use it." },
    ],
    guide: [
      { title: "The formula", body: ["Interest = principal × rate × time, with the rate as a decimal and time in years. 5,000 at 5% for 3 years: 5,000 × 0.05 × 3 = 750. Months are divided by 12 and days by 365."] },
    ],
    metaTitle: "Simple Interest Calculator — Formula & Examples",
    metaDescription: "Calculate simple interest on any principal, rate and time in years, months or days, see the total, and compare it with compound interest.",
  },

  /* ——— Shopping & business ——— */
  {
    ...base,
    slug: "discount-calculator",
    group: "business",
    name: "Discount Calculator",
    primaryKeyword: "discount calculator",
    description: "Work out the sale price and savings — including stacked discounts and tax.",
    icon: "tag",
    keywords: ["discount calculator", "percent off calculator", "sale price calculator", "how much is 20% off", "double discount"],
    steps: ["Enter the original price.", "Pick the discount, and any extra discount or tax.", "See the final price and how much you save."],
    about: "Calculates sale prices for any percentage off, handles “an extra 10% off” stacked discounts correctly, and can add sales tax or VAT. A second calculator tells you what percent off a price really is.",
    useCases: ["Check the price of a sale item.", "Understand stacked discounts.", "See what percent off a deal really is."],
    related: ["calculators/percentage-calculator", "vat-calculator", "profit-margin-calculator"],
    notes: ["Stacked discounts"],
    faqs: [
      { q: "Is 20% off then an extra 10% the same as 30% off?", a: "No. The second discount applies to the already-reduced price, so it's 28% off in total." },
      { q: "How do I calculate 25% off?", a: "Multiply the price by 0.75. £80 at 25% off is £60." },
    ],
    guide: [
      { title: "Quick mental math", body: ["10% off: move the decimal one place and subtract. 25% off: take a quarter off. For stacked discounts, multiply the remaining shares — 30% then 20% off leaves 0.7 × 0.8 = 0.56, so you pay 56%."] },
    ],
    metaTitle: "Discount Calculator — Sale Price & Percent Off",
    metaDescription: "Calculate the sale price and savings for any percent off, including stacked extra discounts and tax, or find what percent off a deal really is.",
  },
  {
    ...base,
    slug: "profit-margin-calculator",
    group: "business",
    name: "Profit Margin Calculator",
    primaryKeyword: "profit margin calculator",
    description: "Find margin, markup and profit — or the price you need for a target margin.",
    icon: "chart-pie",
    keywords: ["profit margin calculator", "markup calculator", "margin vs markup", "gross margin calculator", "pricing calculator"],
    steps: ["Enter your cost.", "Add the selling price, target margin or markup.", "See the margin, markup, profit and price."],
    about: "Works out profit margin and markup from cost and price, or the selling price you need for a target margin or markup — and makes the difference between margin and markup clear.",
    useCases: ["Price a product for a target margin.", "Check the margin on a quote.", "Convert between markup and margin."],
    related: ["discount-calculator", "vat-calculator", "roi-calculator"],
    notes: ["Margin and markup"],
    faqs: [
      { q: "What's the difference between margin and markup?", a: "Margin is profit as a share of the price; markup is profit as a share of the cost. A 50% markup is only a 33.3% margin." },
      { q: "How do I price for a 40% margin?", a: "Divide the cost by 0.6 (1 − 0.40). A product costing 30 needs a price of 50." },
    ],
    guide: [
      { title: "Margin to markup and back", body: ["Markup = margin ÷ (1 − margin). Margin = markup ÷ (1 + markup). So a 25% margin needs a 33.3% markup, and a 100% markup gives a 50% margin."] },
    ],
    metaTitle: "Profit Margin Calculator — Margin, Markup & Price",
    metaDescription: "Calculate profit margin and markup from cost and price, or find the selling price for a target margin. Clear margin vs markup explanation.",
  },
  {
    ...base,
    slug: "vat-calculator",
    group: "business",
    name: "VAT & Sales Tax Calculator",
    title: "VAT, GST & Sales Tax Calculator",
    primaryKeyword: "vat calculator",
    description: "Add or remove VAT, GST, HST or sales tax — with UK, Canadian and Australian rates built in.",
    icon: "receipt-text",
    popular: true,
    keywords: ["vat calculator", "gst calculator", "hst calculator", "sales tax calculator", "remove vat", "add vat", "reverse sales tax"],
    steps: ["Choose your country or province (or enter a rate).", "Choose to add or remove tax.", "Enter the price and see the tax breakdown."],
    about: "Adds tax to a price or takes it back out of a total. Rates are built in for UK VAT, Australian and New Zealand GST, and every Canadian province's GST, HST, PST and QST; for US sales tax or anything else, enter your own rate.",
    useCases: ["Find the price before VAT on a receipt.", "Add GST/HST to an invoice.", "Check a total including US sales tax."],
    related: ["discount-calculator", "profit-margin-calculator", "calculators/percentage-calculator"],
    notes: ["Add or remove tax", "UK, CA, AU rates"],
    faqs: [
      { q: "How do I remove 20% VAT from a price?", a: "Divide by 1.2, don't multiply by 0.8. £120 including VAT is £100 before VAT — multiplying by 0.8 would wrongly give £96." },
      { q: "What are Canada's sales tax rates?", a: "GST is 5%. HST is 13% in Ontario, 14% in Nova Scotia and 15% in New Brunswick, Newfoundland and Labrador and PEI. BC and Manitoba add 7% PST, Saskatchewan 6%, and Quebec 9.975% QST." },
      { q: "Why isn't there a US state list?", a: "US sales tax varies by state, county and city, so the right rate depends on the exact address. Enter the combined rate shown on your receipt." },
    ],
    guide: [
      { title: "Rates included", body: ["UK VAT 20% (and 5% reduced rate), Australia GST 10%, New Zealand GST 15%, and every Canadian province — checked for October 2026. Some items are taxed at reduced or zero rates; check with the tax authority for specifics."] },
    ],
    metaTitle: "VAT Calculator — Add or Remove VAT, GST & Sales Tax",
    metaDescription: "Add or remove VAT, GST, HST or sales tax from any price. UK, Australian, NZ and all Canadian province rates built in, or enter your own.",
  },

  /* ——— Tax by country (coming soon: rules change every tax year) ——— */
  { slug: "uk-take-home-pay-calculator", category: "finance", group: "tax", name: "UK Take-Home Pay Calculator", description: "Your salary after Income Tax, National Insurance, pension and student loan.", icon: "wallet", status: "coming-soon", keywords: ["take home pay calculator", "uk salary calculator", "paye calculator", "national insurance"] },
  { slug: "us-paycheck-calculator", category: "finance", group: "tax", name: "US Paycheck Calculator", description: "Your take-home pay after federal, state and FICA taxes.", icon: "wallet", status: "coming-soon", keywords: ["paycheck calculator", "take home pay", "federal tax", "fica"] },
  { slug: "canada-income-tax-calculator", category: "finance", group: "tax", name: "Canada Income Tax Calculator", description: "Federal and provincial income tax, CPP and EI on your salary.", icon: "wallet", status: "coming-soon", keywords: ["canada income tax calculator", "after tax income canada", "cpp", "ei"] },
  { slug: "australia-pay-calculator", category: "finance", group: "tax", name: "Australia Pay Calculator", description: "Take-home pay after income tax and the Medicare levy, plus super.", icon: "wallet", status: "coming-soon", keywords: ["pay calculator australia", "take home pay australia", "medicare levy"] },
  { slug: "uk-stamp-duty-calculator", category: "finance", group: "tax", name: "UK Stamp Duty Calculator", description: "Stamp Duty Land Tax for first-time buyers, home movers and second homes.", icon: "house", status: "coming-soon", keywords: ["stamp duty calculator", "sdlt", "first time buyer stamp duty"] },
  { slug: "australia-stamp-duty-calculator", category: "finance", group: "tax", name: "Australia Stamp Duty Calculator", description: "Stamp duty by state, including first home buyer concessions.", icon: "house", status: "coming-soon", keywords: ["stamp duty calculator nsw", "stamp duty vic", "transfer duty"] },
  { slug: "401k-calculator", category: "finance", group: "tax", name: "401(k) Calculator", description: "Project your 401(k) with employer match and contribution limits.", icon: "palm", status: "coming-soon", keywords: ["401k calculator", "employer match", "retirement usa"] },
  { slug: "rrsp-tfsa-calculator", category: "finance", group: "tax", name: "RRSP vs TFSA Calculator", description: "Compare Canada's RRSP and TFSA for your income and goals.", icon: "palm", status: "coming-soon", keywords: ["rrsp calculator", "tfsa calculator", "rrsp vs tfsa"] },
  { slug: "superannuation-calculator", category: "finance", group: "tax", name: "Superannuation Calculator", description: "Project your Australian super balance at retirement.", icon: "palm", status: "coming-soon", keywords: ["super calculator", "superannuation", "retirement australia"] },
];
