import type { Tool } from "@/lib/catalog/types";

/**
 * Tools added October 2026, chosen from the most-searched everyday tools that can
 * run entirely in the browser. Tools that need a server are "coming-soon".
 */
const added = "2026-10-01";
const updatedAt = "2026-10-01";

export const moreTools: Tool[] = [
  /* ——— PDF ——— */
  {
    slug: "pdf-to-jpg",
    category: "pdf",
    name: "PDF to JPG",
    title: "PDF to JPG Converter",
    primaryKeyword: "pdf to jpg",
    description: "Turn every page of a PDF into a JPG or PNG image — one page or all of them at once.",
    icon: "file-image",
    status: "live",
    popular: true,
    addedAt: added,
    updatedAt,
    keywords: ["pdf to jpg", "pdf to image", "pdf to png", "convert pdf to jpg", "pdf page to image", "save pdf as jpg"],
    steps: ["Drop a PDF onto the page.", "Pick JPG or PNG, the resolution and which pages.", "Download one page, or all of them as a ZIP."],
    about: "Converts PDF pages into ordinary images you can post, paste into slides or send in a chat. Each page is drawn in your browser at the resolution you choose — screen, standard or print quality — and nothing is uploaded.",
    useCases: ["Share one page of a document as a picture.", "Put a PDF page into a presentation or social post.", "Turn a scanned PDF back into separate photos."],
    related: ["images-to-pdf", "split", "image/compressor"],
    notes: ["Up to 300 dpi", "Files never leave your device"],
    faqs: [
      { q: "Which resolution should I choose?", a: "Standard (150 dpi) suits screens and documents. Choose print (300 dpi) for sharp printing or zooming in, and screen (72 dpi) when you need the smallest files." },
      { q: "How do I get all pages at once?", a: "Leave “All pages” selected and press download — the images come in one ZIP file, named by page number." },
      { q: "Can I convert only some pages?", a: "Yes. Choose “Choose pages” and type ranges like 1-3, 5. You can also tap any page preview to download just that page." },
    ],
    guide: [
      { title: "JPG or PNG?", body: ["JPG gives much smaller files and is right for most documents and scanned pages. PNG keeps text edges perfectly crisp and suits diagrams, but files are larger.", "Very large pages are capped at 8,000 pixels on the longest side so your browser doesn't run out of memory."] },
      { title: "Password-protected PDFs", body: ["PDFs that need a password to open can't be read. Open the file in your PDF reader, save a copy without the password, then convert that copy."] },
    ],
    metaTitle: "PDF to JPG Converter — Save PDF Pages as Images",
    metaDescription: "Convert PDF pages to JPG or PNG images at up to 300 dpi. Download one page or all pages as a ZIP. Free, and your PDF is never uploaded.",
  },
  {
    slug: "rotate",
    category: "pdf",
    name: "Rotate PDF",
    primaryKeyword: "rotate pdf",
    description: "Turn PDF pages the right way up — every page at once or one at a time — and save the file.",
    icon: "rotate",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["rotate pdf", "turn pdf pages", "rotate pdf pages", "fix sideways pdf", "rotate pdf and save"],
    steps: ["Drop a PDF onto the page.", "Rotate all pages, or use the arrows on each page.", "Download the rotated PDF."],
    about: "Scanned documents often come out sideways or upside down. This tool shows every page so you can turn just the ones that need it, then saves a new PDF with the rotation stored permanently — it stays correct in every PDF reader.",
    useCases: ["Fix a scan that came out sideways.", "Turn landscape pages in a mixed document.", "Correct upside-down pages before printing or sending."],
    related: ["merge", "split", "page-numbers"],
    notes: ["Rotate single pages", "Files never leave your device"],
    faqs: [
      { q: "Does rotating reduce quality?", a: "No. Rotation is stored as a page setting, so the text and images inside aren't changed or re-compressed." },
      { q: "Will the rotation stay when I open it elsewhere?", a: "Yes. It's saved in the PDF itself, so it shows the same way in Adobe Reader, browsers, phones and printers." },
    ],
    guide: [
      { title: "Left or right?", body: ["Each press turns a page 90°. “Right” turns clockwise, “Left” anticlockwise; two presses turn a page upside down. The preview shows the result before you download."] },
    ],
    metaTitle: "Rotate PDF — Turn PDF Pages and Save, Free",
    metaDescription: "Rotate all pages of a PDF or just the ones that are sideways, then save the file. Rotation is stored permanently. Free, private, no upload.",
  },
  {
    slug: "page-numbers",
    category: "pdf",
    name: "Add Page Numbers",
    title: "Add Page Numbers to PDF",
    primaryKeyword: "add page numbers to pdf",
    description: "Number the pages of a PDF — choose the position, style and starting number.",
    icon: "file-digit",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["add page numbers to pdf", "pdf page numbers", "number pdf pages", "insert page numbers pdf", "page x of y"],
    steps: ["Drop a PDF onto the page.", "Pick the position, format and starting number.", "Download the numbered PDF."],
    about: "Adds page numbers to every page of a PDF in the corner or edge you choose, in styles like “1”, “Page 1 of 10” or “1 / 10”. You can start from any number and leave the cover page unnumbered.",
    useCases: ["Number a report or thesis before submitting it.", "Add “Page X of Y” to contracts and forms.", "Number pages after merging several PDFs."],
    related: ["merge", "watermark", "rotate"],
    notes: ["Skip the cover page", "Files never leave your device"],
    faqs: [
      { q: "Can I start numbering from a number other than 1?", a: "Yes — set “Start at” to any number, for example to continue numbering from another document." },
      { q: "Can the first page stay without a number?", a: "Yes. Turn on “Don't number the first page” and numbering starts on page two." },
      { q: "Which font is used?", a: "Helvetica, the standard PDF font, in dark gray at the size you choose." },
    ],
    guide: [
      { title: "Choosing a position", body: ["Bottom center is the most common choice for documents; bottom right suits reports and anything bound on the left. Increase the distance from the edge if your pages already have a footer, so the number doesn't overlap it."] },
    ],
    metaTitle: "Add Page Numbers to PDF — Free, Choose Position & Style",
    metaDescription: "Add page numbers to a PDF in any corner, as 1, Page 1 of N or 1 / N. Choose the start number and skip the cover page. Free and private.",
  },
  {
    slug: "watermark",
    category: "pdf",
    name: "Watermark PDF",
    primaryKeyword: "watermark pdf",
    description: "Stamp text like CONFIDENTIAL or DRAFT across your PDF pages — once or repeated.",
    icon: "stamp",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["watermark pdf", "add watermark to pdf", "pdf watermark", "confidential stamp pdf", "draft watermark"],
    steps: ["Drop a PDF onto the page.", "Type the watermark and adjust size, angle, color and opacity.", "Download the watermarked PDF."],
    about: "Adds a text watermark to the pages of a PDF: once in the center, or repeated across the whole page. Adjust the size, angle, color and transparency, and choose which pages get it.",
    useCases: ["Mark a document as CONFIDENTIAL or DRAFT.", "Add your name or company to a file you share.", "Discourage copying of a sample or preview."],
    related: ["sign", "page-numbers", "merge"],
    notes: ["Centered or repeated", "Files never leave your device"],
    faqs: [
      { q: "Can a watermark be removed?", a: "A text watermark is part of the page content, which makes casual copying harder — but anyone with PDF editing software can remove it. It isn't a security measure." },
      { q: "Which characters can I use?", a: "Latin letters, numbers, accents and common symbols. Other alphabets aren't included in the standard PDF font, and the tool will tell you if something can't be used." },
    ],
    guide: [
      { title: "Getting the look right", body: ["A light watermark (15–25% opacity) at 45° keeps the document readable. The preview is approximate; the downloaded file uses the exact settings you chose."] },
    ],
    metaTitle: "Watermark PDF — Add a Text Watermark Online, Free",
    metaDescription: "Add a text watermark like CONFIDENTIAL or DRAFT to a PDF. Choose size, angle, color, opacity and pages, centered or repeated. Free, no upload.",
  },
  {
    slug: "sign",
    category: "pdf",
    name: "Sign PDF",
    primaryKeyword: "sign pdf",
    description: "Draw or type your signature and place it on any page of a PDF.",
    icon: "signature",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["sign pdf", "sign pdf online", "add signature to pdf", "electronic signature", "e-sign pdf", "fill and sign"],
    steps: ["Drop the PDF you need to sign.", "Draw your signature or type your name.", "Place it on the page and download the signed PDF."],
    about: "Add your handwritten-style signature to a PDF without printing and scanning. Draw it with a mouse, finger or pen — or type your name — then drag it into place on any page and resize it.",
    useCases: ["Sign a rental agreement, form or permission slip.", "Return a signed offer letter by email.", "Sign invoices and delivery notes on your phone."],
    related: ["watermark", "merge", "pdf-to-jpg"],
    notes: ["Draw or type", "Files never leave your device"],
    faqs: [
      { q: "Is this a legally valid signature?", a: "It adds an image of your signature, which many people and organizations accept for everyday documents. It isn't a certificate-based digital signature; for contracts that require one, use a dedicated e-signature service." },
      { q: "Is my signature saved?", a: "No. It exists only in this browser tab while you work and is gone when you close it." },
    ],
    guide: [
      { title: "Tips for a clean signature", body: ["Draw slowly and larger than you need — it's scaled down when placed. On a phone, turning it sideways gives you more room to sign."] },
    ],
    metaTitle: "Sign PDF Online — Draw or Type Your Signature, Free",
    metaDescription: "Sign a PDF online for free: draw or type your signature, place it on any page and download the signed file. Nothing is uploaded or stored.",
  },
  { slug: "pdf-to-word", category: "pdf", name: "PDF to Word", description: "Convert a PDF into an editable Word document.", icon: "file-type", status: "coming-soon", keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "editable pdf"] },
  { slug: "word-to-pdf", category: "pdf", name: "Word to PDF", description: "Turn a Word document into a PDF that looks the same everywhere.", icon: "file-type", status: "coming-soon", keywords: ["word to pdf", "docx to pdf", "convert word to pdf"] },

  /* ——— Image ——— */
  {
    slug: "heic-to-jpg",
    category: "image",
    name: "HEIC to JPG",
    title: "HEIC to JPG Converter",
    primaryKeyword: "heic to jpg",
    description: "Convert iPhone HEIC photos to JPG so they open anywhere — many at once.",
    icon: "smartphone",
    status: "live",
    popular: true,
    addedAt: added,
    updatedAt,
    keywords: ["heic to jpg", "heic to jpeg", "convert heic", "iphone photo to jpg", "heif to jpg", "open heic"],
    steps: ["Drop your HEIC photos onto the page.", "Adjust the JPG quality if you like.", "Download one JPG or a ZIP of all of them."],
    about: "iPhones and iPads save photos as HEIC, which many websites, Windows apps and forms don't accept. This tool converts them to standard JPG in your browser — your photos are never uploaded.",
    useCases: ["Upload iPhone photos to a site that only takes JPG.", "Open iPhone pictures on a Windows PC.", "Send photos to someone whose phone can't open HEIC."],
    related: ["png-to-jpg", "compressor", "resizer"],
    notes: ["Batch conversion", "Photos never leave your device"],
    faqs: [
      { q: "Is HEIC better than JPG?", a: "HEIC files are about half the size of a JPG at similar quality, but they aren't supported everywhere. JPG works in practically every app and website." },
      { q: "Why does conversion take a few seconds?", a: "HEIC is decoded in your browser rather than on a server. It takes a moment per photo, but your pictures stay private." },
      { q: "How do I stop my iPhone saving HEIC?", a: "In Settings → Camera → Formats, choose “Most Compatible”. New photos will then be saved as JPG." },
    ],
    guide: [
      { title: "What you keep and lose", body: ["The picture itself converts at the quality you choose; 90% is visually identical for photos. Live Photo motion and HEIC burst sequences are not kept — you get the main still image."] },
    ],
    metaTitle: "HEIC to JPG Converter — Convert iPhone Photos, Free",
    metaDescription: "Convert HEIC photos from iPhone or iPad to JPG in your browser. Many photos at once, downloaded as a ZIP. Free, and photos are never uploaded.",
  },
  {
    slug: "png-to-jpg",
    category: "image",
    name: "PNG to JPG",
    title: "PNG to JPG Converter",
    primaryKeyword: "png to jpg",
    description: "Convert PNG images to smaller JPG files — one or many at once.",
    icon: "convert",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg", "png converter"],
    steps: ["Drop your PNG files onto the page.", "Set the JPG quality.", "Download one JPG or a ZIP of all of them."],
    about: "Turns PNG images into JPG, which is usually much smaller for photos and screenshots with lots of colors. Convert a whole batch at once in your browser.",
    useCases: ["Shrink screenshots before emailing them.", "Meet an upload form that only accepts JPG.", "Make photo files smaller for a website."],
    related: ["jpg-to-png", "webp-to-jpg", "compressor"],
    notes: ["Batch conversion", "Images never leave your device"],
    faqs: [
      { q: "What happens to transparency?", a: "JPG can't store transparency, so transparent areas become white." },
      { q: "Will the JPG be smaller?", a: "For photos and colorful screenshots, usually much smaller. Simple graphics with flat colors can sometimes be smaller as PNG." },
    ],
    guide: [
      { title: "When to keep PNG instead", body: ["Logos, icons and screenshots of text with large flat areas often look sharper — and can even be smaller — as PNG. Convert photos and busy, colorful images to JPG; keep simple graphics as PNG."] },
      { title: "Batches", body: ["Drop as many files as you need. Each one is converted in turn, and two or more download together as a ZIP named converted-jpg.zip."] },
    ],
    metaTitle: "PNG to JPG Converter — Convert Many Images Free",
    metaDescription: "Convert PNG to JPG in your browser, many files at once, with adjustable quality. Transparent areas become white. Free, no upload.",
  },
  {
    slug: "webp-to-jpg",
    category: "image",
    name: "WebP to JPG",
    title: "WebP to JPG Converter",
    primaryKeyword: "webp to jpg",
    description: "Convert WebP images saved from websites into JPG files that open anywhere.",
    icon: "convert",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["webp to jpg", "webp to jpeg", "convert webp", "open webp", "webp converter"],
    steps: ["Drop your WebP files onto the page.", "Set the JPG quality.", "Download one JPG or a ZIP of all of them."],
    about: "Images saved from websites are often WebP, which some photo apps, editors and upload forms can't open. Convert them to JPG in seconds, in your browser.",
    useCases: ["Open an image saved from a website in an older editor.", "Upload a WebP picture to a site that only takes JPG.", "Convert a folder of WebP downloads at once."],
    related: ["png-to-jpg", "converter", "jpg-to-png"],
    notes: ["Batch conversion", "Images never leave your device"],
    faqs: [
      { q: "Why are so many images WebP now?", a: "WebP files are smaller than JPG or PNG at similar quality, so websites use them to load faster." },
      { q: "What about animated WebP?", a: "The first frame is converted to a still JPG." },
    ],
    guide: [
      { title: "Saving images as JPG in the first place", body: ["Many browsers show WebP images even when you save them. Converting here is the reliable fix: drop the saved .webp files and download JPGs. Transparent areas become white, since JPG has no transparency."] },
    ],
    metaTitle: "WebP to JPG Converter — Free, Batch, No Upload",
    metaDescription: "Convert WebP images to JPG in your browser, one or many at once, with adjustable quality. Your images are never uploaded. Free and private.",
  },
  {
    slug: "jpg-to-png",
    category: "image",
    name: "JPG to PNG",
    title: "JPG to PNG Converter",
    primaryKeyword: "jpg to png",
    description: "Convert JPG photos to PNG — one or many at once.",
    icon: "convert",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png"],
    steps: ["Drop your JPG files onto the page.", "Convert them.", "Download one PNG or a ZIP of all of them."],
    about: "Saves JPG images as PNG, a lossless format that some design tools, print services and upload forms prefer. Converting keeps every pixel of the JPG exactly as it is.",
    useCases: ["Get a PNG for a tool that requires it.", "Keep an image from losing quality with repeated edits.", "Prepare images for a design app."],
    related: ["png-to-jpg", "converter", "compressor"],
    notes: ["Lossless output", "Images never leave your device"],
    faqs: [
      { q: "Does converting to PNG improve quality?", a: "No — it keeps the image exactly as it is, but can't restore detail the JPG already lost. Its benefit is that further edits won't lose more." },
      { q: "Does it make the background transparent?", a: "No. A JPG has no transparency, so the PNG has the same solid background." },
    ],
    guide: [
      { title: "Expect bigger files", body: ["PNG compresses without losing anything, so a PNG of a photo is often 3–10 times larger than the JPG. If file size matters more than lossless editing, keep the JPG or use the image compressor."] },
    ],
    metaTitle: "JPG to PNG Converter — Convert Images Free",
    metaDescription: "Convert JPG or JPEG images to lossless PNG in your browser, one or many at once. Every pixel is kept as it is. Free, and nothing is uploaded.",
  },
  { slug: "image-to-text", category: "image", name: "Image to Text (OCR)", description: "Copy the text out of a photo, screenshot or scanned page.", icon: "scan-text", status: "coming-soon", keywords: ["image to text", "ocr", "extract text from image", "photo to text"] },

  /* ——— Calculators ——— */
  {
    slug: "bmi-calculator",
    category: "calculators",
    name: "BMI Calculator",
    primaryKeyword: "bmi calculator",
    description: "Work out your body mass index in metric or US units, with the healthy weight range for your height.",
    icon: "scale",
    status: "live",
    popular: true,
    addedAt: added,
    updatedAt,
    keywords: ["bmi calculator", "body mass index", "bmi chart", "healthy weight", "bmi kg cm", "bmi lbs"],
    steps: ["Choose metric or US units.", "Enter your height and weight.", "See your BMI, its category and your healthy weight range."],
    about: "BMI (body mass index) compares weight with height to give a quick screening number for adults. This calculator shows your BMI, the standard category it falls in, and the weight range that counts as healthy for your height.",
    useCases: ["Check where you are on the BMI scale.", "Find a healthy target weight for your height.", "Convert between kg, cm, pounds and feet."],
    related: ["calorie-calculator", "age-calculator", "percentage-calculator"],
    notes: ["Metric and US units", "Healthy weight range"],
    faqs: [
      { q: "What is a healthy BMI?", a: "For adults, 18.5 to 24.9. Below 18.5 is underweight, 25 to 29.9 overweight, and 30 or more is in the obesity range." },
      { q: "Is BMI accurate for everyone?", a: "No. It doesn't separate muscle from fat, so very muscular people can score high. It's not used the same way for children and teenagers, and some health bodies use lower cut-offs for people of Asian descent." },
    ],
    guide: [
      { title: "How BMI is calculated", body: ["BMI is weight in kilograms divided by height in meters squared. For 70 kg and 1.75 m: 70 ÷ (1.75 × 1.75) = 22.9. US units are converted to metric first."] },
    ],
    metaTitle: "BMI Calculator — Body Mass Index in kg or lbs",
    metaDescription: "Calculate your BMI in metric or US units and see your category and the healthy weight range for your height. Free, instant and private.",
  },
  {
    slug: "loan-calculator",
    category: "calculators",
    name: "Loan Calculator",
    title: "Loan & EMI Calculator",
    primaryKeyword: "loan calculator",
    description: "Find your monthly loan payment (EMI), the total interest and a year-by-year breakdown.",
    icon: "bank",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["loan calculator", "emi calculator", "monthly payment calculator", "personal loan calculator", "car loan calculator", "interest calculator"],
    steps: ["Enter the loan amount and yearly interest rate.", "Enter the term in years or months.", "See the monthly payment, total interest and schedule."],
    about: "Works out the fixed monthly payment for a loan — often called EMI (equated monthly installment) — along with the total interest you'll pay and how the balance falls year by year. It suits personal, car and student loans with a fixed rate.",
    useCases: ["Compare loan offers with different rates or terms.", "See how much a car loan really costs.", "Check whether a monthly payment fits your budget."],
    related: ["mortgage-calculator", "compound-interest-calculator", "percentage-calculator"],
    notes: ["Yearly breakdown", "Any currency"],
    faqs: [
      { q: "What is EMI?", a: "Equated monthly installment — the same payment every month that covers both interest and part of the loan, so it's fully repaid by the end of the term." },
      { q: "Why is so much of the early payment interest?", a: "Interest is charged on the remaining balance, which is largest at the start. As the balance falls, more of each payment goes to the loan itself." },
    ],
    guide: [
      { title: "The formula", body: ["EMI = P × r × (1 + r)ⁿ ÷ ((1 + r)ⁿ − 1), where P is the loan amount, r the monthly interest rate (yearly rate ÷ 12) and n the number of monthly payments."] },
      { title: "Shorter or longer term?", body: ["A longer term lowers the monthly payment but raises the total interest. Try both in the calculator to see the difference before you decide."] },
    ],
    metaTitle: "Loan Calculator — Monthly Payment (EMI) & Interest",
    metaDescription: "Calculate the monthly payment (EMI) on any loan, the total interest and a yearly breakdown. Works for personal, car and student loans.",
  },
  {
    slug: "mortgage-calculator",
    category: "calculators",
    name: "Mortgage Calculator",
    primaryKeyword: "mortgage calculator",
    description: "Estimate your monthly mortgage payment with taxes, insurance and HOA fees.",
    icon: "house",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["mortgage calculator", "home loan calculator", "house payment calculator", "mortgage payment", "monthly mortgage"],
    steps: ["Enter the home price and down payment.", "Add the rate, term, and optional taxes and insurance.", "See the monthly payment and total interest."],
    about: "Estimates the monthly cost of a home: the loan payment itself (principal and interest) plus property tax, home insurance and HOA fees. It also shows the loan amount, total interest over the term and a yearly breakdown.",
    useCases: ["See what price range fits your budget.", "Compare a 15-year and 30-year mortgage.", "Check how a bigger down payment changes the payment."],
    related: ["loan-calculator", "compound-interest-calculator", "percentage-calculator"],
    notes: ["Taxes and insurance", "15, 20 or 30 years"],
    faqs: [
      { q: "What does the monthly payment include?", a: "Principal and interest, plus the yearly property tax and insurance divided by 12 and any monthly HOA fee you enter. It doesn't include mortgage insurance (PMI) or closing costs." },
      { q: "How much should I put down?", a: "Many lenders accept less, but a 20% down payment usually avoids private mortgage insurance and lowers the monthly payment." },
    ],
    guide: [
      { title: "15 vs 30 years", body: ["A 15-year mortgage has higher monthly payments but far less total interest. Enter both terms to see the trade-off for your numbers."] },
    ],
    metaTitle: "Mortgage Calculator — Monthly Payment with Tax & Insurance",
    metaDescription: "Estimate your monthly mortgage payment including property tax, insurance and HOA, plus the total interest and a yearly breakdown. Free.",
  },
  {
    slug: "compound-interest-calculator",
    category: "calculators",
    name: "Compound Interest Calculator",
    primaryKeyword: "compound interest calculator",
    description: "See how savings grow with compound interest and regular monthly contributions.",
    icon: "piggy",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["compound interest calculator", "savings calculator", "investment calculator", "interest calculator", "compound growth"],
    steps: ["Enter a starting amount and monthly contribution.", "Enter the yearly interest rate and number of years.", "See the final balance and how much is interest."],
    about: "Shows how money grows when interest earns interest. Add a starting amount, a regular monthly contribution, a yearly rate and how often it compounds, and see the final balance, what you put in and what you earned — year by year.",
    useCases: ["Plan how much to save each month for a goal.", "See the effect of starting to invest earlier.", "Compare compounding monthly versus yearly."],
    related: ["loan-calculator", "mortgage-calculator", "percentage-calculator"],
    notes: ["Monthly contributions", "Yearly growth chart"],
    faqs: [
      { q: "What is compound interest?", a: "Interest that's added to your balance, so the next period's interest is calculated on a bigger amount. Over long periods, this snowball effect does most of the growth." },
      { q: "Does compounding more often make a big difference?", a: "A little. At 7% a year, monthly compounding gives an effective yearly rate of about 7.23%. Time and the rate matter far more." },
    ],
    guide: [
      { title: "The rule of 72", body: ["Divide 72 by the yearly rate to estimate how many years it takes money to double: at 6%, about 12 years; at 9%, about 8."] },
    ],
    metaTitle: "Compound Interest Calculator — With Monthly Contributions",
    metaDescription: "Calculate compound interest with monthly contributions. See your final balance, total contributions and interest earned, year by year.",
  },
  {
    slug: "gpa-calculator",
    category: "calculators",
    name: "GPA Calculator",
    primaryKeyword: "gpa calculator",
    description: "Calculate your semester and cumulative GPA from letter grades and credits.",
    icon: "graduation",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["gpa calculator", "college gpa calculator", "cumulative gpa", "grade point average", "semester gpa"],
    steps: ["Add each course with its letter grade and credits.", "Optionally enter your current GPA and credits.", "See your semester and new cumulative GPA."],
    about: "Works out your grade point average on the common US 4.0 scale. Enter each course's letter grade and credit hours to get your GPA for the term, and add your existing GPA to see the new cumulative figure.",
    useCases: ["Check your GPA before transcripts come out.", "See what grades you need to raise your average.", "Work out a cumulative GPA for applications."],
    related: ["percentage-calculator", "age-calculator"],
    notes: ["Cumulative GPA", "4.0 scale"],
    faqs: [
      { q: "How is GPA calculated?", a: "Each grade is turned into points (A = 4.0, B = 3.0 …), multiplied by the course's credits, added up and divided by the total credits." },
      { q: "Is A+ worth 4.3?", a: "At some schools, yes. This calculator uses the more common 4.0 cap — check your school's scale." },
    ],
    guide: [
      { title: "Grade points used", body: ["A+ and A = 4.0, A− = 3.7, B+ = 3.3, B = 3.0, B− = 2.7, C+ = 2.3, C = 2.0, C− = 1.7, D+ = 1.3, D = 1.0, D− = 0.7, F = 0. Courses with zero credits (or pass/fail courses you leave out) don't affect the result."] },
      { title: "Raising your GPA", body: ["Courses with more credits move your GPA more. Add a planned course with the grade you're aiming for to see what your cumulative GPA would become."] },
    ],
    metaTitle: "GPA Calculator — Semester & Cumulative GPA (4.0 Scale)",
    metaDescription: "Calculate your GPA from letter grades and credit hours on the 4.0 scale, and your new cumulative GPA. Add as many courses as you need.",
  },
  {
    slug: "tip-calculator",
    category: "calculators",
    name: "Tip Calculator",
    primaryKeyword: "tip calculator",
    description: "Work out the tip and split the bill between any number of people.",
    icon: "receipt",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["tip calculator", "split bill", "gratuity calculator", "how much to tip", "bill splitter"],
    steps: ["Enter the bill amount.", "Pick a tip percentage.", "Split it between people and round up if you like."],
    about: "Calculates the tip on a bill and how much each person pays when you split it. Choose a common percentage with one tap, and round each share up to a whole amount to make paying easier.",
    useCases: ["Split a restaurant bill with friends.", "Check the tip for a taxi or delivery.", "Round shares so everyone pays an even amount."],
    related: ["percentage-calculator", "loan-calculator"],
    notes: ["Split the bill", "Round up"],
    faqs: [
      { q: "How much should I tip?", a: "Customs vary by country. In the US, 15–20% is usual at restaurants; in many other countries service is included or a small round-up is enough." },
      { q: "Is the tip on the amount before or after tax?", a: "Many people tip on the pre-tax amount. Enter whichever amount you want the percentage to apply to." },
    ],
    guide: [
      { title: "Rounding up", body: ["With rounding on, each person's share is rounded up to the next whole amount and the tip is recalculated from the new total, so you can see the actual percentage everyone ends up tipping."] },
    ],
    metaTitle: "Tip Calculator — Work Out the Tip & Split the Bill",
    metaDescription: "Calculate the tip and split the bill between any number of people. Quick 10–25% buttons and an option to round each share up. Free.",
  },
  {
    slug: "calorie-calculator",
    category: "calculators",
    name: "Calorie Calculator",
    primaryKeyword: "calorie calculator",
    description: "Estimate how many calories you need each day to maintain, lose or gain weight.",
    icon: "flame",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["calorie calculator", "tdee calculator", "bmr calculator", "daily calories", "maintenance calories", "calorie deficit"],
    steps: ["Enter your sex, age, height and weight.", "Choose your activity level.", "See your daily calories to maintain, lose or gain."],
    about: "Estimates your daily energy needs using the Mifflin–St Jeor equation: your basal metabolic rate (BMR) multiplied by your activity level gives the calories to maintain your weight (TDEE), plus targets for gentle weight loss or gain.",
    useCases: ["Find your maintenance calories.", "Set a sensible target for losing weight.", "Plan meals for gaining muscle."],
    related: ["bmi-calculator", "age-calculator"],
    notes: ["BMR and TDEE", "Metric and US units"],
    faqs: [
      { q: "What's the difference between BMR and TDEE?", a: "BMR is what your body burns at complete rest. TDEE (total daily energy expenditure) adds everything you do in a day, so it's the number to eat to keep your weight steady." },
      { q: "How accurate is it?", a: "The Mifflin–St Jeor equation is one of the most reliable estimates for adults, but individuals can differ by 10% or more. Track your weight for a few weeks and adjust." },
    ],
    guide: [
      { title: "A sensible deficit", body: ["Eating about 500 calories a day below maintenance leads to roughly 0.5 kg (1 lb) of weight loss a week. The tool never suggests going below 1,200 (women) or 1,500 (men) calories a day."] },
    ],
    metaTitle: "Calorie Calculator — Daily Calories, BMR & TDEE",
    metaDescription: "Estimate your daily calories to maintain, lose or gain weight from your age, height, weight and activity, using Mifflin–St Jeor.",
  },
  {
    slug: "days-between-dates",
    category: "calculators",
    name: "Days Between Dates",
    title: "Days Between Dates Calculator",
    primaryKeyword: "days between dates",
    description: "Count the days, weeks and weekdays between two dates.",
    icon: "calendar-range",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["days between dates", "date calculator", "how many days until", "date difference", "count days", "business days"],
    steps: ["Pick a start date (today by default).", "Pick an end date.", "See the days, weeks, months and weekdays between them."],
    about: "Counts the time between two dates in days, weeks and days, years-months-days and weekdays (Monday to Friday). Choose whether to include the end date, or jump ahead 30, 90 or 365 days.",
    useCases: ["Count down the days to a trip or event.", "Work out a notice period or deadline.", "Count working days for a project."],
    related: ["age-calculator", "developer/timestamp-converter", "productivity/countdown-timer"],
    notes: ["Weekdays count", "Include end date"],
    faqs: [
      { q: "Should I include the end date?", a: "Include it when both the first and last day count, like the days of a holiday or a hotel stay. Leave it off for “how many days until” questions." },
      { q: "Are public holidays excluded from weekdays?", a: "No — holidays differ by country and region, so only weekends are removed." },
    ],
    guide: [
      { title: "How the count works", body: ["Without the end date, the count is the number of midnights between the two dates — from Monday to Friday is 4 days. Including the end date adds one, which is how you'd count the days of a trip.", "Dates are compared as calendar days, so daylight saving changes don't add or remove an hour from the result."] },
    ],
    metaTitle: "Days Between Dates — Count Days, Weeks & Weekdays",
    metaDescription: "Count the days between two dates, with weeks, years-months-days and weekdays (Mon–Fri). Option to include the end date. Free and instant.",
  },

  /* ——— Productivity ——— */
  {
    slug: "stopwatch",
    category: "productivity",
    name: "Online Stopwatch",
    primaryKeyword: "online stopwatch",
    description: "A precise stopwatch with lap times, right in your browser.",
    icon: "timer",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["online stopwatch", "stopwatch", "lap timer", "stop watch", "timer with laps"],
    steps: ["Press Start (or the space bar).", "Press Lap to record split times.", "Stop, resume or reset whenever you like."],
    about: "A full-screen stopwatch accurate to the hundredth of a second, with lap times that highlight your fastest and slowest splits. Keyboard shortcuts make it quick to use on a computer.",
    useCases: ["Time laps, sprints and workouts.", "Time a presentation or speech.", "Measure how long a task really takes."],
    related: ["countdown-timer", "typing-test", "calculators/days-between-dates"],
    notes: ["Lap times", "Keyboard shortcuts"],
    faqs: [
      { q: "Does it keep running if I switch tabs?", a: "Yes. Time is measured from the clock, not counted tick by tick, so it stays accurate even if the tab is in the background." },
      { q: "What are the keyboard shortcuts?", a: "Space starts and stops, L records a lap and R resets when stopped." },
    ],
    guide: [
      { title: "Reading lap times", body: ["Each lap shows its own split time and the total time when it was recorded. With two or more laps, the fastest split is shown in green and the slowest in red."] },
    ],
    metaTitle: "Online Stopwatch — With Lap Times, Free",
    metaDescription: "A free online stopwatch accurate to 1/100 second, with lap and split times and keyboard shortcuts. No download or sign-up needed.",
  },
  {
    slug: "countdown-timer",
    category: "productivity",
    name: "Countdown Timer",
    title: "Online Countdown Timer",
    primaryKeyword: "online timer",
    description: "Set a timer for any length and get an alarm when time is up.",
    icon: "alarm",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["online timer", "countdown timer", "set a timer", "5 minute timer", "10 minute timer", "timer with alarm"],
    steps: ["Set hours, minutes and seconds, or tap a quick start.", "Press Start.", "An alarm sounds and the page changes when time is up."],
    about: "A simple countdown timer with an alarm. Pick a quick preset like 5, 10 or 25 minutes or set any time up to 99 hours; pause and resume as needed. The time left also shows in the browser tab title.",
    useCases: ["Time cooking, study sessions or breaks.", "Run a 25-minute focus session.", "Keep a meeting or exam to time."],
    related: ["stopwatch", "spin-the-wheel", "calculators/days-between-dates"],
    notes: ["Alarm sound", "Shows in tab title"],
    faqs: [
      { q: "Will the alarm play if the tab is in the background?", a: "Yes, as long as the tab stays open and your device isn't muted. The alarm is enabled when you press Start." },
      { q: "Is it accurate in the background?", a: "Yes. The timer counts down to a fixed end time, so it stays accurate even when your browser slows background tabs." },
    ],
    guide: [
      { title: "Popular uses", body: ["25 minutes is the classic Pomodoro focus session followed by a 5-minute break. Short timers of 1–3 minutes suit tooth brushing, tea, presentations and exam questions."] },
      { title: "If you don't hear the alarm", body: ["Check that your device isn't muted and the tab is still open. Browsers only allow sound after you interact with the page, which is why the alarm is armed when you press Start."] },
    ],
    metaTitle: "Online Timer — Free Countdown Timer with Alarm",
    metaDescription: "A free online countdown timer with an alarm. Quick 1–60 minute presets, any custom time, pause and resume, and the time left in your tab title.",
  },
  {
    slug: "spin-the-wheel",
    category: "productivity",
    name: "Spin the Wheel",
    title: "Spin the Wheel — Random Picker",
    primaryKeyword: "spin the wheel",
    description: "Put names or options on a wheel and spin it to pick one at random.",
    icon: "pinwheel",
    status: "live",
    popular: true,
    addedAt: added,
    updatedAt,
    keywords: ["spin the wheel", "wheel spinner", "wheel of names", "random wheel", "decision wheel", "prize wheel"],
    steps: ["Type your entries, one per line.", "Press Spin the wheel.", "See the winner — and remove it for the next spin if you like."],
    about: "A colorful wheel spinner for classrooms, giveaways and quick decisions. Add up to 100 entries, spin, and the wheel lands on a winner chosen fairly with a secure random generator.",
    useCases: ["Pick a student or a giveaway winner.", "Decide what to eat or watch.", "Choose turns or teams in a game."],
    related: ["list-randomizer", "random-number-generator", "countdown-timer"],
    notes: ["Up to 100 entries", "Fair and random"],
    faqs: [
      { q: "Is the wheel fair?", a: "Yes. The winner is chosen with your browser's cryptographically secure random generator before the wheel stops, so every entry has exactly the same chance." },
      { q: "Can I remove the winner after each spin?", a: "Yes — tap “Remove from the wheel”, or turn on automatic removal for draws with several prizes." },
    ],
    guide: [
      { title: "Running a giveaway", body: ["Paste the entrant list, remove duplicates first with the duplicate line remover if people entered twice, and spin once per prize with automatic removal turned on. Screen-record the spin if you want proof of a fair draw."] },
    ],
    metaTitle: "Spin the Wheel — Random Name Picker Wheel, Free",
    metaDescription: "Spin a wheel to pick a random name or option. Add up to 100 entries, remove winners as you go. Fair, secure randomness. Free, no sign-up.",
  },
  {
    slug: "typing-test",
    category: "productivity",
    name: "Typing Speed Test",
    primaryKeyword: "typing speed test",
    description: "Find your typing speed in words per minute, with accuracy.",
    icon: "keyboard",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["typing speed test", "typing test", "wpm test", "words per minute", "typing practice", "check typing speed"],
    steps: ["Choose 30 seconds, 1 minute or 2 minutes.", "Start typing the text — the timer starts with your first key.", "See your words per minute and accuracy."],
    about: "A quick typing test that measures your speed in words per minute (WPM) and your accuracy. Mistakes are highlighted as you type, and you can retry the same text or practice with a new one.",
    useCases: ["Check your typing speed for a job application.", "Practice a little each day and track progress.", "Challenge friends or classmates."],
    related: ["stopwatch", "text/word-counter"],
    notes: ["WPM and accuracy", "30s, 1 min or 2 min"],
    faqs: [
      { q: "How is WPM calculated?", a: "Correctly typed characters are divided by five (the standard length of a “word”) and then by the minutes spent. Mistakes don't count toward your speed." },
      { q: "What's a good typing speed?", a: "Around 40 WPM is typical. 60+ WPM is fast, and professional typists often reach 80 or more." },
    ],
    guide: [
      { title: "How to improve", body: ["Accuracy first: aim for 95% or higher, then speed up. Keep your fingers on the home row (ASDF and JKL;), look at the screen rather than the keyboard, and practice for a few minutes every day rather than once a week."] },
      { title: "Fair results", body: ["Pasting is turned off, the timer starts on your first keystroke, and only correctly typed characters count toward your speed."] },
    ],
    metaTitle: "Typing Speed Test — Check Your WPM & Accuracy",
    metaDescription: "Take a free typing speed test. Measure your words per minute and accuracy in 30 seconds, 1 minute or 2 minutes, with mistakes highlighted.",
  },
  {
    slug: "unit-converter",
    category: "productivity",
    name: "Unit Converter",
    primaryKeyword: "unit converter",
    description: "Convert length, weight, temperature, volume, area, speed, time and data units.",
    icon: "ruler",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["unit converter", "cm to inches", "kg to lbs", "celsius to fahrenheit", "measurement converter", "metric converter"],
    steps: ["Pick what you're converting.", "Enter a value and choose the units.", "See the result and every other unit at once."],
    about: "One converter for everyday units: length, weight, temperature, volume, area, speed, time and digital data. Type a value to see it in your chosen unit and in every other unit of the same kind.",
    useCases: ["Convert a recipe between cups and milliliters.", "Turn kilograms into pounds or centimeters into inches.", "Check how many GiB a GB really is."],
    related: ["time-zone-converter", "calculators/percentage-calculator", "color/color-converter"],
    notes: ["8 kinds of units", "Exact factors"],
    faqs: [
      { q: "Are the conversions exact?", a: "Yes. They use the official definitions — for example, 1 inch is exactly 2.54 cm and 1 pound is exactly 0.45359237 kg." },
      { q: "Why are there two kinds of gallon?", a: "The US gallon (3.785 liters) and the UK imperial gallon (4.546 liters) are different units. Cups, pints and quarts here are US measures." },
    ],
    guide: [
      { title: "KB vs KiB", body: ["Storage makers use decimal units (1 GB = 1,000,000,000 bytes), while many operating systems report binary units (1 GiB = 1,073,741,824 bytes). That's why a “500 GB” drive shows about 465 GB on a computer."] },
      { title: "Temperature", body: ["Temperature isn't a simple multiplication: °F = °C × 9/5 + 32 and K = °C + 273.15. The converter handles the offsets for you."] },
    ],
    metaTitle: "Unit Converter — Length, Weight, Temperature & More",
    metaDescription: "Convert length, weight, temperature, volume, area, speed, time and data units instantly, with every unit shown at once. Free.",
  },
  {
    slug: "time-zone-converter",
    category: "productivity",
    name: "Time Zone Converter",
    primaryKeyword: "time zone converter",
    description: "See what time it is in other cities — for now or any date and time you pick.",
    icon: "globe",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["time zone converter", "time difference", "world clock", "meeting planner", "est to ist", "pst to gmt"],
    steps: ["Pick your time zone, date and time (now by default).", "Add the cities you care about.", "See the same moment in each place."],
    about: "Converts a time in one time zone into the matching time in other cities, with daylight saving time handled automatically. Use it for now, or pick any date and time to plan a call across countries.",
    useCases: ["Schedule a meeting with people in other countries.", "Check when a live event starts where you are.", "See if it's a sensible hour to call someone."],
    related: ["unit-converter", "developer/timestamp-converter", "calculators/days-between-dates"],
    notes: ["Daylight saving aware", "Any date and time"],
    faqs: [
      { q: "Does it handle daylight saving time?", a: "Yes. Each zone's offset is worked out for the exact date you pick, using your browser's built-in time zone database." },
      { q: "What do “next day” and “previous day” mean?", a: "The converted time falls on a different calendar date than the one you entered — common when converting between Asia and the Americas." },
    ],
    guide: [
      { title: "Planning a meeting", body: ["Set the time in your own time zone, then add each participant's city. Aim for a time that falls between about 8 am and 6 pm for everyone; the “next day” and “previous day” labels warn you when it crosses midnight somewhere."] },
      { title: "Cities, not abbreviations", body: ["Abbreviations like EST or IST are ambiguous and don't change with daylight saving. Choosing a city always gives the correct local time for the date you pick."] },
    ],
    metaTitle: "Time Zone Converter — Compare Times Across Cities",
    metaDescription: "Convert any date and time between time zones and cities, with daylight saving handled for you. Plan meetings across countries. Free.",
  },

  /* ——— Text ——— */
  {
    slug: "text-to-speech",
    category: "text",
    name: "Text to Speech",
    primaryKeyword: "text to speech",
    description: "Have any text read aloud with the voices built into your device.",
    icon: "volume",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["text to speech", "read text aloud", "tts", "text reader", "speak text", "voice reader"],
    steps: ["Paste or type your text.", "Choose a voice, speed and pitch.", "Press Play — the word being read is highlighted."],
    about: "Reads text aloud using the speech voices available on your device and browser. Choose a voice and language, adjust the speed and pitch, and follow along as each word is highlighted.",
    useCases: ["Listen to an article while doing something else.", "Proofread writing by hearing it.", "Check how a word or name is pronounced."],
    related: ["word-counter", "case-converter", "fancy-text-generator"],
    notes: ["Many languages", "Word highlighting"],
    faqs: [
      { q: "Can I download the audio as an MP3?", a: "No. Browsers play speech directly but don't let websites record it as a file." },
      { q: "Why are the voices different on my phone?", a: "Voices come from your operating system and browser, so Windows, Mac, Android and iPhone each offer their own set." },
    ],
    guide: [
      { title: "Getting the best voice", body: ["Voices marked “online” are often more natural but need an internet connection. Pick a voice that matches the language of your text — an English voice reading French sounds wrong.", "Very long texts are read sentence by sentence, so you can paste whole articles."] },
    ],
    metaTitle: "Text to Speech — Read Text Aloud Online, Free",
    metaDescription: "Free text to speech in your browser. Choose a voice and language, adjust speed and pitch, and follow along with word highlighting. No sign-up.",
  },
  {
    slug: "fancy-text-generator",
    category: "text",
    name: "Fancy Text Generator",
    primaryKeyword: "fancy text generator",
    description: "Turn text into bold, italic, script, gothic and other styles you can paste anywhere.",
    icon: "italic",
    status: "live",
    addedAt: added,
    updatedAt,
    keywords: ["fancy text generator", "font generator", "bold text generator", "cursive text", "instagram fonts", "stylish text", "copy and paste fonts"],
    steps: ["Type your text.", "Browse the styles.", "Copy the one you like and paste it anywhere."],
    about: "Creates stylish versions of your text — bold, italic, script, gothic, double-struck, circled, upside down and more — using special Unicode characters. They paste into social media bios, posts, usernames and messages where you normally can't change the font.",
    useCases: ["Make an Instagram or TikTok bio stand out.", "Add bold or italic text to a social post.", "Create a stylish username or display name."],
    related: ["case-converter", "text-to-speech", "word-counter"],
    notes: ["19 styles", "Copy and paste anywhere"],
    faqs: [
      { q: "How does it work if it's not a font?", a: "Each style uses different Unicode characters that look like styled letters, so they keep their look wherever you paste them." },
      { q: "Are there any downsides?", a: "Screen readers may read these characters oddly or not at all, and search engines don't treat them as normal words. Use them for decoration, not for important information." },
    ],
    guide: [
      { title: "Where it works", body: ["Styled text works in most places that accept emoji: Instagram and TikTok bios, X posts, Discord and WhatsApp. Some apps and older devices show boxes instead of certain characters — check how it looks before posting.", "Letters and numbers change; punctuation and other characters stay as they are, and not every style has numbers."] },
    ],
    metaTitle: "Fancy Text Generator — Copy & Paste Fonts",
    metaDescription: "Generate fancy text in bold, italic, script, gothic, bubble and more styles to copy and paste into Instagram, TikTok, X and anywhere else.",
  },
];
