import type { Tool } from "@/lib/catalog/types";

/**
 * Tools outside YouTube. Every "live" tool here runs entirely in the browser —
 * no server, API or database. Tools that would need one are "coming-soon".
 */
const added = "2026-09-30";
const updatedAt = "2026-09-30";

export const otherTools: Tool[] = [
  /* ——— AI (planned — these need a server-side AI model) ——— */
  { slug: "text-summarizer", category: "ai", name: "AI Text Summarizer", description: "Turn a long article or document into a short, clear summary.", icon: "letters", status: "coming-soon", keywords: ["ai", "summarize", "summary", "tl;dr", "shorten text"] },
  { slug: "paraphraser", category: "ai", name: "AI Paraphraser", description: "Rewrite a sentence or paragraph in clearer, fresher words.", icon: "pen", status: "coming-soon", keywords: ["ai", "paraphrase", "rewrite", "reword"] },
  { slug: "grammar-checker", category: "ai", name: "AI Grammar Checker", description: "Fix spelling, grammar and punctuation mistakes.", icon: "type", status: "coming-soon", keywords: ["ai", "grammar", "spelling", "proofread"] },
  { slug: "background-remover", category: "ai", name: "AI Background Remover", description: "Remove the background from a photo in one click.", icon: "wand", status: "coming-soon", keywords: ["ai", "remove background", "transparent background", "cut out"] },
  { slug: "image-caption-generator", category: "ai", name: "AI Image Caption Generator", description: "Get a description or alt text for any image.", icon: "image", status: "coming-soon", keywords: ["ai", "caption", "alt text", "describe image"] },
  { slug: "title-generator", category: "ai", name: "AI Title Generator", description: "Get catchy title ideas for videos, blog posts and emails.", icon: "heading", status: "coming-soon", keywords: ["ai", "title ideas", "headline", "blog title"] },

  /* ——— Text ——— */
  {
    slug: "word-counter",
    category: "text",
    name: "Word Counter",
    primaryKeyword: "word counter",
    description: "Count words, characters, sentences and reading time as you type.",
    icon: "letters",
    status: "live",
    featured: true,
    popular: true,
    addedAt: added,
    keywords: ["words", "characters", "count", "letters", "reading time", "essay", "letter counter"],
    steps: ["Type or paste your text into the box.", "The counts update as you type.", "Copy or clear the text when you're done."],
    about: "Paste or type any text to see how many words, characters, sentences and paragraphs it has, plus how long it takes to read or say out loud. Counting happens on your device as you type.",
    useCases: ["Stay within a word limit for an essay, application or article.", "Keep social posts and descriptions under a character limit.", "Estimate how long a script or speech will take to read aloud."],
    updatedAt,
    related: ["case-converter", "whitespace-remover", "youtube/description-generator"],
    notes: ["Updates as you type", "Your text never leaves your device"],
    metaTitle: "Word Counter — Count Words, Characters & Reading Time",
    metaDescription: "Free online word counter. Count words, characters (with and without spaces), sentences, paragraphs and reading time as you type. Private, runs in your browser.",
  },
  {
    slug: "case-converter",
    category: "text",
    name: "Case Converter",
    primaryKeyword: "case converter",
    description: "Change text to UPPERCASE, lowercase, Title Case or Sentence case in one click.",
    icon: "case",
    status: "live",
    addedAt: added,
    keywords: ["uppercase", "lowercase", "title case", "sentence case", "capitalize", "caps"],
    steps: ["Paste your text into the box.", "Pick the style you want.", "Copy the result."],
    about: "Change text between UPPERCASE, lowercase, Title Case, Sentence case and more with one click — useful when text was typed with caps lock on or needs a consistent style.",
    useCases: ["Fix text typed with caps lock on.", "Turn a list of headings into consistent Title Case.", "Convert a shouty title into normal sentence case."],
    updatedAt,
    related: ["word-counter", "whitespace-remover", "seo/slug-generator"],
    notes: ["Your text never leaves your device"],
    metaTitle: "Case Converter — UPPERCASE, lowercase, Title Case & More",
    metaDescription: "Convert text to uppercase, lowercase, title case, sentence case, capitalized case and more. Free, instant and private.",
  },
  {
    slug: "remove-duplicate-lines",
    category: "text",
    name: "Remove Duplicate Lines",
    primaryKeyword: "remove duplicate lines",
    description: "Remove repeated lines from a list in one click, keeping the first of each.",
    icon: "copy-minus",
    status: "live",
    addedAt: added,
    keywords: ["duplicates", "unique", "list", "dedupe", "remove duplicates", "distinct"],
    steps: ["Paste your list, one item per line.", "Choose whether capitals and spaces matter.", "Copy or download the cleaned list."],
    about: "Paste any list and get back only the unique lines, in their original order. You can ignore differences in capital letters, trim stray spaces and drop empty lines.",
    useCases: ["Clean up an email or contact list before importing it.", "Remove repeated keywords or tags from a list.", "Tidy up data copied from a spreadsheet."],
    updatedAt,
    related: ["sort-lines", "whitespace-remover", "text-diff"],
    notes: ["Keeps the original order", "Runs in your browser"],
    faqs: [
      { q: "Which copy of a duplicate is kept?", a: "The first one. Later repeats are removed, and the order of everything else stays the same." },
      { q: "Does “Apple” count as a duplicate of “apple”?", a: "Only if you turn on “Ignore capital letters”." },
      { q: "Is there a size limit?", a: "No practical limit — tens of thousands of lines work fine in a modern browser." },
    ],
    metaTitle: "Remove Duplicate Lines — Free Online Duplicate Remover",
    metaDescription: "Remove duplicate lines from any list or text instantly. Keep the original order, ignore case, trim spaces and drop empty lines. Private and free.",
  },
  {
    slug: "sort-lines",
    category: "text",
    name: "Line Sorter",
    primaryKeyword: "sort lines",
    description: "Sort lines alphabetically, by number or length — or reverse and shuffle them.",
    icon: "sort",
    status: "live",
    addedAt: added,
    keywords: ["sort", "alphabetical", "a-z", "order", "sort list", "alphabetize", "shuffle lines"],
    steps: ["Paste your lines.", "Choose how to sort them.", "Copy the sorted list."],
    about: "Sort any list A→Z or Z→A, put numbers in their natural order (2 before 10), sort by length, reverse the order or shuffle it randomly. Handles accents and capital letters sensibly.",
    useCases: ["Alphabetise names, glossary terms or references.", "Put numbered items (like “item 2, item 10”) in the right order.", "Randomise the order of questions or tasks."],
    updatedAt,
    related: ["remove-duplicate-lines", "productivity/list-randomizer", "text-diff"],
    notes: ["Natural number sorting", "Runs in your browser"],
    faqs: [
      { q: "What does “Numbers in order” do?", a: "It sorts numbers by value, so “item 2” comes before “item 10” — normal alphabetical sorting would put 10 first." },
      { q: "Is the shuffle truly random?", a: "It uses your browser's secure random generator, so every order is equally likely." },
    ],
    metaTitle: "Sort Lines Online — Alphabetical, Numeric & Random",
    metaDescription: "Sort text lines alphabetically, in natural number order, by length, in reverse or at random. Free, instant and private.",
  },
  {
    slug: "whitespace-remover",
    category: "text",
    name: "Extra Space Remover",
    primaryKeyword: "remove extra spaces",
    description: "Remove extra spaces, tabs and blank lines from any text.",
    icon: "eraser",
    status: "live",
    addedAt: added,
    keywords: ["whitespace", "remove spaces", "extra spaces", "blank lines", "trim", "clean text", "line breaks"],
    steps: ["Paste the messy text.", "Choose what to clean up.", "Copy the tidy result."],
    about: "Text copied from PDFs, emails and websites often comes with double spaces, tabs, stray line breaks and blank lines. This tool cleans all of that in one go, and can join everything into a single line.",
    useCases: ["Fix text copied from a PDF that breaks in odd places.", "Tidy up pasted text before publishing it.", "Turn a multi-line list into one line."],
    updatedAt,
    related: ["remove-duplicate-lines", "word-counter", "case-converter"],
    notes: ["Runs in your browser"],
    faqs: [
      { q: "Will it remove single spaces between words?", a: "No. It only collapses runs of two or more spaces into one." },
      { q: "Can it fix line breaks from PDFs?", a: "Yes — turn on “Join into one line” to remove the breaks, then split paragraphs where you need them." },
    ],
    metaTitle: "Remove Extra Spaces — Whitespace & Blank Line Remover",
    metaDescription: "Remove double spaces, tabs, trailing spaces and blank lines from text, or join it into one line. Free online text cleaner that runs in your browser.",
  },
  {
    slug: "text-diff",
    category: "text",
    name: "Text Compare",
    primaryKeyword: "text compare",
    description: "Compare two versions of text and see exactly which lines changed.",
    icon: "diff",
    status: "live",
    addedAt: added,
    keywords: ["diff", "compare text", "difference", "changes", "text comparison", "diff checker"],
    steps: ["Paste the original text on the left.", "Paste the changed text on the right.", "See added and removed lines highlighted."],
    about: "Paste two versions of a document, list or code and see which lines were added, removed or left the same. You can ignore differences in spacing and capital letters.",
    useCases: ["Check what changed between two drafts.", "Compare two versions of a config file or code snippet.", "Spot differences between two lists."],
    updatedAt,
    related: ["remove-duplicate-lines", "sort-lines", "developer/json-formatter"],
    notes: ["Line-by-line", "Runs in your browser"],
    faqs: [
      { q: "Does it compare word by word?", a: "It compares line by line. A changed line shows as the old line removed and the new line added." },
      { q: "Is my text uploaded?", a: "No. The comparison runs on your device." },
    ],
    metaTitle: "Text Compare — Free Online Diff Checker",
    metaDescription: "Compare two texts and highlight added and removed lines. Ignore whitespace or case. A free, private diff checker that runs in your browser.",
  },
  {
    slug: "lorem-ipsum-generator",
    category: "text",
    name: "Lorem Ipsum Generator",
    primaryKeyword: "lorem ipsum generator",
    description: "Generate placeholder text by paragraphs, sentences or words.",
    icon: "pilcrow",
    status: "live",
    addedAt: added,
    keywords: ["lorem ipsum", "placeholder text", "dummy text", "filler text"],
    steps: ["Choose paragraphs, sentences or words.", "Pick how many you need.", "Copy the text into your design."],
    about: "Lorem ipsum is scrambled Latin used as placeholder text in designs and layouts, so people focus on the look rather than the words. Generate exactly as much as you need.",
    useCases: ["Fill a website mock-up or template before the real copy is ready.", "Test how a layout handles long or short text.", "Create sample content for a presentation."],
    updatedAt,
    related: ["word-counter", "case-converter", "whitespace-remover"],
    notes: ["Instant", "Runs in your browser"],
    faqs: [
      { q: "What does lorem ipsum mean?", a: "It's based on a passage from Cicero's “De finibus”, scrambled so it reads as meaningless text." },
      { q: "Can I start with “Lorem ipsum dolor sit amet”?", a: "Yes — that option is on by default." },
    ],
    metaTitle: "Lorem Ipsum Generator — Placeholder Text Paragraphs",
    metaDescription: "Generate lorem ipsum placeholder text by paragraphs, sentences or words for mockups and layouts. Copy or download it instantly, free.",
  },

  /* ——— Images ——— */
  {
    slug: "compressor",
    category: "image",
    name: "Image Compressor",
    primaryKeyword: "image compressor",
    description: "Make photos and images smaller without losing visible quality.",
    icon: "shrink",
    status: "live",
    popular: true,
    featured: true,
    addedAt: added,
    keywords: ["compress", "reduce size", "smaller", "jpg", "png", "optimize", "image size", "kb"],
    steps: ["Drop your image into the box.", "Adjust the quality and see the new size.", "Download the smaller image."],
    about: "Big images slow down websites and fill up email attachments. This tool re-saves your image at a quality you choose — usually a fraction of the size with no visible difference — and can shrink its dimensions too.",
    useCases: ["Make photos small enough to email or upload.", "Speed up a website by shrinking its images.", "Save space on your device."],
    updatedAt,
    related: ["resizer", "converter", "cropper"],
    notes: ["Images never leave your device", "Before/after comparison"],
    faqs: [
      { q: "What quality should I use?", a: "Around 70–80% is a good balance for photos. Check the preview — if it looks the same, it's fine." },
      { q: "Why did my PNG get bigger?", a: "PNGs of graphics are often already small. Try WebP, or keep the original." },
      { q: "Are my images uploaded?", a: "No. Compression happens in your browser using the Canvas API." },
    ],
    metaTitle: "Image Compressor — Reduce Image File Size Online",
    metaDescription: "Compress JPG, PNG and WebP images in your browser. Choose the quality, compare the size before and after, and download. Private — nothing is uploaded.",
  },
  {
    slug: "resizer",
    category: "image",
    name: "Image Resizer",
    primaryKeyword: "image resizer",
    description: "Change an image's width and height in pixels or by percentage.",
    icon: "scaling",
    status: "live",
    addedAt: added,
    keywords: ["resize", "dimensions", "scale", "width", "height", "pixels", "resize photo"],
    steps: ["Drop your image into the box.", "Enter a new width or height (or a percentage).", "Download the resized image."],
    about: "Resize any image to exact pixel dimensions, keep its proportions or stretch it, and save it as PNG, JPG or WebP. Useful for profile pictures, forms with size limits and web images.",
    useCases: ["Resize a photo to the size a website or form asks for.", "Make a large image smaller for the web.", "Create a thumbnail version of an image."],
    updatedAt,
    related: ["compressor", "cropper", "converter"],
    notes: ["Keeps proportions", "Images never leave your device"],
    faqs: [
      { q: "Will making an image bigger improve its quality?", a: "No. Enlarging adds pixels by estimating them, so the image looks softer. Start from the largest version you have." },
      { q: "What's the maximum size?", a: "Up to 12,000 pixels on each side, depending on your device's memory." },
    ],
    metaTitle: "Image Resizer — Resize Images to Exact Pixels Online",
    metaDescription: "Resize images to any width and height, keep proportions or scale by percentage, and download as PNG, JPG or WebP. Free and private.",
  },
  {
    slug: "cropper",
    category: "image",
    name: "Image Cropper",
    primaryKeyword: "image cropper",
    description: "Cut an image to the exact shape and size you need.",
    icon: "crop",
    status: "live",
    addedAt: added,
    keywords: ["crop", "cut", "trim", "square", "16:9", "aspect ratio", "crop photo"],
    steps: ["Drop your image into the box.", "Drag the box and pick a shape like square or 16:9.", "Download the cropped image."],
    about: "Crop an image by dragging a box over the part you want to keep. Lock it to common shapes — square for profile pictures, 16:9 for videos and slides, 9:16 for stories — or crop freely.",
    useCases: ["Make a square profile picture.", "Crop a screenshot to the important part.", "Fit an image to 16:9 or a story format."],
    updatedAt,
    related: ["resizer", "compressor", "youtube/thumbnail-safe-zone"],
    notes: ["Common aspect ratios", "Images never leave your device"],
    faqs: [
      { q: "Does cropping reduce quality?", a: "No. The part you keep is saved at its original resolution." },
      { q: "Can I crop to exact pixel sizes?", a: "Crop to the shape you want here, then use the image resizer to set exact dimensions." },
    ],
    metaTitle: "Image Cropper — Crop Photos Online (Square, 16:9, Free)",
    metaDescription: "Crop images online by dragging a box. Lock to square, 16:9, 4:3 or 9:16, and download as PNG, JPG or WebP. Free and private.",
  },
  {
    slug: "converter",
    category: "image",
    name: "Image Converter",
    primaryKeyword: "image converter",
    description: "Convert images between JPG, PNG and WebP.",
    icon: "file-image",
    status: "live",
    addedAt: added,
    keywords: ["convert", "jpg", "png", "webp", "format", "png to jpg", "webp to jpg", "jpg to png"],
    steps: ["Drop your image into the box.", "Choose JPG, PNG or WebP.", "Download the converted file."],
    about: "Change an image's format in seconds: WebP to JPG for apps that don't support WebP, PNG to JPG to make photos smaller, or JPG to PNG when you need a lossless copy.",
    useCases: ["Convert a WebP image so an older app or site accepts it.", "Turn a large PNG photo into a smaller JPG.", "Save a lossless PNG copy for editing."],
    updatedAt,
    related: ["compressor", "resizer", "image-to-base64"],
    notes: ["JPG, PNG and WebP", "Images never leave your device"],
    faqs: [
      { q: "What happens to transparency when converting to JPG?", a: "JPG doesn't support transparency, so see-through areas become white." },
      { q: "Which format is smallest?", a: "WebP is usually smallest for the same quality, then JPG. PNG is lossless and larger for photos." },
    ],
    metaTitle: "Image Converter — Convert WebP, PNG and JPG Online",
    metaDescription: "Convert images between JPG, PNG and WebP in your browser. Choose the quality and download instantly. Free — nothing is uploaded.",
  },
  {
    slug: "color-extractor",
    category: "image",
    name: "Image Color Extractor",
    primaryKeyword: "image color extractor",
    description: "Get the main colors from any image, or click to pick an exact color.",
    icon: "pipette",
    status: "live",
    addedAt: added,
    keywords: ["color picker", "palette from image", "extract colors", "hex from image", "eyedropper"],
    steps: ["Drop your image into the box.", "See its main colors, or click the image to pick one.", "Copy the color codes you need."],
    about: "Find the colors an image is made of: the tool groups similar pixels to show the main colors and how much of the image each covers. Click anywhere on the image to pick that exact color.",
    useCases: ["Build a color palette from a photo or logo.", "Find the exact HEX code of a color in a screenshot.", "Match your design to a brand image."],
    updatedAt,
    related: ["color/shades-generator", "color/color-converter", "converter"],
    notes: ["Click-to-pick eyedropper", "Images never leave your device"],
    faqs: [
      { q: "How are the main colors chosen?", a: "Similar pixels are grouped together (a method called k-means), and each group's average color is shown with its share of the image." },
      { q: "Can I get colors from a website?", a: "Take a screenshot, then drop it here." },
    ],
    metaTitle: "Image Color Extractor & Picker — Get HEX Colors From Images",
    metaDescription: "Extract a color palette from any image and pick exact colors by clicking. Copy HEX codes instantly. Free and private.",
  },
  {
    slug: "image-to-base64",
    category: "image",
    name: "Image to Base64",
    primaryKeyword: "image to base64",
    description: "Turn an image into a Base64 data URI for HTML, CSS or code.",
    icon: "binary",
    status: "live",
    addedAt: added,
    keywords: ["base64", "data uri", "image to base64", "embed image", "inline image"],
    steps: ["Drop your image into the box.", "Choose data URI, plain Base64, CSS or HTML.", "Copy the code."],
    about: "Base64 turns an image file into text, so it can be placed directly inside HTML, CSS or JSON instead of being loaded as a separate file. Handy for small icons and emails.",
    useCases: ["Embed a small icon directly in CSS.", "Include an image in a JSON payload or API test.", "Put a logo inside an HTML email template."],
    updatedAt,
    related: ["developer/base64", "converter", "svg-to-png"],
    notes: ["Works with SVG too", "Images never leave your device"],
    faqs: [
      { q: "Is Base64 bigger than the image?", a: "Yes — about a third bigger. It's best for small images; larger ones load faster as normal files." },
    ],
    metaTitle: "Image to Base64 Converter — Data URI for HTML & CSS",
    metaDescription: "Convert JPG, PNG, WebP, GIF or SVG images to Base64 data URIs, CSS backgrounds or HTML img tags. Free and private.",
  },
  {
    slug: "svg-to-png",
    category: "image",
    name: "SVG to PNG",
    primaryKeyword: "svg to png",
    description: "Convert SVG files or code into a PNG image at any size.",
    icon: "image-plus",
    status: "live",
    addedAt: added,
    keywords: ["svg to png", "convert svg", "svg image", "vector to png"],
    steps: ["Drop an SVG file or paste SVG code.", "Pick a size (1× to 4×).", "Download the PNG."],
    about: "SVG is a sharp vector format, but many apps and sites only accept PNG. This tool draws your SVG in the browser and saves it as a PNG at the size you choose, with or without a transparent background.",
    useCases: ["Use an SVG logo somewhere that only accepts PNG.", "Export an icon at 2× or 4× for crisp screens.", "Turn SVG code from a design tool into an image."],
    updatedAt,
    related: ["image-to-base64", "converter", "resizer"],
    notes: ["Up to 4× size", "Files never leave your device"],
    faqs: [
      { q: "Why does my SVG look different?", a: "SVGs that load external fonts or images can't include them when drawn in the browser. Convert text to outlines in your design tool first." },
    ],
    metaTitle: "SVG to PNG Converter — Convert SVG to High-Resolution PNG",
    metaDescription: "Convert SVG files or code to PNG at 1× to 4× size, with a transparent background. Free and private — runs in your browser.",
  },

  /* ——— PDFs ——— */
  {
    slug: "merge",
    category: "pdf",
    name: "PDF Merger",
    primaryKeyword: "merge pdf",
    description: "Combine several PDF files into one, in the order you choose.",
    icon: "merge",
    status: "live",
    popular: true,
    featured: true,
    addedAt: added,
    keywords: ["merge", "combine", "join", "merge pdf", "combine pdf files"],
    steps: ["Drop your PDFs into the box.", "Put them in the right order.", "Merge and download one PDF."],
    about: "Put several PDFs together into a single file — invoices, scanned pages, chapters. Everything happens in your browser, so your documents are never uploaded.",
    useCases: ["Combine scanned pages into one document.", "Send several attachments as one file.", "Join chapters or reports into a single PDF."],
    updatedAt,
    related: ["split", "images-to-pdf", "compressor"],
    notes: ["Files never leave your device", "Reorder before merging"],
    faqs: [
      { q: "Is there a file size limit?", a: "No fixed limit — it depends on your device's memory. Hundreds of pages are usually fine." },
      { q: "Can I merge password-protected PDFs?", a: "Remove the password first in your PDF reader, then merge." },
      { q: "Are my files uploaded?", a: "No. The merging happens entirely in your browser." },
    ],
    metaTitle: "Merge PDF Files Online — Combine PDFs Privately",
    metaDescription: "Merge PDF files into one in your browser. Reorder files before combining. Nothing is uploaded — free and private.",
  },
  {
    slug: "split",
    category: "pdf",
    name: "PDF Splitter",
    primaryKeyword: "split pdf",
    description: "Pull out the pages you need, or split a PDF into single pages.",
    icon: "scissors",
    status: "live",
    addedAt: added,
    keywords: ["split", "separate", "extract pages", "split pdf", "remove pages"],
    steps: ["Drop your PDF into the box.", "Type the pages you want, like 1-3, 5.", "Download the new PDF."],
    about: "Extract just the pages you need into a new PDF, or split every page into its own file. Type page ranges like “1-3, 5, 8-” — the original file isn't changed.",
    useCases: ["Send only the relevant pages of a long document.", "Remove pages you don't need by keeping the rest.", "Split a scanned bundle into separate documents."],
    updatedAt,
    related: ["merge", "images-to-pdf", "compressor"],
    notes: ["Files never leave your device"],
    faqs: [
      { q: "How do I write page ranges?", a: "Separate with commas: “1-3, 5, 8-” means pages 1 to 3, page 5, and page 8 to the end." },
      { q: "Can I remove pages?", a: "Yes — list the pages you want to keep, and download that." },
    ],
    metaTitle: "Split PDF Online — Extract Pages From a PDF",
    metaDescription: "Split a PDF or extract selected pages (like 1-3, 5) into a new file, in your browser. Free and private — nothing is uploaded.",
  },
  {
    slug: "images-to-pdf",
    category: "pdf",
    name: "Images to PDF",
    primaryKeyword: "jpg to pdf",
    description: "Turn photos and images into a single PDF, one image per page.",
    icon: "file-plus",
    status: "live",
    addedAt: added,
    keywords: ["jpg to pdf", "image to pdf", "photos to pdf", "png to pdf", "convert images to pdf"],
    steps: ["Drop your images into the box.", "Put them in order and choose a page size.", "Create and download the PDF."],
    about: "Combine photos, screenshots or scanned pages into one PDF. Choose A4, US Letter or pages that match each image, and set a margin. Each image is placed on its own page.",
    useCases: ["Turn phone photos of documents into one PDF.", "Send several screenshots as a single file.", "Make a simple photo booklet."],
    updatedAt,
    related: ["merge", "split", "image/compressor"],
    notes: ["JPG, PNG, WebP, GIF", "Files never leave your device"],
    faqs: [
      { q: "Will the images lose quality?", a: "JPG and PNG images are placed as they are. Other formats are converted to PNG first." },
      { q: "Can I make the PDF smaller?", a: "Compress the images with the image compressor before adding them." },
    ],
    metaTitle: "Images to PDF — Convert JPG and PNG to PDF Online",
    metaDescription: "Convert JPG, PNG and WebP images into one PDF. Reorder pages, choose A4 or Letter, set margins. Free and private — runs in your browser.",
  },
  {
    slug: "compressor",
    category: "pdf",
    name: "PDF Compressor",
    description: "Make a PDF file smaller so it's easier to send.",
    icon: "shrink",
    // Proper PDF compression re-encodes embedded images, which needs server-side processing.
    status: "coming-soon",
    keywords: ["compress", "reduce size", "smaller", "compress pdf"],
  },

  /* ——— Social media (planned) ——— */
  { slug: "hashtag-counter", category: "social-media", name: "Hashtag Counter", description: "Count hashtags and characters before you post.", icon: "hash", status: "coming-soon", keywords: ["hashtags", "instagram", "tiktok", "caption"] },
  { slug: "bio-formatter", category: "social-media", name: "Bio Line Break Tool", description: "Add clean line breaks to your Instagram or TikTok bio.", icon: "at", status: "coming-soon", keywords: ["bio", "line break", "instagram", "tiktok"] },

  /* ——— Developer ——— */
  {
    slug: "json-formatter",
    category: "developer",
    name: "JSON Formatter",
    primaryKeyword: "json formatter",
    description: "Make JSON readable, check it for errors, or minify it.",
    icon: "braces",
    status: "live",
    popular: true,
    featured: true,
    addedAt: added,
    keywords: ["json", "format", "pretty", "validate", "beautify", "minify json", "json validator"],
    steps: ["Paste your JSON.", "Pick an indent style — or minify.", "Copy or download the result."],
    about: "Paste JSON to format it with clean indentation, check that it's valid (errors show the line and column), sort keys alphabetically or minify it to one line.",
    useCases: ["Read an API response that arrived as one long line.", "Find the exact spot where a JSON file is broken.", "Minify JSON before embedding it."],
    updatedAt,
    related: ["base64", "jwt-decoder", "text/text-diff"],
    notes: ["Shows error line and column", "Nothing is uploaded"],
    faqs: [
      { q: "Is it safe to paste private data?", a: "Yes. The JSON is parsed in your browser and never sent anywhere." },
      { q: "Does it accept comments or trailing commas?", a: "No — those aren't valid JSON, so the tool points them out." },
    ],
    metaTitle: "JSON Formatter & Validator — Beautify or Minify JSON",
    metaDescription: "Format, validate and minify JSON online. See the exact line and column of errors, sort keys, choose indentation. Private — runs in your browser.",
  },
  {
    slug: "url-encoder",
    category: "developer",
    name: "URL Encoder",
    primaryKeyword: "url encoder",
    description: "Encode or decode text for use in web links.",
    icon: "link",
    status: "live",
    addedAt: added,
    keywords: ["url", "encode", "decode", "percent", "urlencode", "uri", "%20"],
    steps: ["Choose encode or decode.", "Paste your text or link.", "Copy the result."],
    about: "Web addresses can't contain spaces or certain symbols, so they're written as percent codes like %20. Encode text to put it safely in a URL, or decode a messy link to read it.",
    useCases: ["Put a search term or email address into a link.", "Read a long tracking link full of %20 codes.", "Debug query parameters in an API call."],
    updatedAt,
    related: ["base64", "html-entities", "marketing/utm-builder"],
    notes: ["Runs in your browser"],
    faqs: [
      { q: "What's the difference between the two encode options?", a: "By default every special character is encoded (right for a single parameter). The other option keeps a full address readable by leaving characters like / and ? alone." },
    ],
    metaTitle: "URL Encoder & Decoder — Percent-Encode Text Online",
    metaDescription: "Encode text for URLs or decode percent-encoded links (%20, %26…). Handles full URLs and query values. Runs in your browser, free and private.",
  },
  {
    slug: "base64",
    category: "developer",
    name: "Base64 Encoder",
    primaryKeyword: "base64 encoder",
    description: "Encode text to Base64 or decode Base64 back to text.",
    icon: "binary",
    status: "live",
    addedAt: added,
    keywords: ["base64", "encode", "decode", "b64", "base64 decode"],
    steps: ["Choose encode or decode.", "Paste your text.", "Copy the result."],
    about: "Base64 represents any text or data using only letters, numbers and a few symbols, so it can travel safely through email, URLs and JSON. Encode text or decode a Base64 string — emoji and accents included.",
    useCases: ["Decode a Base64 value from an API or config file.", "Encode credentials for a Basic Auth header.", "Create URL-safe Base64 for tokens."],
    updatedAt,
    related: ["url-encoder", "jwt-decoder", "image/image-to-base64"],
    notes: ["Supports emoji and accents", "Runs in your browser"],
    faqs: [
      { q: "Is Base64 encryption?", a: "No. Anyone can decode it — it only changes how data is written, not who can read it." },
    ],
    metaTitle: "Base64 Encoder & Decoder — Encode or Decode Text Online",
    metaDescription: "Encode text to Base64 or decode Base64 strings, including URL-safe Base64 and Unicode. Free, instant and private.",
  },
  {
    slug: "html-entities",
    category: "developer",
    name: "HTML Entity Encoder",
    primaryKeyword: "html entity encoder",
    description: "Escape text for HTML (&lt; &amp; …) or turn entities back into text.",
    icon: "file-code",
    status: "live",
    addedAt: added,
    keywords: ["html entities", "escape html", "unescape", "&amp;", "html encode"],
    steps: ["Choose encode or decode.", "Paste your text or HTML.", "Copy the result."],
    about: "Characters like < and & have special meaning in HTML. Encoding turns them into entities (&lt;, &amp;) so they show as text; decoding turns entities back into normal characters.",
    useCases: ["Show code examples on a web page.", "Make user-entered text safe to place in HTML.", "Read text full of &amp; and &#39; codes."],
    updatedAt,
    related: ["url-encoder", "base64", "json-formatter"],
    notes: ["Runs in your browser"],
    faqs: [
      { q: "Which characters are encoded?", a: "& < > \" and ' by default. You can also encode every accented letter and symbol as a numeric entity." },
    ],
    metaTitle: "HTML Entity Encoder & Decoder — Escape HTML Online",
    metaDescription: "Encode special characters like < > & and quotes as HTML entities, or decode entities back to plain text. Free, instant and private.",
  },
  {
    slug: "hash-generator",
    category: "developer",
    name: "Hash Generator",
    primaryKeyword: "hash generator",
    description: "Create MD5, SHA-1, SHA-256, SHA-384 and SHA-512 hashes of any text.",
    icon: "fingerprint",
    status: "live",
    addedAt: added,
    keywords: ["md5", "sha256", "sha1", "sha512", "hash", "checksum", "sha-256"],
    steps: ["Type or paste your text.", "All five hashes update instantly.", "Copy the one you need."],
    about: "A hash is a short fingerprint of some text: the same input always gives the same hash, and any change gives a completely different one. Generate MD5, SHA-1 and the SHA-2 family at once.",
    useCases: ["Check that two pieces of text are identical.", "Create a checksum for a value in a script or config.", "Compare a hash from documentation with your own."],
    updatedAt,
    related: ["uuid-generator", "base64", "productivity/password-generator"],
    notes: ["Web Crypto API", "Runs in your browser"],
    faqs: [
      { q: "Can a hash be decrypted?", a: "No — hashing is one-way. Sites that “decrypt” MD5 just look it up in lists of common inputs." },
      { q: "Should I use MD5 for passwords?", a: "No. Use a dedicated password-hashing method such as bcrypt or Argon2 on your server." },
    ],
    metaTitle: "Hash Generator — MD5, SHA-1, SHA-256 & SHA-512 Online",
    metaDescription: "Generate MD5, SHA-1, SHA-256, SHA-384 and SHA-512 hashes of any text instantly. Runs privately in your browser.",
  },
  {
    slug: "uuid-generator",
    category: "developer",
    name: "UUID Generator",
    primaryKeyword: "uuid generator",
    description: "Generate random version 4 UUIDs, one or a hundred at a time.",
    icon: "key",
    status: "live",
    addedAt: added,
    keywords: ["uuid", "guid", "uuid v4", "random id", "unique id"],
    steps: ["Choose how many you need.", "Pick uppercase or no hyphens if you like.", "Copy or download them."],
    about: "A UUID is a 128-bit identifier that's practically guaranteed to be unique. These are version 4 UUIDs made from your browser's secure random generator.",
    useCases: ["Create IDs for database records or test data.", "Generate unique keys for files or requests.", "Fill a spreadsheet with unique identifiers."],
    updatedAt,
    related: ["hash-generator", "productivity/password-generator", "productivity/random-number-generator"],
    notes: ["Cryptographically secure", "Runs in your browser"],
    faqs: [{ q: "Can two UUIDs be the same?", a: "In theory, but the chance is so small it can be ignored for any practical purpose." }],
    metaTitle: "UUID Generator — Random v4 UUIDs / GUIDs Online",
    metaDescription: "Generate up to 100 random version 4 UUIDs (GUIDs) at once, with or without hyphens, using a secure random generator. Free and instant.",
  },
  {
    slug: "jwt-decoder",
    category: "developer",
    name: "JWT Decoder",
    primaryKeyword: "jwt decoder",
    description: "Read the header and payload of a JSON Web Token, and see when it expires.",
    icon: "lock",
    status: "live",
    addedAt: added,
    keywords: ["jwt", "json web token", "decode jwt", "token", "jwt parser"],
    steps: ["Paste your token.", "See the decoded header and payload.", "Check the expiry and issue times."],
    about: "A JWT is a login or API token made of three parts. This tool decodes the header and payload so you can read the claims inside — including when it expires — without sending the token anywhere.",
    useCases: ["Check which user or permissions a token contains.", "Find out why an API rejects a token (for example, it has expired).", "Debug login flows during development."],
    updatedAt,
    related: ["base64", "json-formatter", "timestamp-converter"],
    notes: ["Token never leaves your browser"],
    faqs: [
      { q: "Does it verify the signature?", a: "No. Verifying needs the secret or public key, which should stay on your server. Decoding only reads the contents." },
      { q: "Is it safe to paste a real token?", a: "It isn't sent anywhere, but treat live tokens like passwords and avoid sharing your screen while they're visible." },
    ],
    metaTitle: "JWT Decoder — Decode JSON Web Tokens Online",
    metaDescription: "Decode a JWT to read its header, payload and expiry time. Runs entirely in your browser — your token is never sent anywhere.",
  },
  {
    slug: "timestamp-converter",
    category: "developer",
    name: "Unix Timestamp Converter",
    primaryKeyword: "unix timestamp converter",
    description: "Convert Unix timestamps to dates and dates to timestamps.",
    icon: "timer",
    status: "live",
    addedAt: added,
    keywords: ["unix timestamp", "epoch", "epoch converter", "timestamp to date", "date to timestamp"],
    steps: ["Paste a timestamp, or pick a date.", "See it in your time zone, UTC and ISO format.", "Copy the value you need."],
    about: "Unix time counts seconds since 1 January 1970 (UTC), and it's how most systems store dates. Convert a timestamp to a readable date — seconds or milliseconds are detected automatically — or turn a date into a timestamp.",
    useCases: ["Read dates in logs and API responses.", "Create a timestamp for a script or database.", "Check what time an event happened in UTC."],
    updatedAt,
    related: ["jwt-decoder", "calculators/age-calculator", "json-formatter"],
    notes: ["Seconds or milliseconds", "Runs in your browser"],
    faqs: [{ q: "How do I know if it's seconds or milliseconds?", a: "Timestamps with 13 digits are milliseconds; 10 digits are seconds. The tool detects this for you." }],
    metaTitle: "Unix Timestamp Converter — Epoch to Date and Back",
    metaDescription: "Convert Unix epoch timestamps (seconds or milliseconds) to readable dates in your time zone, UTC and ISO 8601 — and dates back to timestamps.",
  },
  {
    slug: "regex-tester",
    category: "developer",
    name: "Regex Tester",
    primaryKeyword: "regex tester",
    description: "Test regular expressions with live highlighting and replace.",
    icon: "regex",
    status: "live",
    addedAt: added,
    keywords: ["regex", "regular expression", "regex tester", "pattern", "regexp"],
    steps: ["Type your pattern.", "Paste some text to search.", "See matches highlighted, with their groups."],
    about: "Write a regular expression and see every match highlighted as you type, with capture groups listed. Try a replacement to see the result. Uses the JavaScript regex engine built into your browser.",
    useCases: ["Build and debug a pattern before putting it in code.", "Find all email addresses or dates in some text.", "Preview a find-and-replace across a document."],
    updatedAt,
    related: ["json-formatter", "text/text-diff", "text/whitespace-remover"],
    notes: ["JavaScript flavour", "Runs in your browser"],
    faqs: [{ q: "Which regex flavour is this?", a: "JavaScript (ECMAScript). Most patterns work the same in other languages, but some features differ." }],
    metaTitle: "Regex Tester — Test Regular Expressions Online",
    metaDescription: "Test JavaScript regular expressions with live match highlighting, capture groups, flags and replace preview. Free and private.",
  },

  /* ——— Color ——— */
  {
    slug: "color-converter",
    category: "color",
    name: "Color Converter",
    primaryKeyword: "color converter",
    description: "Convert colors between HEX, RGB, HSL, HSV and CMYK.",
    icon: "palette",
    status: "live",
    addedAt: added,
    keywords: ["hex to rgb", "rgb to hex", "color converter", "hsl", "cmyk", "color codes"],
    steps: ["Type a color in any format — or pick one.", "See it in every other format.", "Copy the code you need."],
    about: "Paste a color as HEX, RGB, HSL or even a name like “teal”, and get it in every common format at once. Handy when a design tool, website and print shop all want different codes.",
    useCases: ["Turn a HEX code from a brand guide into RGB.", "Get HSL values to create lighter and darker versions.", "Find an approximate CMYK value for print."],
    updatedAt,
    related: ["contrast-checker", "shades-generator", "image/color-extractor"],
    notes: ["HEX, RGB, HSL, HSV, CMYK"],
    faqs: [{ q: "Is the CMYK value exact for printing?", a: "It's a standard mathematical conversion. Printed colors depend on the printer's color profile, so check with your print shop for exact matching." }],
    metaTitle: "Color Converter — HEX to RGB, HSL, HSV and CMYK",
    metaDescription: "Convert colors between HEX, RGB, HSL, HSV and CMYK instantly. Paste any color code or name and copy every format.",
  },
  {
    slug: "contrast-checker",
    category: "color",
    name: "Contrast Checker",
    primaryKeyword: "color contrast checker",
    description: "Check that text is readable on its background, using WCAG standards.",
    icon: "contrast",
    status: "live",
    popular: true,
    addedAt: added,
    keywords: ["contrast checker", "wcag", "accessibility", "color contrast", "aa", "aaa", "readable"],
    steps: ["Pick a text color and a background color.", "See the contrast ratio and a live preview.", "Adjust until the checks pass."],
    about: "Low-contrast text is hard to read, especially on phones and for people with low vision. This tool calculates the contrast ratio between two colors and checks it against the WCAG AA and AAA levels.",
    useCases: ["Make sure button text is readable.", "Check brand colors before using them for text.", "Meet accessibility requirements on a website."],
    updatedAt,
    related: ["color-converter", "shades-generator", "youtube/thumbnail-analyzer"],
    notes: ["WCAG 2 AA and AAA"],
    faqs: [
      { q: "What ratio should I aim for?", a: "At least 4.5:1 for normal text and 3:1 for large text (WCAG AA). 7:1 meets the stricter AAA level." },
      { q: "What counts as large text?", a: "About 24px and up, or 18.5px and up when bold." },
    ],
    metaTitle: "Color Contrast Checker — WCAG AA & AAA",
    metaDescription: "Check the contrast ratio between text and background colors against WCAG 2 AA and AAA, with a live preview. Free accessibility tool.",
  },
  {
    slug: "shades-generator",
    category: "color",
    name: "Color Shades Generator",
    primaryKeyword: "color shades generator",
    description: "Turn one color into a full palette of tints and shades.",
    icon: "swatch",
    status: "live",
    addedAt: added,
    keywords: ["shades", "tints", "palette", "color scale", "tailwind colors", "color palette generator"],
    steps: ["Pick a base color.", "Choose how many steps you want.", "Copy colors or the CSS variables."],
    about: "Get lighter tints and darker shades of any color, arranged from lightest to darkest like a design-system scale, with the HEX code of each and ready-to-paste CSS variables.",
    useCases: ["Build hover and background colors from a brand color.", "Create a color scale for a design system.", "Find a lighter version of a color for backgrounds."],
    updatedAt,
    related: ["color-converter", "contrast-checker", "css/gradient-generator"],
    notes: ["Exports CSS variables"],
    faqs: [{ q: "How are tints and shades made?", a: "Tints mix the color with white; shades mix it with black, in even steps." }],
    metaTitle: "Color Shades Generator — Tints & Shades of Any Color",
    metaDescription: "Generate tints and shades of any color as a palette scale for UI states and design systems. Copy HEX codes or CSS variables. Free.",
  },

  /* ——— CSS ——— */
  {
    slug: "gradient-generator",
    category: "css",
    name: "CSS Gradient Generator",
    primaryKeyword: "css gradient generator",
    description: "Design linear and radial gradients visually and copy the CSS.",
    icon: "paintbrush",
    status: "live",
    addedAt: added,
    keywords: ["css gradient", "linear gradient", "radial gradient", "gradient generator", "background gradient"],
    steps: ["Pick colors and positions.", "Set the angle or switch to radial.", "Copy the CSS."],
    about: "Build a CSS gradient with up to five colors, adjust the angle and each color's position, and see it change live. The code includes a solid fallback color.",
    useCases: ["Create a background for a hero section or button.", "Match a gradient from a design mock-up.", "Experiment with color combinations."],
    updatedAt,
    related: ["box-shadow-generator", "border-radius-generator", "color/shades-generator"],
    notes: ["Live preview", "Up to five colors"],
    faqs: [{ q: "Why is there a solid color first?", a: "It's a fallback for the rare browser that can't draw gradients." }],
    metaTitle: "CSS Gradient Generator — Linear & Radial Gradients",
    metaDescription: "Create CSS linear and radial gradients with a live preview. Add up to five color stops, set the angle and copy the code.",
  },
  {
    slug: "box-shadow-generator",
    category: "css",
    name: "Box Shadow Generator",
    primaryKeyword: "box shadow generator",
    description: "Create soft or sharp CSS box shadows with a live preview.",
    icon: "layers",
    status: "live",
    addedAt: added,
    keywords: ["box shadow", "css shadow", "drop shadow", "shadow generator"],
    steps: ["Adjust the offset, blur and spread.", "Pick the color and opacity.", "Copy the CSS."],
    about: "Tweak a box shadow with sliders and see it on a card instantly — from subtle elevation to bold drop shadows, including inner (inset) shadows.",
    useCases: ["Give cards and buttons depth.", "Match a shadow from a design file.", "Create an inner shadow for input fields."],
    updatedAt,
    related: ["border-radius-generator", "gradient-generator", "minifier"],
    notes: ["Live preview"],
    faqs: [{ q: "What does spread do?", a: "Positive spread makes the shadow bigger than the box; negative spread makes it smaller, which gives softer, more realistic shadows." }],
    metaTitle: "CSS Box Shadow Generator — Visual Shadow Editor",
    metaDescription: "Generate CSS box-shadow code with sliders for offset, blur, spread, color and opacity. Live preview, including inset shadows.",
  },
  {
    slug: "border-radius-generator",
    category: "css",
    name: "Border Radius Generator",
    primaryKeyword: "border radius generator",
    description: "Round the corners of any element and copy the CSS.",
    icon: "corner",
    status: "live",
    addedAt: added,
    keywords: ["border radius", "rounded corners", "css border radius"],
    steps: ["Choose one radius for all corners, or set each one.", "Watch the preview change.", "Copy the CSS."],
    about: "Set rounded corners visually — the same on every corner or different on each — and copy the shortest correct CSS.",
    useCases: ["Round cards, buttons and images.", "Create pill or leaf shapes with uneven corners.", "Match the corner radius from a design."],
    updatedAt,
    related: ["box-shadow-generator", "gradient-generator", "minifier"],
    notes: ["Live preview"],
    faqs: [{ q: "What order are the four values in?", a: "Top left, top right, bottom right, bottom left — clockwise from the top left." }],
    metaTitle: "CSS Border Radius Generator — Rounded Corners",
    metaDescription: "Generate CSS border-radius for all corners or each corner separately, with a live preview. Copy the code instantly.",
  },
  {
    slug: "minifier",
    category: "css",
    name: "CSS Minifier",
    primaryKeyword: "css minifier",
    description: "Shrink CSS by removing comments and extra spaces.",
    icon: "minimize",
    status: "live",
    addedAt: added,
    keywords: ["css minifier", "minify css", "compress css", "css compressor"],
    steps: ["Paste your CSS.", "See the minified version and how much smaller it is.", "Copy or download it."],
    about: "Minifying removes comments, line breaks and spaces the browser doesn't need, so your stylesheet downloads faster. The CSS behaves exactly the same.",
    useCases: ["Shrink a stylesheet before putting it live.", "Minify CSS for an HTML email or embed.", "Check how much space comments take up."],
    updatedAt,
    related: ["gradient-generator", "developer/json-formatter", "text/whitespace-remover"],
    notes: ["Runs in your browser"],
    faqs: [{ q: "Can minifying break my CSS?", a: "It only removes characters the browser ignores, and keeps spaces where CSS needs them (such as inside calc)." }],
    metaTitle: "CSS Minifier — Minify & Compress CSS Online",
    metaDescription: "Minify CSS by removing comments and unnecessary whitespace. See the size saved and copy or download the result. Free and private.",
  },

  /* ——— Productivity ——— */
  {
    slug: "qr-code-generator",
    category: "productivity",
    name: "QR Code Generator",
    primaryKeyword: "qr code generator",
    description: "Turn a link, text, Wi-Fi login or email into a QR code you can download.",
    icon: "qr",
    status: "live",
    popular: true,
    featured: true,
    addedAt: added,
    keywords: ["qr", "qr code", "barcode", "scan", "wifi qr", "qr generator", "free qr code"],
    steps: ["Choose what the code should open.", "Enter the details and pick colors.", "Download it as PNG or SVG."],
    about: "Create QR codes for websites, plain text, Wi-Fi networks and email. The code contains your content directly, so it works forever — no tracking links and no expiry.",
    useCases: ["Put your website on a flyer, menu or business card.", "Let guests join your Wi-Fi without typing the password.", "Add a scannable link to a presentation."],
    updatedAt,
    related: ["password-generator", "marketing/utm-builder", "seo/slug-generator"],
    notes: ["Never expires", "PNG and SVG"],
    faqs: [
      { q: "Do these QR codes expire?", a: "No. They contain your content directly — there's no redirect service that could switch off." },
      { q: "Can I track scans?", a: "Not with the code itself. Add UTM tags to your link with the UTM builder to see visits in your analytics." },
      { q: "Which format should I download?", a: "SVG for print (it stays sharp at any size), PNG for screens and documents." },
    ],
    metaTitle: "QR Code Generator — Free QR Codes That Never Expire",
    metaDescription: "Create free QR codes for links, text, Wi-Fi and email. Custom colors, PNG and SVG download. No sign-up, no expiry, no tracking.",
  },
  {
    slug: "password-generator",
    category: "productivity",
    name: "Password Generator",
    primaryKeyword: "password generator",
    description: "Create strong, random passwords you can trust.",
    icon: "key",
    status: "live",
    popular: true,
    addedAt: added,
    keywords: ["password", "strong password", "random password", "secure password", "password generator"],
    steps: ["Choose the length and character types.", "See how strong it is.", "Copy the password."],
    about: "Generate strong passwords from your browser's cryptographically secure random generator. Choose the length and characters, avoid look-alike letters, and see an estimate of the strength.",
    useCases: ["Create a new password for an online account.", "Generate several passwords at once for a team.", "Make a Wi-Fi password that's hard to guess."],
    updatedAt,
    related: ["qr-code-generator", "developer/uuid-generator", "developer/hash-generator"],
    notes: ["Never sent or saved", "Cryptographically secure"],
    faqs: [
      { q: "Is it safe to generate passwords online?", a: "These are created in your browser and never sent or stored. Still, save them in a password manager rather than in plain text." },
      { q: "How long should a password be?", a: "At least 16 characters for important accounts. Longer is stronger." },
    ],
    metaTitle: "Password Generator — Strong Random Passwords",
    metaDescription: "Generate strong, random passwords with a cryptographically secure generator. Choose length and characters, avoid look-alikes. Never sent or saved.",
  },
  {
    slug: "list-randomizer",
    category: "productivity",
    name: "List Randomizer",
    primaryKeyword: "list randomizer",
    description: "Shuffle a list or pick random winners from it.",
    icon: "shuffle",
    status: "live",
    addedAt: added,
    keywords: ["randomize list", "random picker", "shuffle", "pick a winner", "name picker", "random name"],
    steps: ["Paste your list, one item per line.", "Shuffle it or choose how many winners.", "Randomize again as often as you like."],
    about: "Shuffle any list into a random order, or pick one or more random winners — fairly, using a secure random generator.",
    useCases: ["Pick a giveaway winner.", "Put names in a random order for presentations or turns.", "Split people into random groups."],
    updatedAt,
    related: ["random-number-generator", "text/sort-lines", "password-generator"],
    notes: ["Fair and random"],
    faqs: [{ q: "Is it really random?", a: "Yes — it uses your browser's cryptographically secure random generator, so every order and every winner is equally likely." }],
    metaTitle: "List Randomizer & Random Name Picker — Shuffle a List",
    metaDescription: "Shuffle lists and pick random winners fairly with a secure random generator. Great for giveaways, turns and groups. Free.",
  },
  {
    slug: "random-number-generator",
    category: "productivity",
    name: "Random Number Generator",
    primaryKeyword: "random number generator",
    description: "Generate random numbers in any range, with or without repeats.",
    icon: "dices",
    status: "live",
    addedAt: added,
    keywords: ["random number", "number generator", "rng", "random between", "dice"],
    steps: ["Set the lowest and highest number.", "Choose how many and whether they can repeat.", "Generate again any time."],
    about: "Get one or many random whole numbers between any two values, with the option of no repeats — like drawing numbered tickets from a hat.",
    useCases: ["Draw raffle or lottery-style numbers.", "Pick a random number for a game.", "Create sample data for testing."],
    updatedAt,
    related: ["list-randomizer", "password-generator", "developer/uuid-generator"],
    notes: ["Secure random"],
    faqs: [{ q: "Are the minimum and maximum included?", a: "Yes — both ends of the range can come up." }],
    metaTitle: "Random Number Generator — Pick Numbers in Any Range",
    metaDescription: "Generate random numbers between any two values, one or many, with or without repeats. Uses a secure random generator.",
  },

  /* ——— Calculators ——— */
  {
    slug: "percentage-calculator",
    category: "calculators",
    name: "Percentage Calculator",
    primaryKeyword: "percentage calculator",
    description: "Work out percentages, percentage change, increases and discounts.",
    icon: "percent",
    status: "live",
    popular: true,
    addedAt: added,
    keywords: ["percent", "percentage", "discount", "increase", "percentage change", "what percent"],
    steps: ["Pick the question you're answering.", "Enter the two numbers.", "Read the answer and the formula used."],
    about: "Four everyday percentage questions in one place: X% of a number, what percent one number is of another, the percentage change between two numbers, and increasing or decreasing by a percentage.",
    useCases: ["Work out a discount or sale price.", "Calculate a pay rise or price increase.", "Find the percentage change between two months."],
    updatedAt,
    related: ["age-calculator", "youtube/engagement-calculator", "youtube/revenue-calculator"],
    notes: ["Formula shown"],
    faqs: [{ q: "How is percentage change calculated?", a: "(new − old) ÷ old × 100. A change from 80 to 100 is +25%." }],
    metaTitle: "Percentage Calculator — Percent Of, Change & Discount",
    metaDescription: "Calculate X% of a number, what percent one number is of another, percentage change, and increases or discounts. Formulas shown.",
  },
  {
    slug: "age-calculator",
    category: "calculators",
    name: "Age Calculator",
    primaryKeyword: "age calculator",
    description: "Find an exact age in years, months and days — and the days to the next birthday.",
    icon: "calendar",
    status: "live",
    addedAt: added,
    keywords: ["age calculator", "how old am i", "date of birth", "age in days", "birthday"],
    steps: ["Enter the date of birth.", "Change the “age on” date if you need to.", "See the exact age and totals."],
    about: "Enter a date of birth to get an exact age in years, months and days, plus total months, weeks and days lived and a countdown to the next birthday. Check an age on any date, not just today.",
    useCases: ["Check someone's exact age for a form.", "Find how old someone was on a past date.", "Count down the days to a birthday."],
    updatedAt,
    related: ["percentage-calculator", "developer/timestamp-converter"],
    notes: ["Any date, not just today"],
    faqs: [{ q: "How are months counted?", a: "Full calendar months are counted first, then the remaining days, the same way people usually describe age." }],
    metaTitle: "Age Calculator — Exact Age in Years, Months and Days",
    metaDescription: "Calculate exact age from a date of birth in years, months and days, plus total weeks and days and the next birthday countdown.",
  },

  /* ——— SEO ——— */
  {
    slug: "meta-tag-generator",
    category: "seo",
    name: "Meta Tag Generator",
    primaryKeyword: "meta tag generator",
    description: "Create title, description and social sharing tags — with Google and social previews.",
    icon: "tags",
    status: "live",
    addedAt: added,
    keywords: ["meta tags", "title tag", "meta description", "open graph", "og tags", "twitter card", "seo"],
    steps: ["Enter your page title and description.", "Add the URL and share image.", "Copy the tags into your page's head."],
    about: "Create the HTML tags that control how a page appears in Google and when it's shared on social media — title, meta description, canonical link, Open Graph and X/Twitter card tags — with a live preview of both.",
    useCases: ["Write a title and description that won't be cut off in Google.", "Make links look good when shared on social media.", "Check tags before launching a new page."],
    updatedAt,
    related: ["slug-generator", "marketing/utm-builder", "youtube/description-generator"],
    notes: ["Google and social previews"],
    faqs: [
      { q: "How long should the title and description be?", a: "Around 50–60 characters for the title and 150–160 for the description, so they aren't cut off." },
      { q: "Will Google always show my description?", a: "Not always — Google may choose text from the page that better matches a search." },
    ],
    metaTitle: "Meta Tag Generator — Title, Description & Open Graph Tags",
    metaDescription: "Generate SEO meta tags, Open Graph and Twitter card tags with a live Google result and social share preview. Copy the HTML instantly.",
  },
  {
    slug: "slug-generator",
    category: "seo",
    name: "URL Slug Generator",
    primaryKeyword: "slug generator",
    description: "Turn titles into clean, readable URL slugs.",
    icon: "link",
    status: "live",
    addedAt: added,
    keywords: ["slug", "url slug", "permalink", "seo url", "slugify"],
    steps: ["Paste one or more titles.", "Choose hyphens or underscores and other options.", "Copy the slugs."],
    about: "A slug is the readable part of a web address, like /how-to-download-youtube-thumbnail. This tool turns titles into lowercase, hyphenated slugs with accents and symbols removed.",
    useCases: ["Create URLs for blog posts or product pages.", "Clean up file names for a website.", "Convert a batch of titles at once."],
    updatedAt,
    related: ["meta-tag-generator", "text/case-converter", "marketing/utm-builder"],
    notes: ["Batch conversion"],
    faqs: [{ q: "Hyphens or underscores?", a: "Hyphens. Google treats hyphens as spaces between words, which keeps slugs readable." }],
    metaTitle: "URL Slug Generator — Create SEO-Friendly Slugs",
    metaDescription: "Convert titles into clean, SEO-friendly URL slugs. Removes accents and symbols, optional stop-word removal, batch conversion. Free.",
  },

  /* ——— Marketing ——— */
  {
    slug: "utm-builder",
    category: "marketing",
    name: "UTM Link Builder",
    primaryKeyword: "utm builder",
    description: "Build trackable campaign links for Google Analytics in seconds.",
    icon: "link",
    status: "live",
    addedAt: added,
    keywords: ["utm", "campaign", "tracking link", "analytics", "utm builder", "google analytics"],
    steps: ["Paste the page you're linking to.", "Fill in source, medium and campaign.", "Copy your tracking link."],
    about: "UTM tags are extra bits added to a link so analytics tools like Google Analytics can tell which newsletter, ad or post sent a visitor. Fill in the fields and get a correctly formatted link.",
    useCases: ["Track clicks from a newsletter.", "Compare which social posts bring visitors.", "Tag links in ads or QR codes."],
    updatedAt,
    related: ["productivity/qr-code-generator", "seo/meta-tag-generator", "developer/url-encoder"],
    notes: ["Keeps existing parameters"],
    faqs: [
      { q: "Which fields are required?", a: "Source, medium and campaign. Term and content are optional." },
      { q: "Should I use UTM tags on internal links?", a: "No — only on links from other places. Internal UTM links reset how visits are attributed." },
    ],
    metaTitle: "UTM Builder — Create Campaign Tracking Links",
    metaDescription: "Build UTM tracking links for Google Analytics: source, medium, campaign, term and content. Consistent formatting, free and instant.",
  },
];
