import type { Tool } from "@/lib/catalog/types";

const category = "youtube";

export const youtubeTools: Tool[] = [
  // ——— Videos & links ———
  {
    slug: "thumbnail-downloader",
    category,
    name: "Thumbnail Downloader",
    title: "YouTube Thumbnail Downloader",
    description: "Download a YouTube video's thumbnail in seconds, in every available size.",
    icon: "image-down",
    status: "live",
    popular: true,
    featured: true,
    group: "links",
    addedAt: "2026-09-30",
    keywords: ["thumbnail", "download", "save", "image", "picture", "cover", "hd", "grabber"],
    steps: [
      "Copy the link of any YouTube video or Short.",
      "Paste it into the box and press Get thumbnails.",
      "Pick a size and press Download. That's it.",
    ],
    about: "Every YouTube video has a set of thumbnail images stored at public addresses on YouTube's image servers. This tool finds all of them from a single video link and lets you save each size as a JPG — the largest is 1280 × 720 when the creator uploaded one that big.",
    useCases: ["Save the cover image of your own video when you no longer have the original file.", "Study how successful thumbnails in your niche are laid out, before designing your own.", "Add a preview image to a blog post, newsletter or presentation that links to the video.", "Check which image YouTube is actually showing after you've changed a thumbnail."],
    updatedAt: "2026-09-30",
    related: ["video-id-finder", "thumbnail-analyzer", "metadata-extractor"],
    notes: ["Free", "No sign-up", "HD quality when available"],
    metaTitle: "YouTube Thumbnail Downloader — Download Thumbnails Online",
    metaDescription:
      "Download any YouTube video or Shorts thumbnail in HD, SD and smaller sizes. Paste the link, pick a size, download. Free, no sign-up.",
  },
  {
    slug: "video-id-finder",
    category,
    name: "Video ID Finder",
    title: "YouTube Video ID Finder",
    description: "Get the video ID from any YouTube link, plus clean watch and embed links.",
    icon: "hash",
    status: "live",
    popular: true,
    group: "links",
    addedAt: "2026-09-01",
    keywords: ["id", "video id", "extract", "url", "link", "embed url", "shorts"],
    steps: [
      "Paste one YouTube link — or many, one per line.",
      "The video ID appears instantly underneath.",
      "Copy the ID or the clean link with one click.",
    ],
    about: "A video ID is the 11-character code that identifies every YouTube video — it's the part after “v=” in a normal link, or after “youtu.be/” in a short one. This tool pulls the ID out of any YouTube link format and gives you clean watch and embed links.",
    useCases: ["Get the ID a plugin, website builder or app asks for when you add a video.", "Tidy up messy links that include playlist, timestamp or tracking parameters.", "Turn a Shorts or mobile link into a normal watch link.", "Extract IDs from a list of links in one go, for a spreadsheet or report."],
    updatedAt: "2026-09-30",
    related: ["channel-id-finder", "embed-generator", "thumbnail-downloader"],
    notes: ["Works instantly", "Nothing is sent anywhere"],
    metaTitle: "YouTube Video ID Finder — Extract ID from Any YouTube URL",
    metaDescription:
      "Paste a youtube.com/watch, youtu.be, Shorts or embed link to extract the 11-character video ID, the canonical watch URL and the embed URL. Copy with one click.",
  },
  {
    slug: "channel-id-finder",
    category,
    name: "Channel ID Finder",
    title: "YouTube Channel ID Finder",
    description: "Find the permanent ID of any YouTube channel from its link or @handle.",
    icon: "id-card",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    popular: true,
    group: "links",
    addedAt: "2026-09-30",
    keywords: ["channel id", "uc", "handle", "@", "channel url", "find id"],
    steps: [
      "Copy the channel's link, or just type its @handle.",
      "Paste it and press Find channel ID.",
      "Copy the ID (it always starts with UC).",
    ],
    about: "Every YouTube channel has a permanent ID that starts with “UC”. Names and @handles can change; the ID never does, which is why many apps and services ask for it. This tool looks up the ID from a channel link or @handle.",
    useCases: ["Connect a channel to an analytics tool, RSS reader or website widget that needs the channel ID.", "Keep a permanent reference to a channel in case it changes its name or handle.", "Build the channel's permanent link (youtube.com/channel/UC…)."],
    updatedAt: "2026-09-30",
    related: ["video-id-finder", "channel-audit", "metadata-extractor"],
    notes: ["Free", "Works with @handles"],
    metaTitle: "YouTube Channel ID Finder — Get Any Channel's UC ID",
    metaDescription:
      "Find the YouTube channel ID (UC…) for any channel from its URL or @handle. Copy the ID and the permanent channel link with one click.",
  },
  {
    slug: "embed-generator",
    category,
    name: "Embed Code Generator",
    title: "YouTube Embed Code Generator",
    description: "Create the code to put a YouTube video on your website, with the options you want.",
    icon: "code",
    status: "live",
    group: "links",
    addedAt: "2026-09-30",
    keywords: ["embed", "iframe", "website", "html", "autoplay", "start time", "responsive"],
    steps: [
      "Paste the link of the video you want to show.",
      "Choose options like start time, autoplay or no cookies.",
      "Copy the code and paste it into your website.",
    ],
    about: "An embed code is the small piece of HTML that shows a YouTube player on another website. This tool builds that code for you, with options like a start time, autoplay, looping and YouTube's privacy-enhanced mode, and shows a live preview.",
    useCases: ["Add a video to a website, blog post or online course page.", "Start a video at the exact moment that matters, such as a tutorial step.", "Use privacy-enhanced mode so YouTube doesn't set cookies until the visitor presses play.", "Make the player resize correctly on phones."],
    updatedAt: "2026-09-30",
    related: ["video-id-finder", "timestamp-generator", "thumbnail-downloader"],
    notes: ["Live preview", "Mobile-friendly code"],
    metaTitle: "YouTube Embed Code Generator — Responsive iframe with Options",
    metaDescription:
      "Generate YouTube embed code with start time, autoplay, mute, loop, captions and privacy-enhanced mode. Responsive by default, with a live preview.",
  },
  {
    slug: "metadata-extractor",
    category,
    name: "Video Metadata Extractor",
    title: "YouTube Video Metadata Extractor",
    description: "See a video's title, description, upload date, length, views and more — all in one place.",
    icon: "file-search",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    group: "links",
    addedAt: "2026-09-30",
    keywords: ["metadata", "details", "info", "title", "description", "upload date", "duration", "views", "likes"],
    steps: [
      "Paste the link of any public YouTube video.",
      "Press Get details.",
      "Copy any detail, or all of them at once.",
    ],
    about: "Metadata is the information attached to a video: title, description, upload date, length, view count, tags and more. This tool reads the public details YouTube shares for any public video and lays them out so you can copy exactly what you need.",
    useCases: ["Copy a video's full description, including links and chapters.", "Check the exact upload date and length of a video.", "Research how other creators write titles and descriptions in your niche.", "Collect video details for a report, citation or spreadsheet."],
    updatedAt: "2026-09-30",
    related: ["tag-extractor", "thumbnail-downloader", "video-comparison"],
    notes: ["Public data only"],
    metaTitle: "YouTube Video Metadata Extractor — Title, Description, Date & Stats",
    metaDescription:
      "Extract a YouTube video's title, description, channel, publish date, duration, views, likes and comments. Copy any field or everything at once.",
  },
  {
    slug: "tag-extractor",
    category,
    name: "Tag Extractor",
    title: "YouTube Tag Extractor",
    description: "See the hidden tags a YouTube video uses, and copy them in one click.",
    icon: "tags",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    popular: true,
    group: "links",
    addedAt: "2026-09-30",
    keywords: ["tags", "keywords", "hidden tags", "video tags", "seo"],
    steps: [
      "Paste the link of a public YouTube video.",
      "Press Get tags.",
      "Copy all tags, or pick the ones you want.",
    ],
    about: "Tags are optional keywords creators add when uploading. They aren't shown on the video page, but they're part of the video's public data. This tool shows the tags a public video uses and lets you copy them.",
    useCases: ["See which keywords similar videos in your niche use.", "Check that your own video's tags saved correctly.", "Spot common misspellings creators add as tags — the main thing YouTube says tags help with."],
    updatedAt: "2026-09-30",
    related: ["metadata-extractor", "title-generator", "video-id-finder"],
    notes: ["Public data only"],
    metaTitle: "YouTube Tag Extractor — See Any Video's Tags",
    metaDescription:
      "See the tags any public YouTube video uses. Copy all tags as a comma-separated list or pick individual ones. Free, no sign-up.",
  },
  {
    slug: "timestamp-generator",
    category,
    name: "Timestamp Generator",
    title: "YouTube Timestamp Generator",
    description: "Turn a list of chapters into timestamps that YouTube recognises.",
    icon: "list",
    status: "live",
    group: "writing",
    addedAt: "2026-09-01",
    keywords: ["timestamps", "chapters", "description", "00:00", "sections"],
    steps: [
      "Type your chapters with their start times, one per line.",
      "We fix the format and check YouTube's rules.",
      "Copy the result into your video description.",
    ],
    about: "Timestamps in a description turn into clickable chapters on YouTube's progress bar — but only if they follow YouTube's rules: start at 00:00, list at least three chapters, keep them in order and make each one at least 10 seconds long. This tool formats your notes and checks those rules for you.",
    useCases: ["Add chapters to a tutorial, podcast or long video so viewers can jump to the part they need.", "Fix chapter lists that YouTube isn't recognising.", "Turn rough notes from editing into a clean list for the description."],
    updatedAt: "2026-09-30",
    related: ["description-generator", "embed-generator", "video-id-finder"],
    notes: ["Checks YouTube's chapter rules"],
    metaTitle: "YouTube Timestamp Generator — Format Chapters for Your Description",
    metaDescription:
      "Generate correctly formatted YouTube chapter timestamps for your video description. Validates the 00:00 start, ascending order and minimum 10-second chapter length.",
  },
  {
    slug: "title-generator",
    category,
    name: "Title Generator",
    title: "YouTube Title Generator",
    description: "Get title ideas for your next video from a short description of it.",
    icon: "heading",
    status: "coming-soon",
    group: "writing",
    keywords: ["title", "ideas", "headline", "name video"],
  },
  {
    slug: "description-generator",
    category,
    name: "Description Generator",
    title: "YouTube Description Generator",
    description: "Build a clear, well-structured video description — summary, links, chapters and hashtags in the right order.",
    icon: "pen",
    status: "live",
    group: "writing",
    addedAt: "2026-09-30",
    keywords: ["description", "description template", "write description", "about section", "video description"],
    steps: [
      "Write one or two sentences about your video.",
      "Add your links, chapters and hashtags if you have them.",
      "Copy the finished description into YouTube Studio.",
    ],
    about:
      "A good description tells viewers — and YouTube — what the video is about in the first couple of lines, then gives links, chapters and hashtags in a tidy order. This tool builds that structure from a short form, shows how the first lines will look under a video, and checks YouTube's 5,000-character limit.",
    useCases: [
      "Write descriptions faster with a consistent structure for every upload.",
      "Make sure the most important sentence appears before YouTube's “…more” cut-off.",
      "Format chapters and hashtags correctly so YouTube recognises them.",
    ],
    updatedAt: "2026-09-30",
    related: ["timestamp-generator", "hashtag-generator", "seo-checker"],
    notes: ["Runs in your browser", "Checks the 5,000-character limit"],
    metaTitle: "YouTube Description Generator — Free Description Template",
    metaDescription:
      "Create a well-structured YouTube description: summary first, then links, chapters and hashtags. Preview the first lines and stay under the 5,000-character limit.",
  },
  {
    slug: "hashtag-generator",
    category,
    name: "Hashtag Generator",
    title: "YouTube Hashtag Generator",
    description: "Turn your keywords into correctly formatted YouTube hashtags, and check them against YouTube's rules.",
    icon: "hash",
    status: "live",
    group: "writing",
    addedAt: "2026-09-30",
    keywords: ["hashtags", "hashtag generator", "#", "shorts hashtags", "hashtag rules"],
    steps: [
      "Type your video's topic and a few keywords.",
      "Pick the hashtags you want to keep.",
      "Copy them into your title or description.",
    ],
    about:
      "Hashtags on YouTube link your video to a hashtag page and can appear above the title. YouTube has clear rules: no spaces, no more than 15 per video, and the first three from the description show above the title. This tool turns plain keywords into hashtags that follow those rules.",
    useCases: [
      "Format multi-word topics as hashtags without spaces or symbols.",
      "Pick the three hashtags that will show above your title.",
      "Avoid using more than 15, which makes YouTube ignore all of them.",
    ],
    updatedAt: "2026-09-30",
    related: ["description-generator", "tag-extractor", "seo-checker"],
    notes: ["Runs in your browser", "Follows YouTube's hashtag rules"],
    metaTitle: "YouTube Hashtag Generator — Format Hashtags the Right Way",
    metaDescription:
      "Turn keywords into YouTube hashtags that follow the rules: no spaces, up to 15 per video, and the first three shown above the title. Free and instant.",
  },
  {
    slug: "seo-checker",
    category,
    name: "SEO Checker",
    title: "YouTube SEO Checker",
    description: "Check a video's title, description, tags, hashtags and chapters against YouTube's own guidelines.",
    icon: "search",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    popular: true,
    group: "writing",
    addedAt: "2026-09-30",
    keywords: ["seo", "video seo", "seo checker", "optimize video", "seo score", "youtube seo"],
    steps: [
      "Paste the link of any public YouTube video.",
      "We read its public details and run each check.",
      "Fix anything marked to improve — each check explains why.",
    ],
    about:
      "YouTube search relies mostly on a video's title, description and how viewers respond. This tool reads a public video's details and checks the parts you control against YouTube's published guidelines — like title length, a clear first line in the description, working chapters and hashtag limits. It doesn't give a made-up score or promise rankings.",
    useCases: [
      "Review a video before or after publishing for easy fixes.",
      "Check that chapters and hashtags are formatted so YouTube recognises them.",
      "Compare how well-structured competing videos' titles and descriptions are.",
    ],
    updatedAt: "2026-09-30",
    related: ["metadata-extractor", "description-generator", "tag-extractor"],
    notes: ["Public data only", "Explains every check"],
    metaTitle: "YouTube SEO Checker — Review a Video's Title, Description & Tags",
    metaDescription:
      "Paste a YouTube link to check title length, description, chapters, hashtags, tags and captions against YouTube's guidelines. Clear explanations, no made-up scores.",
  },

  // ——— Thumbnails ———
  {
    slug: "thumbnail-generator",
    category,
    name: "Thumbnail Maker",
    title: "YouTube Thumbnail Maker",
    description: "Make a clean, readable thumbnail from your own image and text.",
    icon: "wand",
    status: "coming-soon",
    group: "thumbnails",
    keywords: ["thumbnail", "make", "create", "design", "generator"],
  },
  {
    slug: "thumbnail-analyzer",
    category,
    name: "Thumbnail Checker",
    title: "YouTube Thumbnail Checker",
    description: "Check your thumbnail's brightness, contrast, colours and text before you publish.",
    icon: "scan",
    status: "live",
    popular: true,
    group: "thumbnails",
    addedAt: "2026-09-01",
    keywords: ["thumbnail analyzer", "thumbnail checker", "contrast", "brightness", "colors", "test"],
    steps: [
      "Drop your thumbnail image into the box.",
      "We measure it right away, in your browser.",
      "Read the simple results and adjust if needed.",
    ],
    about: "This tool measures the visible qualities of a thumbnail image — brightness, contrast, colours, how much of it is text and where the main subject sits. Everything runs in your browser; the image is never uploaded.",
    useCases: ["Check a thumbnail isn't too dark or low-contrast before you publish.", "Compare two design options with the same measurements.", "Spot text that may be too small to read on a phone."],
    updatedAt: "2026-09-30",
    related: ["thumbnail-preview", "thumbnail-readability", "thumbnail-safe-zone"],
    notes: ["Your image never leaves your device"],
    metaTitle: "YouTube Thumbnail Analyzer — Measure Contrast, Color & Composition",
    metaDescription:
      "Free YouTube thumbnail analyzer: measure brightness, contrast, saturation, dominant colors, text area and composition. Runs privately in your browser.",
  },
  {
    slug: "thumbnail-preview",
    category,
    name: "Thumbnail Preview",
    title: "YouTube Thumbnail Preview",
    description: "See how your thumbnail will look on YouTube's home page, search and phones.",
    icon: "smartphone",
    status: "live",
    group: "thumbnails",
    addedAt: "2026-09-01",
    keywords: ["preview", "mockup", "mobile", "home feed", "dark mode"],
    steps: [
      "Drop in your thumbnail and type your title.",
      "Switch between home, search and mobile views.",
      "Try light and dark mode to compare.",
    ],
    about: "See your thumbnail and title as they'd appear on YouTube's home page, in search results, next to other videos and on a phone — in both light and dark mode — before you publish anything.",
    useCases: ["Check how a new thumbnail looks next to typical videos in a feed.", "Make sure the title isn't cut off at common lengths.", "Test the design in dark mode, which many viewers use."],
    updatedAt: "2026-09-30",
    related: ["thumbnail-readability", "thumbnail-analyzer", "thumbnail-safe-zone"],
    notes: ["Your image never leaves your device"],
    metaTitle: "YouTube Thumbnail Preview — Test on Home, Search & Mobile Layouts",
    metaDescription:
      "Preview your YouTube thumbnail in realistic home feed, search results, suggested video and small mobile layouts. Switch between light and dark interface and zoom levels.",
  },
  {
    slug: "thumbnail-readability",
    category,
    name: "Thumbnail Text Tester",
    title: "YouTube Thumbnail Text Tester",
    description: "Check whether the text on your thumbnail can still be read when it's small.",
    icon: "type",
    status: "live",
    group: "thumbnails",
    addedAt: "2026-09-01",
    keywords: ["readability", "text size", "small", "readable"],
    steps: [
      "Drop your thumbnail into the box.",
      "See it shrink from full size down to tiny.",
      "Make text bigger if it gets hard to read.",
    ],
    about: "Most people see thumbnails far smaller than they're designed. This tool shows your image at decreasing sizes and measures how much fine detail survives, so you can tell whether the words are still readable when it's tiny.",
    useCases: ["Check that thumbnail text is still readable on a phone.", "Decide between a short bold word and a longer phrase.", "Catch thin fonts and outlines that disappear when shrunk."],
    updatedAt: "2026-09-30",
    related: ["thumbnail-preview", "thumbnail-analyzer", "thumbnail-safe-zone"],
    notes: ["Your image never leaves your device"],
    metaTitle: "Thumbnail Readability Tester — Can Your Text Be Read at Small Sizes?",
    metaDescription:
      "Check if your YouTube thumbnail text survives downscaling. See it at 100% down to 10% and measure how much text detail is retained.",
  },
  {
    slug: "thumbnail-safe-zone",
    category,
    name: "Thumbnail Safe Zone",
    title: "YouTube Thumbnail Safe Zone Checker",
    description: "Make sure nothing important is hidden behind YouTube's time label.",
    icon: "frame",
    status: "live",
    group: "thumbnails",
    addedAt: "2026-09-01",
    keywords: ["safe zone", "grid", "margins", "timestamp badge", "template"],
    steps: [
      "Drop your thumbnail into the box.",
      "Turn on the grid and the time-label area.",
      "Move anything important out of the shaded parts.",
    ],
    about: "YouTube places the video length label in the bottom-right corner of every thumbnail. This tool overlays that area, a thirds grid and safe margins on your image so you can keep important text and faces clear of it.",
    useCases: ["Make sure the time label doesn't cover key text.", "Line up your subject using the rule of thirds.", "Keep important elements away from edges that get cropped in some layouts."],
    updatedAt: "2026-09-30",
    related: ["thumbnail-analyzer", "thumbnail-preview", "thumbnail-readability"],
    notes: ["Your image never leaves your device"],
    metaTitle: "YouTube Thumbnail Safe Zone Checker — Grid, Margins & Timestamp Area",
    metaDescription:
      "Interactive YouTube thumbnail safe-zone checker with a thirds grid, center lines, margins and the duration-badge area. Runs in your browser.",
  },

  // ——— Channel & video stats ———
  {
    slug: "channel-audit",
    category,
    name: "Channel Checker",
    title: "YouTube Channel Checker",
    description: "See any channel's subscribers, views, latest videos and how often it posts.",
    icon: "clipboard",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    popular: true,
    group: "stats",
    addedAt: "2026-09-01",
    keywords: ["channel audit", "channel stats", "subscribers", "analyzer", "channel checker"],
    steps: [
      "Paste a channel link or @handle.",
      "Press Check channel.",
      "Read the overview and scroll through recent videos.",
    ],
    about: "A quick public overview of any YouTube channel: subscribers, total views, video count, how often it uploads and how its recent videos performed. It uses YouTube's official public data — private analytics like watch time aren't available to anyone but the owner.",
    useCases: ["Get a snapshot of a channel before collaborating or sponsoring.", "Check your own channel's posting rhythm.", "Research channels in a niche you're thinking of joining."],
    updatedAt: "2026-09-30",
    related: ["channel-tracker", "competitor-tracker", "video-comparison"],
    notes: ["Public data only"],
    metaTitle: "YouTube Channel Audit Tool — Free Public Channel Analysis",
    metaDescription:
      "Audit any public YouTube channel: subscribers, total views, recent videos, upload frequency, average and median views, and views per day.",
  },
  {
    slug: "channel-tracker",
    category,
    name: "Channel Tracker",
    title: "YouTube Channel Tracker",
    description: "Follow a channel's subscribers and views over days, weeks and months.",
    icon: "line-chart",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    group: "stats",
    addedAt: "2026-09-01",
    keywords: ["tracker", "subscriber history", "growth", "over time"],
    steps: [
      "Paste a channel link and press Track.",
      "We save its numbers once a day.",
      "Come back any time to see the growth chart.",
    ],
    about: "YouTube only shows current totals, not history. This tool saves a channel's public numbers once a day so you can see real growth over the following weeks and months. History starts from the day you begin tracking.",
    useCases: ["Follow your own subscriber growth day by day.", "Watch how a channel grows after a viral video or a change in strategy.", "Keep a factual record of a partner channel's growth."],
    updatedAt: "2026-09-30",
    related: ["channel-audit", "competitor-tracker", "content-gap-finder"],
    notes: ["Real daily history", "Public data only"],
    metaTitle: "YouTube Channel Tracker — Track Subscribers & Views Over Time",
    metaDescription:
      "Track public YouTube channels over time with real daily snapshots of subscribers, views and videos, charted over 7, 30 and 90 days.",
  },
  {
    slug: "competitor-tracker",
    category,
    name: "Channel Comparison",
    title: "YouTube Channel Comparison",
    description: "Compare up to five channels side by side — size, uploads and recent views.",
    icon: "users",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    group: "stats",
    addedAt: "2026-09-01",
    keywords: ["competitor", "compare channels", "side by side"],
    steps: [
      "Add up to five channels by link or @handle.",
      "See them lined up side by side.",
      "Spot who posts more and whose videos get more views.",
    ],
    about: "Line up two to five channels and compare their public numbers side by side: size, how often they upload and how their recent videos perform.",
    useCases: ["See how your channel compares to similar ones.", "Understand which channels in a niche post most often.", "Shortlist channels for a collaboration or sponsorship."],
    updatedAt: "2026-09-30",
    related: ["content-gap-finder", "channel-tracker", "channel-audit"],
    notes: ["Public data only"],
    metaTitle: "YouTube Competitor Tracker — Compare Channels Side by Side",
    metaDescription:
      "Compare up to five YouTube channels side by side: subscribers, views, upload activity, average views, likes, comments and historical change.",
  },
  {
    slug: "video-comparison",
    category,
    name: "Video Comparison",
    title: "YouTube Video Comparison",
    description: "Put two or more videos side by side and compare views, likes and comments.",
    icon: "columns",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    group: "stats",
    addedAt: "2026-09-01",
    keywords: ["compare videos", "views", "likes", "engagement"],
    steps: [
      "Paste two or more video links.",
      "Press Compare.",
      "See which video is doing better, and by how much.",
    ],
    about: "Put two or more public videos next to each other and compare views, likes, comments, length and how fast each gathered views since publishing.",
    useCases: ["Compare two of your own videos to see which topic or format did better.", "Look at how a competitor's recent videos performed against each other.", "Check engagement rates rather than raw views."],
    updatedAt: "2026-09-30",
    related: ["engagement-calculator", "metadata-extractor", "comment-analyzer"],
    notes: ["Public data only"],
    metaTitle: "YouTube Video Comparison Tool — Compare Views, Likes & Engagement",
    metaDescription:
      "Compare two or more YouTube videos side by side. See views, likes, comments, duration, publish date, views per day and like and comment rates, with charts.",
  },
  {
    slug: "comment-analyzer",
    category,
    name: "Comment Summary",
    title: "YouTube Comment Summary",
    description: "Paste a video's comments to find the questions and requests viewers repeat most.",
    icon: "message",
    status: "live",
    group: "stats",
    addedAt: "2026-09-01",
    keywords: ["comments", "analyze", "questions", "requests", "sentiment"],
    steps: [
      "Copy the comments from a video and paste them in, one per line.",
      "Press Analyze comments.",
      "See repeated questions, requests and common topics.",
    ],
    about: "Reading hundreds of comments takes time. Paste a video's comments and this tool groups them to show the questions and requests people repeat most often, along with common topics. Everything is analysed in your browser.",
    useCases: ["Find follow-up video ideas from what viewers keep asking for.", "Spot confusion in a tutorial so you can add a pinned comment or correction.", "Get a quick sense of how viewers reacted to a video."],
    updatedAt: "2026-09-30",
    related: ["content-gap-finder", "video-comparison", "engagement-calculator"],
    notes: ["Runs in your browser", "Nothing is uploaded"],
    metaTitle: "YouTube Comment Analyzer — Find Questions, Requests & Topics",
    metaDescription:
      "Analyze YouTube comments to find frequently asked questions, repeated requests, common topics, frequent terms and estimated sentiment.",
  },
  {
    slug: "content-gap-finder",
    category,
    name: "Video Idea Finder",
    title: "YouTube Video Idea Finder",
    description: "Find topics similar channels make videos about that you haven't covered yet.",
    icon: "search",
    // Needs the YouTube Data API (a server). Coming back when the site has a backend.
    status: "coming-soon",
    group: "stats",
    addedAt: "2026-09-01",
    keywords: ["content gap", "topics", "ideas", "competitor topics"],
    steps: [
      "Paste your channel and a few similar channels.",
      "Press Find topics.",
      "See topics they cover often that you don't.",
    ],
    about: "Compare the recent video titles of your channel with a few similar channels, and see topics they cover repeatedly that you haven't covered yet. Every suggestion links back to the actual videos it came from.",
    useCases: ["Find video ideas grounded in what similar channels are publishing.", "Spot gaps in your own content plan.", "Research a niche before starting a channel."],
    updatedAt: "2026-09-30",
    related: ["competitor-tracker", "channel-audit", "comment-analyzer"],
    notes: ["Every topic links to real videos"],
    metaTitle: "YouTube Content Gap Finder — Topics Your Competitors Cover",
    metaDescription:
      "Discover topics that appear repeatedly in comparison channels' recent video titles but not on your channel. Every topic links back to the exact videos it was found in.",
  },

  // ——— Earnings calculators ———
  {
    slug: "revenue-calculator",
    category,
    name: "Earnings Calculator",
    title: "YouTube Earnings Calculator",
    description: "Estimate how much a channel could earn from its views.",
    icon: "dollar",
    status: "live",
    popular: true,
    group: "money",
    addedAt: "2026-09-01",
    keywords: ["revenue", "money", "earnings", "income", "how much does youtube pay"],
    steps: [
      "Enter the number of views per day.",
      "Pick an earnings rate (RPM), or keep the default.",
      "See daily, monthly and yearly estimates.",
    ],
    about: "Estimate how much a channel could earn from its views, using a simple formula: views ÷ 1,000 × RPM (revenue per 1,000 views). Results are estimates — real earnings depend on audience, country, topic and time of year.",
    useCases: ["Get a rough idea of earnings for a channel size you're working towards.", "Compare scenarios with different view counts or RPMs.", "Sanity-check income figures you read online."],
    updatedAt: "2026-09-30",
    related: ["rpm-calculator", "cpm-calculator", "watch-time-calculator"],
    notes: ["Formula shown"],
    metaTitle: "YouTube Revenue Calculator — Estimate Earnings from Views & RPM",
    metaDescription:
      "Estimate YouTube earnings with a transparent formula: views ÷ 1,000 × RPM. Get daily, weekly, monthly and yearly estimates in USD, GBP, CAD or AUD.",
  },
  {
    slug: "rpm-calculator",
    category,
    name: "RPM Calculator",
    title: "YouTube RPM Calculator",
    description: "Work out how much you earn for every 1,000 views.",
    icon: "gauge",
    status: "live",
    group: "money",
    addedAt: "2026-09-01",
    keywords: ["rpm", "revenue per mille", "per 1000 views"],
    steps: ["Enter what you earned.", "Enter how many views you had in the same period.", "See your RPM instantly."],
    about: "RPM is how much you earn for every 1,000 views after YouTube's share. Enter what you earned and how many views you had in the same period to calculate it, with the working shown.",
    useCases: ["Work out your real earnings per 1,000 views from YouTube Studio numbers.", "Compare RPM between months or between videos.", "Use your RPM in the earnings calculator for forecasts."],
    updatedAt: "2026-09-30",
    related: ["cpm-calculator", "revenue-calculator", "engagement-calculator"],
    notes: ["Formula shown"],
    metaTitle: "YouTube RPM Calculator — Revenue per 1,000 Views",
    metaDescription:
      "Calculate YouTube RPM (revenue per mille) from total revenue and views. RPM = revenue ÷ views × 1,000. Includes the full calculation and how RPM differs from CPM.",
  },
  {
    slug: "cpm-calculator",
    category,
    name: "CPM Calculator",
    title: "YouTube CPM Calculator",
    description: "Work out what advertisers pay for every 1,000 ad views on your videos.",
    icon: "badge-dollar",
    status: "live",
    group: "money",
    addedAt: "2026-09-01",
    keywords: ["cpm", "cost per mille", "ad rate", "cpm vs rpm"],
    steps: ["Enter your ad revenue.", "Enter your ad impressions.", "See your CPM and how it compares to RPM."],
    about: "CPM is what advertisers pay for 1,000 ad views on your videos, before YouTube's share. This tool calculates it from ad revenue and ad impressions, and explains why it's usually higher than RPM.",
    useCases: ["Understand advertiser demand for your content.", "See how ad prices change across the year.", "Explain the difference between CPM and RPM to a client or team."],
    updatedAt: "2026-09-30",
    related: ["rpm-calculator", "revenue-calculator", "watch-time-calculator"],
    notes: ["Formula shown"],
    metaTitle: "YouTube CPM Calculator — Cost per 1,000 Ad Impressions",
    metaDescription:
      "Calculate YouTube CPM from advertising revenue and monetized impressions. Learn the difference between CPM and RPM and why your RPM is usually lower than CPM.",
  },
  {
    slug: "watch-time-calculator",
    category,
    name: "Watch Time Calculator",
    title: "YouTube Watch Time Calculator",
    description: "Turn views and average watch length into total hours watched.",
    icon: "clock",
    status: "live",
    group: "money",
    addedAt: "2026-09-01",
    keywords: ["watch time", "watch hours", "4000 hours", "average view duration"],
    steps: ["Enter your number of views.", "Enter the average time people watch.", "See total minutes and hours watched."],
    about: "Multiply views by the average time people watch to get total watch time in minutes and hours — the figure used for thresholds like YouTube's 4,000 public watch hours.",
    useCases: ["Estimate total watch hours from a video's views and average view duration.", "Plan how many views you'd need to reach a watch-hour goal.", "Convert average view duration into total hours for a report."],
    updatedAt: "2026-09-30",
    related: ["engagement-calculator", "revenue-calculator", "rpm-calculator"],
    notes: ["Formula shown"],
    metaTitle: "YouTube Watch Time Calculator — Views × Average View Duration",
    metaDescription:
      "Calculate total YouTube watch time in minutes and hours from views and average view duration (HH:MM:SS). Useful for tracking progress toward watch-hour thresholds.",
  },
  {
    slug: "engagement-calculator",
    category,
    name: "Engagement Calculator",
    title: "YouTube Engagement Calculator",
    description: "See what share of viewers like and comment on a video.",
    icon: "heart",
    status: "live",
    group: "money",
    addedAt: "2026-09-01",
    keywords: ["engagement rate", "like rate", "comment rate"],
    steps: ["Enter views, likes and comments.", "See the like rate and comment rate.", "Compare with your other videos."],
    about: "Engagement rate shows what share of viewers liked or commented. This tool calculates like rate, comment rate and a combined rate from public counts, with the formulas shown.",
    useCases: ["Compare how engaging different videos are, regardless of view count.", "Report engagement to a sponsor using transparent formulas.", "Track whether a new format gets more interaction."],
    updatedAt: "2026-09-30",
    related: ["video-comparison", "watch-time-calculator", "comment-analyzer"],
    notes: ["Formula shown"],
    metaTitle: "YouTube Engagement Rate Calculator — Like & Comment Rate",
    metaDescription:
      "Calculate YouTube engagement ratios: like rate, comment rate, combined engagement and likes per comment. Transparent formulas using public view, like and comment counts.",
  },
];
