import {
  ArrowDownAZ,
  Binary,
  Blend,
  CalendarDays,
  Contrast,
  CopyMinus,
  Dices,
  Eraser,
  FileCode2,
  FilePlus2,
  FileStack,
  Fingerprint,
  GitCompare,
  ImagePlus,
  KeyRound,
  Layers,
  Lock,
  Minimize2,
  Paintbrush,
  Palette,
  Pilcrow,
  Pipette,
  Regex,
  Shuffle,
  SquareRoundCorner,
  SwatchBook,
  Timer,
  AtSign,
  BadgeDollarSign,
  Braces,
  Calculator,
  CaseSensitive,
  ChartLine,
  ClipboardList,
  Clock,
  Code,
  CodeXml,
  Columns2,
  Crop,
  DollarSign,
  Download,
  FileImage,
  FileSearch,
  FileText,
  Frame,
  Gauge,
  Hash,
  Heading,
  Heart,
  IdCard,
  Image,
  ImageDown,
  LetterText,
  Link,
  ListChecks,
  ListOrdered,
  Megaphone,
  Merge,
  MessageSquareText,
  PenLine,
  Percent,
  QrCode,
  Scaling,
  ScanSearch,
  Scissors,
  Search,
  Share2,
  Shrink,
  Smartphone,
  Sparkles,
  SquarePlay,
  Tags,
  TrendingUp,
  Type,
  Users,
  WandSparkles,
  RotateCw,
  FileDigit,
  Stamp,
  Signature,
  ArrowRightLeft,
  Scale,
  Landmark,
  House,
  PiggyBank,
  GraduationCap,
  Receipt,
  Flame,
  CalendarRange,
  AlarmClock,
  LoaderPinwheel,
  Keyboard,
  Ruler,
  Globe,
  Volume2,
  Italic,
  FileType,
  ScanText,
  Wallet,
  Car,
  TrendingDown,
  CreditCard,
  Target,
  TreePalm,
  ChartColumn,
  Building2,
  HousePlus,
  Tag,
  ChartPie,
  ReceiptText,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/catalog/lite";
import type { Tint } from "@/lib/catalog/types";
import { cn } from "@/lib/utils";

const icons: Record<IconName, LucideIcon> = {
  youtube: SquarePlay,
  image: Image,
  pdf: FileText,
  text: Type,
  social: Share2,
  developer: CodeXml,
  marketing: Megaphone,
  productivity: ListChecks,
  calculator: Calculator,
  seo: TrendingUp,
  ai: Sparkles,
  download: Download,
  "image-down": ImageDown,
  "id-card": IdCard,
  hash: Hash,
  code: Code,
  tags: Tags,
  "file-search": FileSearch,
  list: ListOrdered,
  scan: ScanSearch,
  smartphone: Smartphone,
  type: Type,
  frame: Frame,
  clipboard: ClipboardList,
  "line-chart": ChartLine,
  users: Users,
  columns: Columns2,
  message: MessageSquareText,
  search: Search,
  dollar: DollarSign,
  gauge: Gauge,
  "badge-dollar": BadgeDollarSign,
  clock: Clock,
  heart: Heart,
  heading: Heading,
  pen: PenLine,
  wand: WandSparkles,
  shrink: Shrink,
  scaling: Scaling,
  crop: Crop,
  merge: Merge,
  scissors: Scissors,
  "file-image": FileImage,
  letters: LetterText,
  case: CaseSensitive,
  braces: Braces,
  link: Link,
  qr: QrCode,
  percent: Percent,
  at: AtSign,
  binary: Binary,
  fingerprint: Fingerprint,
  key: KeyRound,
  regex: Regex,
  palette: Palette,
  pipette: Pipette,
  contrast: Contrast,
  blend: Blend,
  layers: Layers,
  paintbrush: Paintbrush,
  dices: Dices,
  shuffle: Shuffle,
  calendar: CalendarDays,
  eraser: Eraser,
  diff: GitCompare,
  sort: ArrowDownAZ,
  lock: Lock,
  timer: Timer,
  corner: SquareRoundCorner,
  "image-plus": ImagePlus,
  "file-plus": FilePlus2,
  "file-code": FileCode2,
  minimize: Minimize2,
  "copy-minus": CopyMinus,
  pilcrow: Pilcrow,
  swatch: SwatchBook,
  "file-stack": FileStack,
  "rotate": RotateCw,
  "file-digit": FileDigit,
  "stamp": Stamp,
  "signature": Signature,
  "convert": ArrowRightLeft,
  "scale": Scale,
  "bank": Landmark,
  "house": House,
  "piggy": PiggyBank,
  "graduation": GraduationCap,
  "receipt": Receipt,
  "flame": Flame,
  "calendar-range": CalendarRange,
  "alarm": AlarmClock,
  "pinwheel": LoaderPinwheel,
  "keyboard": Keyboard,
  "ruler": Ruler,
  "globe": Globe,
  "volume": Volume2,
  "italic": Italic,
  "file-type": FileType,
  "scan-text": ScanText,
  "wallet": Wallet,
  "car": Car,
  "trending-down": TrendingDown,
  "credit-card": CreditCard,
  "target": Target,
  "palm": TreePalm,
  "chart-column": ChartColumn,
  "building": Building2,
  "house-plus": HousePlus,
  "tag": Tag,
  "chart-pie": ChartPie,
  "receipt-text": ReceiptText,
};

export function ToolIcon({ name, className }: { name: IconName; className?: string }) {
  const Icon = icons[name];
  return <Icon aria-hidden className={cn("h-4 w-4", className)} strokeWidth={1.75} />;
}

/** Icon inside a soft rounded tile — used on cards and headers. */
export function ToolIconTile({
  name,
  size = "md",
  tone = "neutral",
  tint,
  className,
}: {
  name: IconName;
  size?: "sm" | "md" | "lg";
  /** "tint" uses the tool's own color wash; pass `tint` with it. */
  tone?: "neutral" | "accent" | "tint";
  tint?: Tint;
  className?: string;
}) {
  const box = size === "lg" ? "h-12 w-12 rounded-[14px]" : size === "sm" ? "h-8 w-8 rounded-[9px]" : "h-10 w-10 rounded-xl";
  const icon = size === "lg" ? "h-[22px] w-[22px]" : size === "sm" ? "h-4 w-4" : "h-[18px] w-[18px]";
  return (
    <span
      className={cn(
        "inline-flex shrink-0 items-center justify-center border transition-colors",
        tone === "accent" && "border-transparent bg-accent-soft text-accent",
        tone === "neutral" && "border-line bg-surface-2 text-ink-2",
        tone === "tint" && `tint-${tint ?? "mint"} border-[var(--tint-3)] bg-[var(--tint-2)] text-[var(--tint-ink)]`,
        box,
        className,
      )}
    >
      <ToolIcon name={name} className={icon} />
    </span>
  );
}
