/**
 * Writes src/lib/catalog/generated/lite-data.ts: the catalog with only the fields
 * the browser needs (names, links, icons, descriptions, keywords). Client code
 * imports "@/lib/catalog/lite", so FAQs, guides and page copy never ship as JS.
 *
 * Runs automatically before `dev` and `build`. `--check` fails if the file is stale.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { categories, tools } from "@/lib/catalog";
import type { Category, Tool } from "@/lib/catalog/types";

const TOOL_FIELDS = ["slug", "category", "name", "title", "primaryKeyword", "description", "icon", "status", "popular", "featured", "addedAt", "group", "keywords", "related", "backdrop", "access"] as const;
const CATEGORY_FIELDS = ["slug", "path", "name", "title", "description", "icon", "order", "showInNav", "groups", "backdrop"] as const;

function pick<T extends object>(obj: T, fields: readonly string[]) {
  return Object.fromEntries(fields.filter((f) => (obj as Record<string, unknown>)[f] !== undefined).map((f) => [f, (obj as Record<string, unknown>)[f]]));
}

const liteTools = tools.map((t) => pick(t, TOOL_FIELDS)) as Tool[];
// `intro` is required by the type but only used on the (server-rendered) category page.
const liteCategories = categories.map((c) => ({ ...pick(c, CATEGORY_FIELDS), intro: "" })) as Category[];

const out = `// Generated by scripts/gen-lite-catalog.ts from src/lib/catalog — do not edit.
import type { Category, Tool } from "@/lib/catalog/types";

export const liteCategories: Category[] = ${JSON.stringify(liteCategories)};

export const liteTools: Tool[] = ${JSON.stringify(liteTools)};
`;

const file = "src/lib/catalog/generated/lite-data.ts";
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(file, "utf8");
  } catch {}
  if (current !== out) {
    console.error(`${file} is out of date — run: npm run catalog:lite`);
    process.exit(1);
  }
} else {
  mkdirSync("src/lib/catalog/generated", { recursive: true });
  writeFileSync(file, out);
  console.log(`catalog:lite → ${file} (${liteTools.length} tools, ${(out.length / 1024).toFixed(1)} KB)`);
}
