/**
 * SEO checks for the catalog and blog, plus the keyword map.
 *
 *   npm run seo:check        → checks, then rewrites docs/seo/keyword-map.md
 *
 * Errors (exit 1): duplicate primary keywords (pages competing for one search),
 * duplicate titles, related links to tools that don't exist.
 * Warnings: titles over 60 characters, descriptions outside 110–160 characters,
 * a primary keyword missing from the title, fewer than two FAQs, no long-form help.
 */
import { writeFileSync } from "node:fs";
import { categories, liveTools, resolveTool, toolHref, toolTitle } from "@/lib/catalog";
import { sortedPosts, postHref } from "@/lib/blog/posts";
import { toolModules } from "@/tools/registry";
import { brandedTitle } from "@/lib/seo";

const errors: string[] = [];
const warnings: string[] = [];
const seenKeyword = new Map<string, string>();
const seenTitle = new Map<string, string>();

function claim(keyword: string, url: string) {
  const k = keyword.toLowerCase().trim();
  const other = seenKeyword.get(k);
  if (other) errors.push(`Primary keyword "${k}" is used by both ${other} and ${url}`);
  else seenKeyword.set(k, url);
}
function checkTitle(title: string, url: string) {
  if (title.length > 60) warnings.push(`${url}: title is ${title.length} characters (aim for ≤ 60): ${title}`);
  const other = seenTitle.get(title);
  if (other) errors.push(`Duplicate title on ${other} and ${url}`);
  else seenTitle.set(title, url);
}
function checkDescription(d: string, url: string) {
  if (d.length > 160 || d.length < 110) warnings.push(`${url}: description is ${d.length} characters (aim for 110–160)`);
}

type Row = { url: string; primary: string; secondary: string; intent: string; title: string; h1: string };
const rows: Row[] = [];

for (const t of liveTools) {
  const url = toolHref(t);
  const key = `${t.category}/${t.slug}`;
  const primary = t.primaryKeyword ?? toolTitle(t).toLowerCase();
  const title = t.metaTitle ?? `${toolTitle(t)} — Free Online Tool`;
  claim(primary, url);
  checkTitle(title, url);
  checkDescription(t.metaDescription ?? t.description, url);
  if (!title.toLowerCase().includes(primary.split(" ").slice(-2).join(" ")) && !title.toLowerCase().includes(primary))
    warnings.push(`${url}: title doesn't contain the primary keyword "${primary}"`);
  const pageModule = Boolean(toolModules[key]); // page modules supply their own FAQs and sections
  if (!pageModule && (t.faqs?.length ?? 0) < 2) warnings.push(`${url}: only ${t.faqs?.length ?? 0} FAQ(s)`);
  if (!pageModule && !t.guide?.length) warnings.push(`${url}: no long-form help (add it in src/lib/catalog/tools/help.ts)`);
  for (const r of t.related ?? []) {
    const rt = resolveTool(r, t.category);
    // Coming-soon tools are skipped by relatedTools() and start linking automatically once live.
    if (!rt) errors.push(`${url}: related tool "${r}" doesn't exist`);
  }
  rows.push({ url, primary, secondary: (t.keywords ?? []).filter((k) => k.toLowerCase() !== primary).slice(0, 5).join(", "), intent: "Use a tool", title: brandedTitle(title), h1: toolTitle(t) });
}

for (const p of sortedPosts) {
  const url = postHref(p);
  claim(p.primaryKeyword, url);
  const title = p.metaTitle ?? p.title;
  checkTitle(title, url);
  checkDescription(p.description, url);
  rows.push({ url, primary: p.primaryKeyword, secondary: (p.keywords ?? []).slice(0, 5).join(", "), intent: "Learn (guide)", title: brandedTitle(title), h1: p.title });
}

for (const c of categories.filter((c) => liveTools.some((t) => t.category === c.slug))) {
  const url = `/${c.path}`;
  const title = c.metaTitle ?? `Free ${c.title} Online`;
  checkTitle(title, url);
  rows.push({ url, primary: `${c.title.toLowerCase()}`, secondary: "", intent: "Browse a category", title: brandedTitle(title), h1: c.title });
}

const esc = (s: string) => s.replace(/\|/g, "\\|");
const byCategory = (url: string) => url.split("/")[1];
const md = [
  "# Keyword map",
  "",
  "Generated by `npm run seo:check` from the catalog (`src/lib/catalog`) and blog (`src/lib/blog/posts.ts`). Don't edit by hand — change the catalog and re-run.",
  "",
  "Each page targets one primary search phrase; no two pages share one. Tools answer “do it now” searches, guides answer “how/why” searches and link to the tool.",
  "",
  "| URL | Primary keyword | Secondary keywords | Intent | Title (as rendered) |",
  "| --- | --- | --- | --- | --- |",
  ...rows
    .sort((a, b) => byCategory(a.url).localeCompare(byCategory(b.url)) || a.url.localeCompare(b.url))
    .map((r) => `| ${r.url} | ${esc(r.primary)} | ${esc(r.secondary)} | ${r.intent} | ${esc(r.title)} |`),
  "",
].join("\n");
writeFileSync("docs/seo/keyword-map.md", md);

for (const w of warnings) console.warn(`warn  ${w}`);
for (const e of errors) console.error(`error ${e}`);
console.log(`\n${rows.length} pages mapped → docs/seo/keyword-map.md · ${errors.length} error(s), ${warnings.length} warning(s)`);
if (errors.length) process.exit(1);
