import type { Category } from "@/lib/catalog/types";

/**
 * Every category on the site. Adding one here adds it to the header menu,
 * mobile menu, footer, homepage, /tools and the sitemap. A category with no
 * live tools yet is shown as "Coming soon".
 */
export const categories: Category[] = [
  {
    slug: "youtube",
    path: "youtube-tools",
    name: "YouTube",
    title: "YouTube Tools",
    description: "Tools for working with YouTube videos, channels and thumbnails.",
    intro: "Useful YouTube tools that make common tasks faster and easier. Paste a link, get what you need.",
    icon: "youtube",
    order: 1,
    backdrop: { pattern: "strings", tint: "mint" },
    faqs: [
      { q: "Are these YouTube tools free?", a: "Yes. Every tool is free to use with no sign-up, and they all run in your browser." },
      { q: "Do I need to connect my YouTube account?", a: "No. The tools only use public information — the same details anyone can see on YouTube — or work entirely in your browser. We never ask you to sign in with Google." },
      { q: "Can I download YouTube videos here?", a: "No. Downloading videos goes against YouTube's Terms of Service, so we don't offer it. You can download thumbnails, which are public images, and copy public details like titles, descriptions and tags." },
      { q: "Where does the data come from?", a: "Thumbnail images come straight from YouTube's public image servers. Everything else is worked out in your browser from what you enter. Tools that need YouTube's data service — like channel stats — are coming soon." },
      { q: "Are you affiliated with YouTube?", a: "No. This site is independent and isn't affiliated with or endorsed by YouTube or Google." },
    ],
    groups: [
      { id: "links", name: "Videos & links" },
      { id: "thumbnails", name: "Thumbnails" },
      { id: "writing", name: "Titles, descriptions & SEO" },
      { id: "stats", name: "Channel & video stats" },
      { id: "money", name: "Earnings calculators" },
    ],
    metaTitle: "Free YouTube Tools — Thumbnails, IDs, Stats & Calculators",
    metaDescription:
      "Free, simple YouTube tools: download thumbnails, find video and channel IDs, create embed codes, check video stats and estimate earnings. No sign-up.",
  },
  {
    slug: "text",
    path: "text-tools",
    name: "Text",
    title: "Text Tools",
    description: "Useful tools for writing, editing and analyzing text.",
    intro: "Count words, change letter case and tidy up text — right in your browser.",
    icon: "text",
    order: 2,
    faqs: [
      { q: "Is my text uploaded anywhere?", a: "No. The text tools run entirely in your browser, so what you type or paste never leaves your device." },
      { q: "Is there a length limit?", a: "No practical limit. You can paste whole essays, reports or scripts." },
    ],
  },
  {
    slug: "image",
    path: "image-tools",
    name: "Images",
    title: "Image Tools",
    description: "Resize, compress and transform images easily.",
    intro: "Make images smaller, change their size or format, and get them ready to share.",
    icon: "image",
    order: 3,
    faqs: [
      { q: "Are my images uploaded?", a: "No. Every image tool works inside your browser using the Canvas API. Your photos never leave your device." },
      { q: "Which formats are supported?", a: "JPG, PNG and WebP everywhere, plus GIF, BMP and AVIF as inputs where your browser can open them. SVG files are handled by the SVG to PNG tool." },
      { q: "Will compressing an image make it blurry?", a: "At sensible settings (around 70–85% quality) most photos look the same while the file gets much smaller. The compressor shows the result before you download." },
    ],
  },
  {
    slug: "pdf",
    path: "pdf-tools",
    name: "PDFs",
    title: "PDF Tools",
    description: "Simple tools for managing PDF files.",
    intro: "Merge, split and shrink PDF files without installing anything.",
    icon: "pdf",
    order: 4,
    faqs: [
      { q: "Are my PDFs uploaded to a server?", a: "No. Merging, splitting and creating PDFs all happen in your browser. Your documents stay on your device." },
      { q: "Can I edit password-protected PDFs?", a: "Not yet. Remove the password in your PDF reader first, then use the tool." },
      { q: "Why is PDF compression not available?", a: "Shrinking PDFs properly means re-encoding the images inside them, which needs server-side processing. It's coming later." },
    ],
  },
  {
    slug: "social-media",
    path: "social-media-tools",
    name: "Social Media",
    title: "Social Media Tools",
    description: "Helpers for posts, captions, bios and profiles.",
    intro: "Get your posts, captions and profiles ready for any social network.",
    icon: "social",
    order: 5,
  },
  {
    slug: "developer",
    path: "developer-tools",
    name: "Developer",
    title: "Developer Tools",
    description: "Format, convert and check code and data.",
    intro: "Quick helpers for formatting, encoding and checking code and data.",
    icon: "developer",
    order: 6,
    faqs: [
      { q: "Is my data sent anywhere?", a: "No. Formatting, encoding, hashing and decoding all run in your browser, so it's safe to paste config files and tokens." },
      { q: "Do the hash tools support MD5?", a: "Yes — MD5, SHA-1, SHA-256, SHA-384 and SHA-512. MD5 and SHA-1 are fine for checksums but not for storing passwords." },
    ],
  },
  {
    slug: "marketing",
    path: "marketing-tools",
    name: "Marketing",
    title: "Marketing Tools",
    description: "Build links, codes and campaigns in seconds.",
    intro: "Small tools that save time on everyday marketing tasks.",
    icon: "marketing",
    order: 7,
    faqs: [
      { q: "Do UTM links affect SEO?", a: "No. UTM tags only help your analytics tool group visits. Use them on links you share, not on internal links between your own pages." },
    ],
  },
  {
    slug: "productivity",
    path: "productivity-tools",
    name: "Productivity",
    title: "Productivity Tools",
    description: "Everyday helpers that save you a few minutes.",
    intro: "Handy tools for everyday tasks at work and at home.",
    icon: "productivity",
    order: 8,
    faqs: [
      { q: "How random are the results?", a: "Passwords, lists and numbers use your browser's cryptographically secure random generator (crypto.getRandomValues), not Math.random." },
      { q: "Do QR codes expire?", a: "No. The QR codes here contain your content directly, so they keep working forever and don't depend on our site." },
    ],
  },
  {
    slug: "calculators",
    path: "calculators",
    name: "Calculators",
    title: "Calculators",
    description: "Quick answers for percentages, dates and more.",
    intro: "Simple calculators with the working shown, so you can trust the answer.",
    icon: "calculator",
    order: 9,
    faqs: [
      { q: "Do the calculators show how they got the answer?", a: "Yes — each one shows the formula it used, so you can check it yourself." },
    ],
  },
  {
    slug: "seo",
    path: "seo-tools",
    name: "SEO",
    title: "SEO Tools",
    description: "Check and improve how pages appear in search.",
    intro: "See how your pages look in search results and fix the basics.",
    icon: "seo",
    order: 10,
    faqs: [
      { q: "Will these tools improve my Google ranking?", a: "They help you get the basics right — clear titles, descriptions and URLs. Rankings depend mostly on how useful your content is." },
    ],
  },
  {
    slug: "color",
    path: "color-tools",
    name: "Colour",
    title: "Colour Tools",
    description: "Convert, check and build colour palettes.",
    intro: "Convert colour codes, check that text is readable, and turn one colour into a full palette.",
    icon: "palette",
    order: 11,
    faqs: [
      { q: "What colour formats are supported?", a: "HEX, RGB, HSL, HSV and CMYK, plus CSS colour names like “teal” as input." },
      { q: "What contrast ratio do I need?", a: "WCAG AA asks for at least 4.5:1 for normal text and 3:1 for large text. The contrast checker tests all the common levels." },
    ],
    metaTitle: "Free Colour Tools — Converter, Contrast Checker & Palettes",
    metaDescription: "Convert HEX, RGB and HSL colours, check WCAG contrast for readable text, and generate tints and shades. Free and instant.",
  },
  {
    slug: "css",
    path: "css-tools",
    name: "CSS",
    title: "CSS Tools",
    description: "Generate and tidy up CSS with live previews.",
    intro: "Build gradients, shadows and rounded corners visually, then copy clean CSS. Or shrink your stylesheets.",
    icon: "paintbrush",
    order: 12,
    faqs: [
      { q: "Does the generated CSS work in all browsers?", a: "Yes. Gradients, box shadows and border radius are supported by every modern browser without prefixes." },
    ],
    metaTitle: "Free CSS Tools — Gradient, Box Shadow & Border Radius Generators",
    metaDescription: "Create CSS gradients, box shadows and border radius visually with a live preview, and minify CSS. Copy the code in one click.",
  },
];
