/**
 * Every article's metadata. Client-safe (no article text), so site search can
 * index articles without shipping them. Article bodies live in
 * src/content/blog/<slug>.tsx and are registered in src/content/blog/index.ts.
 *
 * One article per primary keyword — if two articles would answer the same
 * query, merge them instead.
 */
import type { PostMeta } from "@/lib/blog/types";

export const posts: PostMeta[] = [
  {
    slug: "how-to-download-youtube-thumbnail",
    title: "YouTube Thumbnail Downloader: How to Download YouTube Thumbnails in Full Size",
    metaTitle: "How to Download a YouTube Thumbnail in Full Size (HD)",
    description:
      "Save any YouTube thumbnail in the largest size available, on a computer or phone. Every size YouTube makes, how the URLs work, and fixes for common problems.",
    cluster: "youtube",
    kind: "how-to",
    published: "2026-09-30",
    authorId: "editorial",
    readingMinutes: 9,
    primaryKeyword: "how to download youtube thumbnail",
    keywords: [
      "download youtube thumbnail",
      "youtube thumbnail download",
      "youtube thumbnail url",
      "get youtube thumbnail",
      "save youtube thumbnail",
      "youtube thumbnail image",
      "youtube thumbnail size",
      "download thumbnail from youtube video",
    ],
    relatedTools: ["youtube/thumbnail-downloader", "youtube/video-id-finder", "youtube/thumbnail-analyzer", "youtube/thumbnail-preview"],
    relatedPosts: ["thumbnail-readability-at-small-sizes", "public-youtube-metrics-guide"],
  },
  {
    slug: "public-youtube-metrics-guide",
    title: "Which YouTube Metrics Are Public — and What You Can Learn From Them",
    metaTitle: "Which YouTube Metrics Are Public? What They Tell You",
    description:
      "Subscribers, views, likes and comments are public. Click-through rate, impressions and watch time are not. What that public data can tell you about a channel.",
    cluster: "youtube",
    kind: "explainer",
    published: "2026-09-15",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "public youtube metrics",
    keywords: ["youtube public stats", "see youtube channel stats", "youtube analytics public"],
    relatedTools: ["youtube/channel-audit", "youtube/competitor-tracker", "youtube/video-comparison", "youtube/metadata-extractor"],
  },
  {
    slug: "thumbnail-readability-at-small-sizes",
    title: "How to Check Whether a Thumbnail Still Reads at Small Sizes",
    description:
      "Most thumbnails are seen far smaller than they're designed. A practical, repeatable way to test text and subject legibility before you publish.",
    cluster: "youtube",
    kind: "guide",
    published: "2026-09-08",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "youtube thumbnail readability",
    keywords: ["thumbnail text size", "thumbnail mobile", "readable thumbnail"],
    relatedTools: ["youtube/thumbnail-readability", "youtube/thumbnail-preview", "youtube/thumbnail-analyzer", "youtube/thumbnail-safe-zone"],
    relatedPosts: ["how-to-download-youtube-thumbnail"],
  },
  {
    slug: "rpm-vs-cpm-explained",
    title: "RPM vs CPM on YouTube: What Each Number Actually Measures",
    description:
      "CPM is what advertisers pay per 1,000 ad impressions. RPM is what you earn per 1,000 views. Why they differ, and how to calculate both.",
    cluster: "youtube",
    kind: "comparison",
    published: "2026-09-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "youtube rpm vs cpm",
    keywords: ["what is rpm on youtube", "what is cpm on youtube", "rpm vs cpm"],
    relatedTools: ["youtube/rpm-calculator", "youtube/cpm-calculator", "youtube/revenue-calculator"],
  },
  {
    slug: "how-to-open-heic-files-on-windows",
    title: "HEIC Files Won't Open on Windows? 4 Ways to Open or Convert iPhone Photos",
    metaTitle: "How to Open HEIC Files on Windows (4 Easy Fixes)",
    description:
      "iPhone photos (.heic) won't open on your PC? Convert them to JPG in a minute, teach Windows to read them, or change one iPhone setting for good.",
    cluster: "image",
    kind: "how-to",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "how to open heic files on windows",
    keywords: ["heic won't open windows", "open heic on windows 11", "iphone photos heic windows", "heif image extensions", "convert heic to jpg windows", "iphone transfer automatic", "most compatible camera format"],
    relatedTools: ["image/heic-to-jpg", "image/compressor", "image/resizer"],
    relatedPosts: ["reduce-image-size-to-100kb"],
  },
  {
    slug: "reduce-image-size-to-100kb",
    title: "How to Reduce a Photo to Under 100 KB (Without Making It Blurry)",
    metaTitle: "How to Reduce Image Size to 100 KB Without Losing Quality",
    description:
      "Get a photo under 100 KB for an online form and keep it sharp: the two settings that matter, sizes for common limits, and why a file stays too big.",
    cluster: "image",
    kind: "how-to",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "reduce image size to 100kb",
    keywords: ["compress image to 100kb", "reduce photo size in kb", "compress jpg to 50kb", "photo size for online form", "image under 100kb", "reduce image size without losing quality", "signature 20kb"],
    relatedTools: ["image/compressor", "image/resizer", "image/cropper", "image/heic-to-jpg"],
    relatedPosts: ["how-to-open-heic-files-on-windows"],
  },
  {
    slug: "sign-pdf-without-printing",
    title: "How to Sign a PDF Without Printing It — on a Computer or Phone",
    metaTitle: "How to Sign a PDF Without Printing (Free, Any Device)",
    description:
      "Sign a PDF on screen in a couple of minutes — in your browser, Adobe Reader, Preview or iPhone Markup — and know when a signature like this is legally enough.",
    cluster: "pdf",
    kind: "how-to",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how to sign a pdf without printing",
    keywords: ["sign pdf on phone", "electronic signature pdf free", "add signature to pdf", "is electronic signature legal", "electronic vs digital signature", "sign pdf on iphone", "sign pdf on mac"],
    relatedTools: ["pdf/sign", "pdf/merge", "pdf/pdf-to-jpg"],
  },
  {
    slug: "common-json-errors",
    title: "JSON Errors Explained: What Each Message Means and How to Fix It",
    metaTitle: "Common JSON Errors and How to Fix Them",
    description:
      "Trailing commas, single quotes, “Unexpected token <”, NaN from Python: real JavaScript and Python error messages, what causes each and how to fix it.",
    cluster: "developer",
    kind: "guide",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "common json errors",
    keywords: ["unexpected token in json", "unexpected end of json input", "json trailing comma", "expecting property name enclosed in double quotes", "json parse error", "invalid json", "json comments"],
    relatedTools: ["developer/json-formatter", "text/text-diff"],
  },
  {
    slug: "wifi-qr-code",
    title: "How to Make a Wi-Fi QR Code (and Why Some Don't Connect)",
    metaTitle: "How to Make a Wi-Fi QR Code That Actually Works",
    description:
      "Let guests join your Wi-Fi with one scan: how to make the code, why some scan but won't connect, and how to print one that works on every phone.",
    cluster: "productivity",
    kind: "how-to",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "how to make a wifi qr code",
    keywords: ["wifi qr code", "qr code for wifi password", "share wifi qr code", "wifi qr code not working", "hidden network qr code", "wifi qr code format"],
    relatedTools: ["productivity/qr-code-generator", "productivity/password-generator"],
  },
  {
    slug: "how-to-calculate-percentage-change",
    title: "How to Calculate Percentage Change (and the Mistakes Everyone Makes)",
    metaTitle: "How to Calculate Percentage Change — With Examples",
    description:
      "The percentage change formula with worked examples, plus percent vs percentage points, reversing a discount, negative values and multi-year growth.",
    cluster: "calculators",
    kind: "explainer",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how to calculate percentage change",
    keywords: ["percentage change formula", "percentage increase", "percentage decrease", "percent vs percentage points", "percentage difference", "find original price after discount", "percentage change excel"],
    relatedTools: ["calculators/percentage-calculator", "finance/discount-calculator", "finance/compound-interest-calculator"],
  },
  {
    slug: "how-much-is-20-an-hour-a-year",
    title: "How Much Is $20 an Hour a Year? Hourly to Salary Table ($15–$50)",
    metaTitle: "$20 an Hour Is How Much a Year? Hourly to Salary Table",
    description: "$20 an hour is $41,600 a year at 40 hours a week. A full hourly-to-salary table from $15 to $50, plus the cases where the usual math is wrong.",
    cluster: "finance",
    kind: "guide",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how much is 20 an hour a year",
    keywords: ["20 an hour is how much a year", "25 an hour is how much a year", "hourly to annual salary", "2080 hours", "hourly to yearly"],
    relatedTools: ["finance/salary-converter"],
    relatedPosts: ["how-to-calculate-pro-rata-salary"],
  },
  {
    slug: "how-to-calculate-pro-rata-salary",
    title: "How to Calculate a Pro-Rata Salary (and Holiday) for Part-Time Work",
    metaTitle: "How to Calculate Pro Rata Salary and Holiday (UK)",
    description: "What “£30,000 pro rata” really pays for part-time hours, how to work it out in seconds, and how part-time holiday entitlement is calculated.",
    cluster: "finance",
    kind: "how-to",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how to calculate pro rata salary",
    keywords: ["pro rata salary", "pro rata meaning", "part time salary", "pro rata holiday", "part time holiday entitlement"],
    relatedTools: ["finance/salary-converter"],
    relatedPosts: ["how-much-is-20-an-hour-a-year"],
  },
  {
    slug: "28-36-rule",
    title: "The 28/36 Rule: How Much House You Can Really Afford",
    metaTitle: "The 28/36 Rule: How Much House Can You Afford?",
    description: "The 28/36 rule lenders use to size your mortgage, with a worked example, how other debts shrink your budget, and how UK and Australian lenders differ.",
    cluster: "finance",
    kind: "explainer",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "28/36 rule",
    keywords: ["28 36 rule mortgage", "debt to income ratio", "how much mortgage can i afford", "front end ratio", "back end ratio"],
    relatedTools: ["finance/mortgage-affordability-calculator", "finance/mortgage-calculator"],
    relatedPosts: ["15-vs-30-year-mortgage", "is-it-better-to-rent-or-buy"],
  },
  {
    slug: "15-vs-30-year-mortgage",
    title: "15 vs 30-Year Mortgage: Which One Actually Saves You More?",
    metaTitle: "15 vs 30-Year Mortgage: Payments, Interest and Pros",
    description: "A 15-year mortgage saves a fortune in interest; a 30-year one gives breathing room. The real numbers, and a third option most comparisons miss.",
    cluster: "finance",
    kind: "comparison",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "15 vs 30 year mortgage",
    keywords: ["15 year mortgage", "30 year mortgage", "pay off mortgage early", "mortgage overpayment", "mortgage term"],
    relatedTools: ["finance/mortgage-calculator", "finance/mortgage-affordability-calculator"],
    relatedPosts: ["28-36-rule", "is-it-better-to-rent-or-buy"],
  },
  {
    slug: "is-it-better-to-rent-or-buy",
    title: "Is It Better to Rent or Buy a Home? An Honest Comparison",
    metaTitle: "Is It Better to Rent or Buy? How to Decide With Numbers",
    description: "Why “rent is dead money” is only half true, a worked rent vs buy example with the break-even year, and the price-to-rent check that settles it fast.",
    cluster: "finance",
    kind: "comparison",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "is it better to rent or buy",
    keywords: ["rent vs buy", "should i rent or buy", "price to rent ratio", "is renting a waste of money", "buying vs renting"],
    relatedTools: ["finance/rent-vs-buy-calculator", "finance/mortgage-affordability-calculator"],
    relatedPosts: ["28-36-rule", "what-is-a-good-rental-yield"],
  },
  {
    slug: "what-is-a-good-rental-yield",
    title: "What Is a Good Rental Yield? Gross vs Net, Explained",
    metaTitle: "What Is a Good Rental Yield? Gross vs Net Explained",
    description: "How to calculate gross and net rental yield, the costs that turn 6% into 4%, and how to judge whether a buy-to-let's yield is actually good.",
    cluster: "finance",
    kind: "explainer",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "what is a good rental yield",
    keywords: ["rental yield", "how to calculate rental yield", "net rental yield", "buy to let yield", "gross yield"],
    relatedTools: ["finance/rental-yield-calculator", "finance/roi-calculator"],
    relatedPosts: ["is-it-better-to-rent-or-buy", "how-to-calculate-roi"],
  },
  {
    slug: "how-long-should-a-car-loan-be",
    title: "How Long Should a Car Loan Be? 48 vs 60 vs 72 Months",
    metaTitle: "How Long Should a Car Loan Be? 48, 60, 72 or 84 Months",
    description: "What each car loan length really costs, why 72 and 84-month loans leave you underwater, and how to pick a term that fits.",
    cluster: "finance",
    kind: "guide",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how long should a car loan be",
    keywords: ["car loan term", "72 month car loan", "84 month car loan", "20/4/10 rule", "average car loan length", "negative equity car"],
    relatedTools: ["finance/auto-loan-calculator"],
    relatedPosts: ["debt-snowball-vs-avalanche", "how-is-emi-calculated"],
  },
  {
    slug: "debt-snowball-vs-avalanche",
    title: "Debt Snowball vs Avalanche: Which Pays Off Debt Faster?",
    metaTitle: "Debt Snowball vs Avalanche: Which Method Should You Use?",
    description: "Avalanche saves the most interest; snowball keeps you going. A real comparison, when they're identical, and what matters more than either.",
    cluster: "finance",
    kind: "comparison",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "debt snowball vs avalanche",
    keywords: ["debt snowball", "debt avalanche", "how to pay off debt", "pay off credit cards", "debt payoff method"],
    relatedTools: ["finance/debt-payoff-calculator", "finance/credit-card-payoff-calculator"],
    relatedPosts: ["how-credit-card-interest-is-calculated"],
  },
  {
    slug: "how-credit-card-interest-is-calculated",
    title: "How Credit Card Interest Is Calculated (and How to Pay Less)",
    metaTitle: "How Credit Card Interest Is Calculated — With Examples",
    description: "Credit card interest is charged daily on your average balance. How it works, how you lose the grace period, and why minimum payments barely help.",
    cluster: "finance",
    kind: "explainer",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how is credit card interest calculated",
    keywords: ["credit card interest", "daily periodic rate", "average daily balance", "grace period", "minimum payment"],
    relatedTools: ["finance/credit-card-payoff-calculator", "finance/debt-payoff-calculator"],
    relatedPosts: ["debt-snowball-vs-avalanche"],
  },
  {
    slug: "how-is-emi-calculated",
    title: "How Is EMI Calculated? The Formula, Explained",
    metaTitle: "How Is EMI Calculated? Formula, Example and Flat Rate Trap",
    description: "The EMI formula with a worked example, where each payment goes, the flat-rate trick that doubles your interest, and how prepayments save money.",
    cluster: "finance",
    kind: "explainer",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how is emi calculated",
    keywords: ["emi formula", "emi calculation", "flat vs reducing interest", "loan emi", "prepayment"],
    relatedTools: ["finance/loan-calculator", "finance/auto-loan-calculator"],
    relatedPosts: ["how-long-should-a-car-loan-be", "15-vs-30-year-mortgage"],
  },
  {
    slug: "how-much-emergency-fund",
    title: "How Much Should Be in an Emergency Fund?",
    metaTitle: "How Much Should Be in an Emergency Fund? 3 or 6 Months?",
    description: "Three to six months of essential costs — here's how to work out yours, when you need more, where to keep it and how to build it without stalling.",
    cluster: "finance",
    kind: "guide",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how much should be in an emergency fund",
    keywords: ["emergency fund", "3 to 6 months expenses", "rainy day fund", "where to keep emergency fund", "how big emergency fund"],
    relatedTools: ["finance/savings-goal-calculator"],
    relatedPosts: ["how-inflation-affects-savings"],
  },
  {
    slug: "4-percent-rule",
    title: "The 4% Rule for Retirement: How It Works and Its Limits",
    metaTitle: "What Is the 4% Rule? Retirement Withdrawals Explained",
    description: "Where the 4% rule came from, how to use it to set a retirement target, why experts now argue for 3.7% or 4.7%, and what it doesn't account for.",
    cluster: "finance",
    kind: "explainer",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 6,
    primaryKeyword: "what is the 4% rule",
    keywords: ["4 percent rule", "safe withdrawal rate", "how much do i need to retire", "25x rule", "trinity study"],
    relatedTools: ["finance/retirement-calculator", "finance/compound-interest-calculator"],
    relatedPosts: ["how-inflation-affects-savings", "simple-vs-compound-interest"],
  },
  {
    slug: "how-inflation-affects-savings",
    title: "How Inflation Affects Your Savings (and What to Do About It)",
    metaTitle: "How Inflation Affects Savings — and How to Protect Them",
    description: "Why a savings balance that never falls can still lose value, how to work out your real return, the rule of 70, and ways to protect your money.",
    cluster: "finance",
    kind: "explainer",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how does inflation affect savings",
    keywords: ["inflation and savings", "real interest rate", "rule of 70", "purchasing power", "beat inflation"],
    relatedTools: ["finance/inflation-calculator", "finance/savings-goal-calculator"],
    relatedPosts: ["how-much-emergency-fund", "4-percent-rule"],
  },
  {
    slug: "simple-vs-compound-interest",
    title: "Simple vs Compound Interest: What's the Difference?",
    metaTitle: "Simple vs Compound Interest: Differences and Examples",
    description: "Simple interest is paid on the original amount; compound interest grows on itself. Formulas, a 30-year comparison, APR vs APY, and where each is used.",
    cluster: "finance",
    kind: "comparison",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "simple vs compound interest",
    keywords: ["simple interest", "compound interest", "simple interest formula", "apr vs apy", "compounding"],
    relatedTools: ["finance/simple-interest-calculator", "finance/compound-interest-calculator"],
    relatedPosts: ["4-percent-rule", "how-credit-card-interest-is-calculated"],
  },
  {
    slug: "how-to-calculate-roi",
    title: "How to Calculate ROI (and Why Annualized Return Matters)",
    metaTitle: "How to Calculate ROI — Formula, Examples and Annual Return",
    description: "The ROI formula with examples, why you must annualize to compare investments fairly, ROI for marketing, and what ROI leaves out.",
    cluster: "finance",
    kind: "how-to",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how to calculate roi",
    keywords: ["roi formula", "return on investment", "annualized return", "cagr", "marketing roi"],
    relatedTools: ["finance/roi-calculator", "finance/profit-margin-calculator"],
    relatedPosts: ["what-is-a-good-rental-yield", "margin-vs-markup"],
  },
  {
    slug: "margin-vs-markup",
    title: "Margin vs Markup: The Difference That Costs Businesses Money",
    metaTitle: "Margin vs Markup: Formulas, Table and Common Mistakes",
    description: "Markup is profit over cost; margin is profit over price. The formulas, a conversion table, how discounts eat margin, and which one to use.",
    cluster: "finance",
    kind: "comparison",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "margin vs markup",
    keywords: ["profit margin", "markup formula", "margin to markup", "gross margin", "pricing"],
    relatedTools: ["finance/profit-margin-calculator", "finance/discount-calculator"],
    relatedPosts: ["how-to-calculate-vat", "how-to-calculate-roi"],
  },
  {
    slug: "how-to-calculate-vat",
    title: "How to Calculate VAT: Add or Remove It the Right Way",
    metaTitle: "How to Calculate VAT — Add or Remove 20% VAT Correctly",
    description: "Add VAT by multiplying by 1.2; remove it by dividing — not by taking 20% off. UK rates, zero-rated vs exempt, and GST/HST in other countries.",
    cluster: "finance",
    kind: "how-to",
    published: "2026-10-01",
    authorId: "editorial",
    readingMinutes: 5,
    primaryKeyword: "how to calculate vat",
    keywords: ["remove vat", "add vat", "vat formula", "reverse vat", "gst calculation", "uk vat rates"],
    relatedTools: ["finance/vat-calculator", "finance/profit-margin-calculator"],
    relatedPosts: ["margin-vs-markup"],
  },
];

const bySlug = new Map(posts.map((p) => [p.slug, p]));

export const postHref = (p: Pick<PostMeta, "slug">) => `/blog/${p.slug}`;
export const getPost = (slug: string) => bySlug.get(slug);

/** Newest first, by last update. */
export const sortedPosts = [...posts].sort((a, b) => (b.updated ?? b.published).localeCompare(a.updated ?? a.published));

export function latestPosts(limit = 6, cluster?: string): PostMeta[] {
  return sortedPosts.filter((p) => !cluster || p.cluster === cluster).slice(0, limit);
}

/** Articles that help with a tool — the tool page's "Related guides". */
export function postsForTool(toolKey: string, limit = 3): PostMeta[] {
  return sortedPosts.filter((p) => p.relatedTools.includes(toolKey)).slice(0, limit);
}

/** Hand-picked first, then articles sharing tools, then the same cluster. */
export function relatedPosts(post: PostMeta, limit = 3): PostMeta[] {
  const out: PostMeta[] = [];
  const add = (p?: PostMeta) => {
    if (p && p.slug !== post.slug && !out.includes(p) && out.length < limit) out.push(p);
  };
  post.relatedPosts?.forEach((s) => add(bySlug.get(s)));
  sortedPosts.filter((p) => p.relatedTools.some((t) => post.relatedTools.includes(t))).forEach(add);
  sortedPosts.filter((p) => p.cluster === post.cluster).forEach(add);
  return out;
}

/** Previous (older) and next (newer) article in the same cluster. */
export function adjacentPosts(post: PostMeta): { prev?: PostMeta; next?: PostMeta } {
  const cluster = sortedPosts.filter((p) => p.cluster === post.cluster);
  const i = cluster.findIndex((p) => p.slug === post.slug);
  return { next: i > 0 ? cluster[i - 1] : undefined, prev: i < cluster.length - 1 ? cluster[i + 1] : undefined };
}

export const KIND_LABEL: Record<PostMeta["kind"], string> = {
  pillar: "Complete guide",
  "how-to": "How-to",
  guide: "Guide",
  explainer: "Explainer",
  comparison: "Comparison",
};

export const POSTS_PER_PAGE = 12;
