/**
 * Every live tool that has an interface. Shared by the server (which pages to
 * build) and the client mount map in ./mounts.tsx, which must list exactly these
 * keys — TypeScript enforces it.
 */
export const TOOL_KEYS = [
  "text/remove-duplicate-lines",
  "text/sort-lines",
  "text/whitespace-remover",
  "text/text-diff",
  "text/lorem-ipsum-generator",
  "image/compressor",
  "image/resizer",
  "image/cropper",
  "image/converter",
  "image/color-extractor",
  "image/image-to-base64",
  "image/svg-to-png",
  "pdf/merge",
  "pdf/split",
  "pdf/images-to-pdf",
  "developer/json-formatter",
  "developer/url-encoder",
  "developer/base64",
  "developer/html-entities",
  "developer/hash-generator",
  "developer/uuid-generator",
  "developer/jwt-decoder",
  "developer/timestamp-converter",
  "developer/regex-tester",
  "color/color-converter",
  "color/contrast-checker",
  "color/shades-generator",
  "css/gradient-generator",
  "css/box-shadow-generator",
  "css/border-radius-generator",
  "css/minifier",
  "productivity/qr-code-generator",
  "productivity/password-generator",
  "productivity/list-randomizer",
  "productivity/random-number-generator",
  "calculators/percentage-calculator",
  "calculators/age-calculator",
  "seo/meta-tag-generator",
  "seo/slug-generator",
  "marketing/utm-builder",
  "text/case-converter",
  "text/word-counter",
  "youtube/comment-analyzer",
  "youtube/cpm-calculator",
  "youtube/description-generator",
  "youtube/embed-generator",
  "youtube/hashtag-generator",
  "youtube/engagement-calculator",
  "youtube/revenue-calculator",
  "youtube/rpm-calculator",
  "youtube/thumbnail-analyzer",
  "youtube/thumbnail-downloader",
  "youtube/thumbnail-preview",
  "youtube/thumbnail-readability",
  "youtube/thumbnail-safe-zone",
  "youtube/timestamp-generator",
  "youtube/video-id-finder",
  "youtube/watch-time-calculator",
] as const;

export type ToolKey = (typeof TOOL_KEYS)[number];

const keySet: ReadonlySet<string> = new Set(TOOL_KEYS);
export const hasInterface = (key: string): key is ToolKey => keySet.has(key);
